name = "MolecularDynamicsFormalization"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["MolecularDynamicsFormalization", "Blueprint"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.34.0"

[[lean_lib]]
name = "MolecularDynamicsFormalization"
roots = ["MolecularDynamicsFormalization", "MolecularDynamics"]
globs = ["MolecularDynamicsFormalization", "MolecularDynamics.+"]

[[lean_lib]]
name = "Blueprint"
roots = ["Blueprint.Ch01", "Blueprint.Ch02", "Blueprint.Ch03", "Blueprint.Ch04"]
globs = ["Blueprint.Ch01", "Blueprint.Ch02", "Blueprint.Ch03", "Blueprint.Ch04"]
