import Mathlib
import MolecularDynamicsFormalization

-- Check small MathCopilot drafts here before moving them into the library.
#check MolecularDynamics.Position
#check MolecularDynamics.SeparableEnergy.hamiltonian
#check MolecularDynamics.massHamiltonian
#check MolecularDynamics.hamiltonianVectorField
#check MolecularDynamics.mechanical_energy_const_on_Ioo
#check MolecularDynamics.exists_localMechanicalIVP_open_of_force_contDiffAt
#check MolecularDynamics.mechanicalSolution_eventually_unique_of_contDiffAt
#check MolecularDynamics.totalMomentumCoordinate_const_on_Ioo
#check MolecularDynamics.uniformPairPotentialEnergy
#check MolecularDynamics.uniformPairPotentialEnergy_translate
#check MolecularDynamics.uniformPairPotentialEnergy_two
#check MolecularDynamics.nearestNeighborPotentialEnergy
#check MolecularDynamics.nearestNeighborPotentialEnergy_translate
#check MolecularDynamics.nearestNeighborPotentialEnergy_two
#check MolecularDynamics.periodicNearestNeighborPotentialEnergy
#check MolecularDynamics.periodicNearestNeighborPotentialEnergy_translate
#check MolecularDynamics.walledNearestNeighborPotentialEnergy
#check MolecularDynamics.boxPeriodicNearestNeighborPotentialEnergy
#check MolecularDynamics.boxPeriodicNearestNeighborPotentialEnergy_translate
#check MolecularDynamics.gradientLinearizationRemainder
#check MolecularDynamics.gradientLinearizationRemainder_isLittleO
#check MolecularDynamics.gradientLinearization_expansion
#check MolecularDynamics.potentialHessian_quadratic_nonneg_of_posDef
#check MolecularDynamics.linearizedHamiltonianQuadratic_nonneg_of_positive_hessian
#check MolecularDynamics.realNormalMode
#check MolecularDynamics.realNormalMode_eq_linearExponentialFlow
#check MolecularDynamics.mechanicalNormalMode_pair
#check MolecularDynamics.hasDerivAt_mechanicalNormalMode
#check MolecularDynamics.IsConstantVariationalSolution
#check MolecularDynamics.linearExponentialFlow_isConstantVariationalSolution
#check MolecularDynamics.constantVariationalSolution_unique
#check MolecularDynamics.matrixExponential_zero
#check MolecularDynamics.matrixExponential_add_of_commute
#check MolecularDynamics.matrixExponential_neg
#check MolecularDynamics.matrixExponentialFlow_realEigenmode
#check MolecularDynamics.matrixExponentialFlow_diagonal
#check MolecularDynamics.matrixExponential_conjugate
#check MolecularDynamics.upperTriangularMatrix
#check MolecularDynamics.upperTriangularFlow
#check MolecularDynamics.hasDerivAt_positionPair
#check MolecularDynamics.hasDerivAt_upperTriangularFlow
#check MolecularDynamics.matrixExponentialFlow_upperTriangular
#check MolecularDynamics.twoBodyCenterOfMass
#check MolecularDynamics.twoBodySeparation
#check MolecularDynamics.twoBodyCenterVelocity
#check MolecularDynamics.twoBodyRelativeVelocity
#check MolecularDynamics.twoBody_reconstruct_first
#check MolecularDynamics.twoBody_reconstruct_second
#check MolecularDynamics.twoBody_center_roundtrip
#check MolecularDynamics.twoBody_separation_roundtrip
#check MolecularDynamics.twoBody_equalMass_kinetic_decomposition
#check MolecularDynamics.twoBodyRadialLagrangian
#check MolecularDynamics.twoBody_equalMass_lagrangian_center_relative
#check MolecularDynamics.strictPotentialMin_mechanicalEquilibrium
#check MolecularDynamics.momentum_norm_sq_le
#check MolecularDynamics.isCompact_phaseEnergySublevel
#check MolecularDynamics.mechanicalSolution_phase_dist_lt
#check MolecularDynamics.mechanicalSolution_has_rightEndpointLimit_of_compact
#check MolecularDynamics.mechanicalSolution_unique_on_preconnected_of_contDiffAt
#check MolecularDynamics.mechanicalSolution_glue_on_Ioo
#print axioms MolecularDynamics.exists_rightEndpointLimit_of_lipschitzOnWith
#print axioms MolecularDynamics.exists_rightEndpointLimit_mem_of_lipschitzOnWith
#print axioms MolecularDynamics.mechanicalSolution_lipschitzOnWith_of_field_bound
#print axioms MolecularDynamics.mechanicalSolution_has_rightEndpointLimit_of_field_bound
#print axioms MolecularDynamics.mechanicalSolution_has_rightEndpointLimit_of_compact
#print axioms MolecularDynamics.mechanicalSolution_unique_on_preconnected_of_contDiffAt
#print axioms MolecularDynamics.mechanicalSolution_glue_on_Ioo
#check MolecularDynamics.mechanicalSolution_extend_of_compact
#print axioms MolecularDynamics.hasDerivWithinAt_rightEndpoint_of_continuousOn
#print axioms MolecularDynamics.exists_localODE_matching_rightEndpoint
#print axioms MolecularDynamics.mechanicalSolution_extend_of_rightEndpointLimit
#print axioms MolecularDynamics.mechanicalSolution_extend_of_force_contDiffAt
#print axioms MolecularDynamics.mechanicalSolution_extend_of_compact

#print axioms MolecularDynamics.momentumKineticEnergy_eq_inner
#print axioms MolecularDynamics.massHamiltonian_massOperator
#print axioms MolecularDynamics.massHamiltonian_particle
#print axioms MolecularDynamics.hasGradientAt_momentumKineticEnergy
#print axioms MolecularDynamics.hasGradientAt_position_slice
#print axioms MolecularDynamics.hamiltonianVectorField_eq
#print axioms MolecularDynamics.massHamiltonian_velocityOperator
#print axioms MolecularDynamics.mechanical_energy_hasDerivAt_zero
#print axioms MolecularDynamics.mechanical_energy_const_on_Ioo
#print axioms MolecularDynamics.exists_localMechanicalIVP_open_of_force_contDiffAt
#print axioms MolecularDynamics.mechanicalSolution_unique_on_Ioo
#print axioms MolecularDynamics.mechanicalSolution_eventually_unique_of_contDiffAt
#print axioms MolecularDynamics.totalMomentumCoordinate_const_on_Ioo
#print axioms MolecularDynamics.strictPotentialMin_mechanicalEquilibrium
#print axioms MolecularDynamics.momentum_norm_sq_le
#print axioms MolecularDynamics.momentum_norm_le_of_energy
#print axioms MolecularDynamics.isCompact_phaseEnergySublevel
#print axioms MolecularDynamics.mechanicalSolution_below_barrier_stays_in_ball
#print axioms MolecularDynamics.mechanicalSolution_phase_dist_lt

namespace MolecularDynamics

/-- One mass for each of the `n = N_c` configuration coordinates. -/
abbrev ScratchCoordinateMasses (n : ℕ) := Fin n → ℝ

/-- The diagonal mass matrix associated with coordinate masses. -/
def scratchDiagonalMassMatrix {n : ℕ} (masses : ScratchCoordinateMasses n) :
    MassMatrix n :=
  Matrix.diagonal masses

/-- Pointwise form of textbook equation (1.3), including both displayed equalities. -/
def ScratchNBodyEquationAt {n : ℕ} (masses : ScratchCoordinateMasses n)
    (force : Force n) (potential : PotentialEnergy n) (position acceleration : Position n) :
    Prop :=
  (scratchDiagonalMassMatrix masses).mulVec acceleration = force position ∧
    force position = -gradient potential position

/-- The coordinate form of the kinetic-energy sum in textbook equation (1.4). -/
noncomputable def scratchKineticEnergy {n : ℕ} (masses : ScratchCoordinateMasses n) :
    Velocity n → ℝ :=
  fun velocity => ∑ i, masses i * (velocity i) ^ 2 / 2

/-- Textbook equation (1.4): kinetic plus potential energy. -/
noncomputable def scratchTotalEnergy {n : ℕ} (masses : ScratchCoordinateMasses n)
    (potential : PotentialEnergy n) (position : Position n) (velocity : Velocity n) : ℝ :=
  scratchKineticEnergy masses velocity + potential position

end MolecularDynamics
#print axioms MolecularDynamics.exists_glued_function_of_compatible
#print axioms MolecularDynamics.exists_mechanicalSolutionOn_iUnion
#print axioms MolecularDynamics.exists_globalMechanicalSolution_of_local_compact_confinement
#print axioms MolecularDynamics.exists_globalMechanicalIVP_of_energy_barrier
#print axioms MolecularDynamics.gradient_contDiffAt_of_potential_contDiffAt_two
#print axioms MolecularDynamics.strictPotentialMin_exists_future_bound
#print axioms MolecularDynamics.strictPotentialMin_futureStable
#print axioms MolecularDynamics.strictPotentialMin_futureStable_of_potential_contDiffAt_two
#print axioms MolecularDynamics.product_dist_le_phaseEuclideanDistance
#print axioms MolecularDynamics.phaseEuclideanDistance_le_two_mul_dist
#print axioms MolecularDynamics.IsFutureMechanicalStable.euclidean
#print axioms MolecularDynamics.strictPotentialMin_futureStableEuclidean_of_potential_contDiffAt_two
#print axioms MolecularDynamics.strictPotentialMin_futureStableEuclidean_of_smooth
#check MolecularDynamics.strictPotentialMin_futureStableEuclidean_of_smooth
#print axioms MolecularDynamics.nBodyKineticEnergy_eq_inner
#print axioms MolecularDynamics.hasGradientAt_nBodyKineticEnergy
#print axioms MolecularDynamics.hasGradientAt_massLagrangian_velocity
#print axioms MolecularDynamics.hasGradientAt_massLagrangian_position
#print axioms MolecularDynamics.mechanicalSolution_eulerLagrange
#print axioms MolecularDynamics.eulerLagrange_to_mechanicalSolution
#print axioms MolecularDynamics.massLagrangian_coordinateChange
#print axioms MolecularDynamics.hasDerivAt_coordinateChange
#print axioms MolecularDynamics.generalizedMassMatrix_posDef
#print axioms MolecularDynamics.generalizedMassMatrix_isUnit
#print axioms MolecularDynamics.massHamiltonian_legendre_gap
#print axioms MolecularDynamics.legendre_objective_le_massHamiltonian
#print axioms MolecularDynamics.legendre_objective_attains_massHamiltonian
#print axioms MolecularDynamics.nBodyKineticEnergy_eq_zero_iff
#print axioms MolecularDynamics.legendre_objective_eq_massHamiltonian_iff
#print axioms MolecularDynamics.massHamiltonian_eq_legendre_sup
#print axioms MolecularDynamics.mechanicalSolution_translate_on_Ioi
#print axioms MolecularDynamics.futureMechanicalFlow_add
#print axioms MolecularDynamics.futureMechanicalFlow_commute
#print axioms MolecularDynamics.futureMechanicalFlow_energy
#print axioms MolecularDynamics.futureMechanicalFlow_injOn
#print axioms MolecularDynamics.exists_futureMechanicalFlow_of_energy_barrier
#print axioms MolecularDynamics.massHamiltonian_momentumReflection
#print axioms MolecularDynamics.mechanicalSolution_time_reverse_on_Iio
#print axioms MolecularDynamics.exists_globalMechanicalIVP_of_energy_barrier_two_sided
#print axioms MolecularDynamics.mechanicalSolution_translate_on_univ
#print axioms MolecularDynamics.mechanicalSolution_energy_on_univ
#print axioms MolecularDynamics.globalMechanicalFlow_add
#print axioms MolecularDynamics.globalMechanicalFlow_inverse
#print axioms MolecularDynamics.globalMechanicalFlow_commute
#print axioms MolecularDynamics.globalMechanicalFlow_bijOn
#print axioms MolecularDynamics.globalMechanicalFlow_energy
#print axioms MolecularDynamics.exists_globalMechanicalFlow_of_energy_barrier
#print axioms MolecularDynamics.harmonicFlow_isMechanicalSolution
#print axioms MolecularDynamics.harmonicFlow_isGlobalFlow
#print axioms MolecularDynamics.harmonicFlow_continuous
#print axioms MolecularDynamics.harmonicFlow_add
#print axioms MolecularDynamics.harmonicFlow_inverse
#print axioms MolecularDynamics.harmonicContinuousFlow
#print axioms MolecularDynamics.hasGradientAt_harmonicPotential
#print axioms MolecularDynamics.harmonicFlow_energy
#print axioms MolecularDynamics.freeParticleFlow_isMechanicalSolution
#print axioms MolecularDynamics.freeParticleFlow_isGlobalFlow
#print axioms MolecularDynamics.freeParticleFlow_continuous
#print axioms MolecularDynamics.freeParticleFlow_add
#print axioms MolecularDynamics.freeParticleContinuousFlow
#print axioms MolecularDynamics.freeParticleFlow_energy
#print axioms MolecularDynamics.hasDerivAt_linearExponentialFlow
#print axioms MolecularDynamics.linearExponentialFlow_add
#print axioms MolecularDynamics.linearExponentialFlow_continuous
#print axioms MolecularDynamics.linearContinuousFlow
#print axioms MolecularDynamics.linearExponentialFlow_inverse
#print axioms MolecularDynamics.hasDerivAt_linearExponentialFlow_initial_time
#print axioms MolecularDynamics.linearExponentialFlow_unique
#print axioms MolecularDynamics.linearExponentialOperator_series
#print axioms MolecularDynamics.matrixExponentialFlow_eq
#print axioms MolecularDynamics.hasDerivAt_matrixExponentialFlow
#print axioms MolecularDynamics.hasDerivAt_matrixExponentialFlow_initial_time
#print axioms MolecularDynamics.matrixExponentialFlow_unique
#print axioms MolecularDynamics.matrixContinuousFlow
#print axioms MolecularDynamics.matrixExponential_series
#print axioms MolecularDynamics.hasDerivAt_realEigenmode
#print axioms MolecularDynamics.linearExponentialFlow_realEigenmode
#print axioms MolecularDynamics.linearExponentialFlow_realSpectral_sum
#print axioms MolecularDynamics.linearExponentialFlow_realEigenbasis
#print axioms MolecularDynamics.hasDerivAt_complexEigenmode
#print axioms MolecularDynamics.complexExponentialFlow_eigenmode
#print axioms MolecularDynamics.complexExponentialFlow_spectral_sum
#print axioms MolecularDynamics.complexExponentialFlow_eigenbasis
#print axioms MolecularDynamics.hasDerivAt_complexExponentialFlow
#print axioms MolecularDynamics.complexContinuousFlow
#print axioms MolecularDynamics.complexEigenbasis_coefficients_unique
#print axioms MolecularDynamics.linearExponentialFlow_intertwine
#print axioms MolecularDynamics.linearExponentialFlow_fixed_clm
#print axioms MolecularDynamics.realMatrix_conjugation_commute
#print axioms MolecularDynamics.realMatrix_complexFlow_isReal
#print axioms MolecularDynamics.realMatrix_complexSpectral_sum_isReal
#print axioms MolecularDynamics.basisColumnMatrix_mulVec
#print axioms MolecularDynamics.basisColumnMatrix_mulVec_repr
#print axioms MolecularDynamics.basisColumnMatrix_isUnit
#print axioms MolecularDynamics.basisColumnMatrix_inverse_coefficients
#print axioms MolecularDynamics.firstIntegral_hasDerivAt_zero
#print axioms MolecularDynamics.firstIntegral_const_on_Ioo
#print axioms MolecularDynamics.firstIntegral_differential_necessary
#print axioms MolecularDynamics.isFirstIntegralOn_iff_differential
#print axioms MolecularDynamics.firstIntegral_gradient_criterion
#print axioms MolecularDynamics.planarAngularMomentum_hasDerivAt_zero
#print axioms MolecularDynamics.planarAngularMomentum_const_on_Ioo
#print axioms MolecularDynamics.centralForce_planarAngularMomentum_const
#print axioms MolecularDynamics.polarKinetic_identity
#print axioms MolecularDynamics.polarAngularMomentum_identity
#print axioms MolecularDynamics.keplerPolarLagrangian_identity
#print axioms MolecularDynamics.polarCoordinates_hasDerivAt_components
#print axioms MolecularDynamics.polarJacobian_det
#print axioms MolecularDynamics.polarJacobian_isUnit_iff
#print axioms MolecularDynamics.hasGradientAt_keplerPotential
#print axioms MolecularDynamics.keplerForce_eq_neg_gradient
#print axioms MolecularDynamics.keplerForce_contDiffAt
#print axioms MolecularDynamics.exists_kepler_localIVP
#print axioms MolecularDynamics.kepler_energy_const_on_Ioo
#print axioms MolecularDynamics.kepler_planarAngularMomentum_const_on_Ioo
#print axioms MolecularDynamics.hasStrictFDerivAt_polarCoordinateMap
#print axioms MolecularDynamics.exists_polarDerivativeEquiv
#print axioms MolecularDynamics.fderiv_polarCoordinateMap
#print axioms MolecularDynamics.exists_polarLocalChart_strictInverse
#print axioms MolecularDynamics.exists_polarLocalChart
#print axioms MolecularDynamics.keplerPolar_partial_v
#print axioms MolecularDynamics.keplerPolar_partial_ω
#print axioms MolecularDynamics.keplerPolar_partial_r
#print axioms MolecularDynamics.keplerPolar_partial_θ
#print axioms MolecularDynamics.keplerPolar_eulerLagrange_iff
#print axioms MolecularDynamics.keplerPolar_angular_const
#print axioms MolecularDynamics.keplerPolar_radial_reduction
#print axioms MolecularDynamics.keplerRadialEnergy_formula
#print axioms MolecularDynamics.keplerRadialEnergy_hasDerivAt_zero
#print axioms MolecularDynamics.keplerPolar_radialEnergy_const
#print axioms MolecularDynamics.keplerPolar_angle_integral
#print axioms MolecularDynamics.keplerPolar_radialEnergy_const_initialAngular
#print axioms MolecularDynamics.keplerPolar_energy_radial_identity
#print axioms MolecularDynamics.norm_polarCartesianPosition
#print axioms MolecularDynamics.polarCartesianState_angular
#print axioms MolecularDynamics.polarCartesianState_energy
#print axioms MolecularDynamics.hasDerivAt_planarPair
#print axioms MolecularDynamics.keplerPolar_angularVelocity_hasDerivAt
#print axioms MolecularDynamics.polarCartesianState_momentum_hasDerivAt
#print axioms MolecularDynamics.keplerPolarEL_to_cartesianMechanical
#print axioms MolecularDynamics.polarCartesianState_force
#print axioms MolecularDynamics.polarCartesianState_radialVelocity
#print axioms MolecularDynamics.cartesianMechanical_to_keplerPolarEL
#print axioms MolecularDynamics.keplerPolarEL_iff_cartesianMechanical
#print axioms MolecularDynamics.keplerReconstructedAngle_initial
#print axioms MolecularDynamics.keplerReconstructedAngle_hasDerivAt
#print axioms MolecularDynamics.keplerRadial_reconstruction_isEulerLagrange
#print axioms MolecularDynamics.keplerRadial_reconstruction_isMechanical
#print axioms MolecularDynamics.keplerRadialForce_contDiffAt
#print axioms MolecularDynamics.exists_keplerRadial_localIVP
#print axioms MolecularDynamics.exists_keplerRadial_reconstructed_localIVP
#print axioms MolecularDynamics.exists_polarCartesian_initialRepresentation
#print axioms MolecularDynamics.exists_kepler_localIVP_radialReconstruction
#print axioms MolecularDynamics.separableTimePrimitive_initial
#print axioms MolecularDynamics.separableTimePrimitive_hasStrictDerivAt
#print axioms MolecularDynamics.separableTimePrimitive_localInverse
#print axioms MolecularDynamics.separableTimePrimitive_along_solution
#print axioms MolecularDynamics.separableTimePrimitive_inverse_along_solution
#print axioms MolecularDynamics.keplerRadial_energy_speedSquare
#print axioms MolecularDynamics.keplerRadialBranchSpeed_eq_velocity
#print axioms MolecularDynamics.keplerRadialSpeedSquare_continuousAt
#print axioms MolecularDynamics.keplerRadialEnergy_const_on_Ioo
#print axioms MolecularDynamics.keplerRadial_signedQuadrature_inverse_on_branch
#print axioms MolecularDynamics.exists_keplerRadial_nonturning_window
#print axioms MolecularDynamics.keplerRadial_nonturning_signedQuadrature
#print axioms MolecularDynamics.keplerRadial_nonturning_quadrature
#print axioms MolecularDynamics.harmonicAction_time_formula
#print axioms MolecularDynamics.harmonicAction_harmonicFlow
#print axioms MolecularDynamics.harmonicActionAmplitude_pos
#print axioms MolecularDynamics.harmonicActionVelocity_formula
#print axioms MolecularDynamics.harmonicAction_energy
#print axioms MolecularDynamics.harmonicActionAmplitude_hasDerivAt
#print axioms MolecularDynamics.harmonicAction_hasDerivAt_components
#print axioms MolecularDynamics.harmonicAction_derivative_coefficients_iff
#print axioms MolecularDynamics.harmonicAction_ode_iff
#print axioms MolecularDynamics.harmonicAction_explicit_solution
#print axioms MolecularDynamics.exists_harmonicAction_representation
#print axioms MolecularDynamics.harmonicActionAmplitude_hasStrictDerivAt
#print axioms MolecularDynamics.harmonicActionJacobian_det
#print axioms MolecularDynamics.hasStrictFDerivAt_harmonicActionMap
#print axioms MolecularDynamics.fderiv_harmonicActionMap
#print axioms MolecularDynamics.exists_harmonicActionLocalChart
#print axioms MolecularDynamics.harmonicTorusPhase_rotation_coordinates
#print axioms MolecularDynamics.harmonicTorusPhase_rotation_isMechanical
#print axioms MolecularDynamics.harmonicTorusRotation_continuous
#print axioms MolecularDynamics.harmonicTorusRotation_add
#print axioms MolecularDynamics.harmonicTorusRotation_periodic_iff
#print axioms MolecularDynamics.harmonicTorusRotation_periodic_iff_integer
#print axioms MolecularDynamics.harmonicTorusRotation_integerFrequencies_periodic
#print axioms MolecularDynamics.harmonicTorusPhase_continuous
#print axioms MolecularDynamics.harmonicTorusPhase_realAngles
#print axioms MolecularDynamics.harmonicTorusPhase_energy
#print axioms MolecularDynamics.harmonicTorusPhase_image_fixedEnergy
#print axioms MolecularDynamics.harmonicTorusPhase_injective
#print axioms MolecularDynamics.harmonicTorusPhase_isClosedEmbedding
#print axioms MolecularDynamics.exists_harmonicTorusPhase_homeomorph
#print axioms MolecularDynamics.harmonicTorusThreeResonance_rotation
#print axioms MolecularDynamics.harmonicTorusRotation_three_resonant_not_dense
#print axioms MolecularDynamics.harmonicTorusRotation_two_dense_zero
#print axioms MolecularDynamics.harmonicTorusRotation_two_dense
#print axioms MolecularDynamics.harmonicTorusPhase_two_dense_fixedEnergy
#print axioms MolecularDynamics.harmonicTorusRotation_two_positivePeriod_iff_rational
#print axioms MolecularDynamics.harmonicTorusRotation_two_irrational_no_positivePeriod
#print axioms MolecularDynamics.harmonicTorusPhase_periodic_of_rotation_periodic
#print axioms MolecularDynamics.harmonicTorusPhase_periodic_iff_rotation_periodic
#print axioms MolecularDynamics.harmonicTorusPhase_two_positivePeriod_iff_rational
#print axioms MolecularDynamics.harmonicTorusPhase_two_irrational_no_positivePeriod
#print axioms MolecularDynamics.planarScalarPartial_isInvertible
#print axioms MolecularDynamics.exists_planarFirstIntegral_localGraph
#print axioms MolecularDynamics.planarFirstIntegral_localGraph_reduction
#print axioms MolecularDynamics.exists_planarFirstIntegral_C1Graph
#print axioms MolecularDynamics.exists_planarFirstIntegral_quadratureWindow
#print axioms MolecularDynamics.planarFirstIntegral_nonturning_quadrature
#print axioms MolecularDynamics.scalarPotentialEnergy_contDiff
#print axioms MolecularDynamics.scalarPotentialVectorField_contDiff
#print axioms MolecularDynamics.scalarPotentialEnergy_hasDerivAt_zero
#print axioms MolecularDynamics.scalarPotentialEnergy_isFirstIntegral
#print axioms MolecularDynamics.scalarPotentialEnergy_velocityPartial
#print axioms MolecularDynamics.scalarPotential_nonturning_quadrature
#print axioms MolecularDynamics.scalarPotentialSwappedEnergy_contDiff
#print axioms MolecularDynamics.scalarPotentialSwappedField_contDiff
#print axioms MolecularDynamics.scalarPotentialSwappedEnergy_isFirstIntegral
#print axioms MolecularDynamics.scalarPotentialSwappedEnergy_positionPartial
#print axioms MolecularDynamics.scalarPotential_regularTurning_quadrature
#print axioms MolecularDynamics.scalarPotential_equilibrium_constant
#print axioms MolecularDynamics.scalarPotential_equilibrium_locally_unique
#print axioms MolecularDynamics.scalarPotential_equilibrium_on_Ioo
#print axioms MolecularDynamics.scalarPotential_localDescription
#print axioms MolecularDynamics.scalarPotential_exists_localIVP
#print axioms MolecularDynamics.scalarPotential_exists_localIVP_integrable
#print axioms MolecularDynamics.equilibrium_constant_ode_iff
#print axioms MolecularDynamics.equilibriumLinearizationRemainder_isLittleO
#print axioms MolecularDynamics.equilibriumLinearizationRemainder_of_C1
#print axioms MolecularDynamics.actual_perturbation_ode
#print axioms MolecularDynamics.equilibrium_linearized_IVP
#print axioms MolecularDynamics.mechanicalLinearization_apply
#print axioms MolecularDynamics.hasFDerivAt_mechanicalVectorField
#print axioms MolecularDynamics.conservative_mechanical_linearization
#print axioms MolecularDynamics.exists_C1_localContinuousSolutionFamily
#print axioms MolecularDynamics.exists_localContinuousMechanicalFamily
#print axioms MolecularDynamics.exists_localContinuousMechanicalFamily_open
#print axioms MolecularDynamics.potential_hessian_symmetric
#print axioms MolecularDynamics.potential_hessian_symmetric_apply
#print axioms MolecularDynamics.conservative_linearization_hessian_data
#print axioms MolecularDynamics.linearizedHamiltonianQuadratic
#print axioms MolecularDynamics.linearizedHamiltonianQuadratic_eq_textbook_form
#print axioms MolecularDynamics.linearizedHamiltonianQuadratic_nonneg
#print axioms MolecularDynamics.linearizedHamiltonianQuadratic_nonneg_of_hessian

-- Theorem 2.1: full C¹ open-domain Euler convergence, not just a scalar recurrence.
#check MolecularDynamics.eulerStep
#check MolecularDynamics.eulerIterate
#check MolecularDynamics.eulerIterate_zero
#check MolecularDynamics.eulerIterate_succ
#check MolecularDynamics.eulerIterate_zero_step
#check MolecularDynamics.eulerMaxError
#check MolecularDynamics.eulerMaxError_le
#check MolecularDynamics.eulerStep_norm_sub_le
#check MolecularDynamics.euler_localDefect_of_derivative_bound
#check MolecularDynamics.exists_euler_trajectory_bounds
#check MolecularDynamics.euler_convergence_on_open
#check MolecularDynamics.theorem_2_1_euler

-- Section 2.2.3: actual one-step error recurrence, bound (2.12), and convergence.
#check MolecularDynamics.oneStepIterate
#check MolecularDynamics.oneStepIterate_zero
#check MolecularDynamics.oneStepIterate_succ
#check MolecularDynamics.oneStepMaxError
#check MolecularDynamics.oneStepMaxError_nonneg
#check MolecularDynamics.oneStepMaxError_le
#check MolecularDynamics.oneStep_error_recursion
#check MolecularDynamics.oneStep_error_bound
#check MolecularDynamics.oneStepMaxError_order_bound
#check MolecularDynamics.oneStep_converges_of_consistency_stability

-- Section 2.3.3: actual wedge form, sign convention and matrix pullback.
#check MolecularDynamics.SymplecticCoordinates
#check MolecularDynamics.SymplecticCoordinateMatrix
#check MolecularDynamics.textbookJ
#check MolecularDynamics.textbookJ_eq_neg_mathlibJ
#check MolecularDynamics.textbookJ_transpose
#check MolecularDynamics.textbookJ_squared
#check MolecularDynamics.textbookDq
#check MolecularDynamics.textbookDp
#check MolecularDynamics.textbookDq_apply
#check MolecularDynamics.textbookDp_apply
#check MolecularDynamics.textbookWedgeOneForms
#check MolecularDynamics.textbookWedgeOneForms_apply
#check MolecularDynamics.textbookSymplecticForm
#check MolecularDynamics.textbookSymplecticForm_coordinates
#check MolecularDynamics.textbookSymplecticForm_eq_sum_wedges
#check MolecularDynamics.textbookSymplecticForm_self
#check MolecularDynamics.textbookSymplecticForm_skew
#check MolecularDynamics.textbookSymplecticPullback
#check MolecularDynamics.textbookSymplecticPullback_apply
#check MolecularDynamics.textbookSymplecticPullback_matrix
#check MolecularDynamics.IsTextbookSymplectic
#check MolecularDynamics.isTextbookSymplectic_iff_pullback
#check MolecularDynamics.isTextbookSymplectic_iff_preserves_form
#check MolecularDynamics.isTextbookSymplectic_iff_mathlib
#check MolecularDynamics.isTextbookSymplectic_one
#check MolecularDynamics.IsTextbookSymplectic.mul
#check MolecularDynamics.IsTextbookSymplectic.det_eq_one
#check MolecularDynamics.IsTextbookSymplectic.det_square
#check MolecularDynamics.IsTextbookSymplectic.abs_det
#check MolecularDynamics.IsTextbookSymplectic.inv
#check MolecularDynamics.IsTextbookSymplectic.inv_formula

-- Sections 2.3.3--2.3.5: actual Jacobians and the genuine diffeomorphism group.
#check MolecularDynamics.textbookJacobian
#check MolecularDynamics.textbookJacobian_entry
#check MolecularDynamics.textbookJacobian_mulVec
#check MolecularDynamics.textbookJacobian_id
#check MolecularDynamics.textbookJacobian_comp
#check MolecularDynamics.IsTextbookSymplecticMap
#check MolecularDynamics.isTextbookSymplecticMap_iff_preserves_form
#check MolecularDynamics.isTextbookSymplecticMap_id
#check MolecularDynamics.IsTextbookSymplecticMap.comp
#check MolecularDynamics.IsTextbookSymplecticMap.jacobian_det_eq_one
#check MolecularDynamics.textbookJacobian_equiv_symm
#check MolecularDynamics.IsTextbookSymplecticEquiv
#check MolecularDynamics.isTextbookSymplecticEquiv_refl
#check MolecularDynamics.IsTextbookSymplecticEquiv.mul
#check MolecularDynamics.IsTextbookSymplecticEquiv.symm
#check MolecularDynamics.textbookSymplecticDiffeomorphismGroup
#check MolecularDynamics.textbookSymplecticDiffeomorphismGroup_mem_iff
#check MolecularDynamics.TextbookSymplecticDiffeomorphism
#check MolecularDynamics.textbookSymplecticDiffeomorphism_mul_apply
#synth Group (MolecularDynamics.TextbookSymplecticDiffeomorphism 2)

-- Section 2.3.4: actual time-dependent variational derivatives and Hessian symmetry.
#check MolecularDynamics.textbookHamiltonianHessian
#check MolecularDynamics.textbookHamiltonianHessian_isSymm
#check MolecularDynamics.hamiltonian_variational_matrix_cancellation
#check MolecularDynamics.hasDerivWithinAt_hamiltonian_variational_form
#check MolecularDynamics.hamiltonian_variational_form_constant
#check MolecularDynamics.hamiltonian_variational_isSymplectic
#check MolecularDynamics.hamiltonian_hessian_variational_isSymplectic
#check MolecularDynamics.hamiltonian_flow_isSymplectic_of_variational_equation

-- Section 2.3.6: actual C2 potential, symplectic Euler and its genuine inverse.
#check MolecularDynamics.textbookPositionProjection
#check MolecularDynamics.textbookPotentialForce
#check MolecularDynamics.contDiff_textbookPotentialForce
#check MolecularDynamics.textbookPotentialForce_matrix_isSymm
#check MolecularDynamics.textbookMomentumKick
#check MolecularDynamics.textbookPositionDrift
#check MolecularDynamics.textbookJacobian_momentumKick
#check MolecularDynamics.contDiff_textbookMomentumKick
#check MolecularDynamics.textbookJacobian_positionDrift
#check MolecularDynamics.textbookPositionDrift_isSymplectic
#check MolecularDynamics.textbookPotentialKick_isSymplectic
#check MolecularDynamics.textbookSymplecticEuler
#check MolecularDynamics.textbookSymplecticEuler_position
#check MolecularDynamics.textbookSymplecticEuler_momentum
#check MolecularDynamics.textbookSymplecticEuler_isSymplectic
#check MolecularDynamics.textbookPositionProjection_momentumKick
#check MolecularDynamics.textbookMomentumKick_neg_cancel
#check MolecularDynamics.textbookPositionDrift_neg_cancel
#check MolecularDynamics.textbookMomentumKickEquiv
#check MolecularDynamics.textbookPositionDriftEquiv
#check MolecularDynamics.textbookSymplecticEulerEquiv
#check MolecularDynamics.textbookSymplecticEulerEquiv_apply
#check MolecularDynamics.textbookSymplecticEulerEquiv_symm_apply
#check MolecularDynamics.textbookSymplecticEulerEquiv_isSymplectic

-- Section 2.3.7: actual inverse maps and adjoint methods.
#check MolecularDynamics.textbookAdjointMethod
#check MolecularDynamics.textbookAdjointMethod_apply_eq_iff
#check MolecularDynamics.textbookAdjointMethod_involutive
#check MolecularDynamics.textbookAdjointMethod_isSymplectic
#check MolecularDynamics.textbookFlowMethod
#check MolecularDynamics.textbookFlowMethod_isSelfAdjoint
#check MolecularDynamics.euler_negative_step_iff_backward
#check MolecularDynamics.euler_adjoint_iff_backward
#check MolecularDynamics.textbookAdjointSymplecticEuler
#check MolecularDynamics.textbookAdjointSymplecticEuler_apply
#check MolecularDynamics.textbookAdjointSymplecticEuler_position
#check MolecularDynamics.textbookAdjointSymplecticEuler_momentum
#check MolecularDynamics.textbookAdjointSymplecticEuler_isSymplectic
