import Mathlib
import MolecularDynamicsFormalization

-- Check small MathCopilot drafts here before moving them into the library.
#check MolecularDynamics.Position
#check MolecularDynamics.SeparableEnergy.hamiltonian
#check MolecularDynamics.massHamiltonian
#check MolecularDynamics.hamiltonianVectorField
#check MolecularDynamics.mechanical_energy_const_on_Ioo
#check MolecularDynamics.exists_localMechanicalIVP_open_of_force_contDiffAt
#check MolecularDynamics.mechanicalSolution_eventually_unique_of_contDiffAt
#check MolecularDynamics.totalMomentumCoordinate_const_on_Ioo
#check MolecularDynamics.uniformPairPotentialEnergy
#check MolecularDynamics.uniformPairPotentialEnergy_translate
#check MolecularDynamics.uniformPairPotentialEnergy_two
#check MolecularDynamics.nearestNeighborPotentialEnergy
#check MolecularDynamics.nearestNeighborPotentialEnergy_translate
#check MolecularDynamics.nearestNeighborPotentialEnergy_two
#check MolecularDynamics.periodicNearestNeighborPotentialEnergy
#check MolecularDynamics.periodicNearestNeighborPotentialEnergy_translate
#check MolecularDynamics.walledNearestNeighborPotentialEnergy
#check MolecularDynamics.boxPeriodicNearestNeighborPotentialEnergy
#check MolecularDynamics.boxPeriodicNearestNeighborPotentialEnergy_translate
#check MolecularDynamics.gradientLinearizationRemainder
#check MolecularDynamics.gradientLinearizationRemainder_isLittleO
#check MolecularDynamics.gradientLinearization_expansion
#check MolecularDynamics.potentialHessian_quadratic_nonneg_of_posDef
#check MolecularDynamics.linearizedHamiltonianQuadratic_nonneg_of_positive_hessian
#check MolecularDynamics.realNormalMode
#check MolecularDynamics.realNormalMode_eq_linearExponentialFlow
#check MolecularDynamics.mechanicalNormalMode_pair
#check MolecularDynamics.hasDerivAt_mechanicalNormalMode
#check MolecularDynamics.IsConstantVariationalSolution
#check MolecularDynamics.linearExponentialFlow_isConstantVariationalSolution
#check MolecularDynamics.constantVariationalSolution_unique
#check MolecularDynamics.matrixExponential_zero
#check MolecularDynamics.matrixExponential_add_of_commute
#check MolecularDynamics.matrixExponential_neg
#check MolecularDynamics.matrixExponentialFlow_realEigenmode
#check MolecularDynamics.matrixExponentialFlow_diagonal
#check MolecularDynamics.matrixExponential_conjugate
#check MolecularDynamics.upperTriangularMatrix
#check MolecularDynamics.upperTriangularFlow
#check MolecularDynamics.hasDerivAt_positionPair
#check MolecularDynamics.hasDerivAt_upperTriangularFlow
#check MolecularDynamics.matrixExponentialFlow_upperTriangular
#check MolecularDynamics.twoBodyCenterOfMass
#check MolecularDynamics.twoBodySeparation
#check MolecularDynamics.twoBodyCenterVelocity
#check MolecularDynamics.twoBodyRelativeVelocity
#check MolecularDynamics.twoBody_reconstruct_first
#check MolecularDynamics.twoBody_reconstruct_second
#check MolecularDynamics.twoBody_center_roundtrip
#check MolecularDynamics.twoBody_separation_roundtrip
#check MolecularDynamics.twoBody_equalMass_kinetic_decomposition
#check MolecularDynamics.twoBodyRadialLagrangian
#check MolecularDynamics.twoBody_equalMass_lagrangian_center_relative
#check MolecularDynamics.strictPotentialMin_mechanicalEquilibrium
#check MolecularDynamics.momentum_norm_sq_le
#check MolecularDynamics.isCompact_phaseEnergySublevel
#check MolecularDynamics.mechanicalSolution_phase_dist_lt
#check MolecularDynamics.mechanicalSolution_has_rightEndpointLimit_of_compact
#check MolecularDynamics.mechanicalSolution_unique_on_preconnected_of_contDiffAt
#check MolecularDynamics.mechanicalSolution_glue_on_Ioo
#print axioms MolecularDynamics.exists_rightEndpointLimit_of_lipschitzOnWith
#print axioms MolecularDynamics.exists_rightEndpointLimit_mem_of_lipschitzOnWith
#print axioms MolecularDynamics.mechanicalSolution_lipschitzOnWith_of_field_bound
#print axioms MolecularDynamics.mechanicalSolution_has_rightEndpointLimit_of_field_bound
#print axioms MolecularDynamics.mechanicalSolution_has_rightEndpointLimit_of_compact
#print axioms MolecularDynamics.mechanicalSolution_unique_on_preconnected_of_contDiffAt
#print axioms MolecularDynamics.mechanicalSolution_glue_on_Ioo
#check MolecularDynamics.mechanicalSolution_extend_of_compact
#print axioms MolecularDynamics.hasDerivWithinAt_rightEndpoint_of_continuousOn
#print axioms MolecularDynamics.exists_localODE_matching_rightEndpoint
#print axioms MolecularDynamics.mechanicalSolution_extend_of_rightEndpointLimit
#print axioms MolecularDynamics.mechanicalSolution_extend_of_force_contDiffAt
#print axioms MolecularDynamics.mechanicalSolution_extend_of_compact

#print axioms MolecularDynamics.momentumKineticEnergy_eq_inner
#print axioms MolecularDynamics.massHamiltonian_massOperator
#print axioms MolecularDynamics.massHamiltonian_particle
#print axioms MolecularDynamics.hasGradientAt_momentumKineticEnergy
#print axioms MolecularDynamics.hasGradientAt_position_slice
#print axioms MolecularDynamics.hamiltonianVectorField_eq
#print axioms MolecularDynamics.massHamiltonian_velocityOperator
#print axioms MolecularDynamics.mechanical_energy_hasDerivAt_zero
#print axioms MolecularDynamics.mechanical_energy_const_on_Ioo
#print axioms MolecularDynamics.exists_localMechanicalIVP_open_of_force_contDiffAt
#print axioms MolecularDynamics.mechanicalSolution_unique_on_Ioo
#print axioms MolecularDynamics.mechanicalSolution_eventually_unique_of_contDiffAt
#print axioms MolecularDynamics.totalMomentumCoordinate_const_on_Ioo
#print axioms MolecularDynamics.strictPotentialMin_mechanicalEquilibrium
#print axioms MolecularDynamics.momentum_norm_sq_le
#print axioms MolecularDynamics.momentum_norm_le_of_energy
#print axioms MolecularDynamics.isCompact_phaseEnergySublevel
#print axioms MolecularDynamics.mechanicalSolution_below_barrier_stays_in_ball
#print axioms MolecularDynamics.mechanicalSolution_phase_dist_lt

namespace MolecularDynamics

/-- One mass for each of the `n = N_c` configuration coordinates. -/
abbrev ScratchCoordinateMasses (n : ℕ) := Fin n → ℝ

/-- The diagonal mass matrix associated with coordinate masses. -/
def scratchDiagonalMassMatrix {n : ℕ} (masses : ScratchCoordinateMasses n) :
    MassMatrix n :=
  Matrix.diagonal masses

/-- Pointwise form of textbook equation (1.3), including both displayed equalities. -/
def ScratchNBodyEquationAt {n : ℕ} (masses : ScratchCoordinateMasses n)
    (force : Force n) (potential : PotentialEnergy n) (position acceleration : Position n) :
    Prop :=
  (scratchDiagonalMassMatrix masses).mulVec acceleration = force position ∧
    force position = -gradient potential position

/-- The coordinate form of the kinetic-energy sum in textbook equation (1.4). -/
noncomputable def scratchKineticEnergy {n : ℕ} (masses : ScratchCoordinateMasses n) :
    Velocity n → ℝ :=
  fun velocity => ∑ i, masses i * (velocity i) ^ 2 / 2

/-- Textbook equation (1.4): kinetic plus potential energy. -/
noncomputable def scratchTotalEnergy {n : ℕ} (masses : ScratchCoordinateMasses n)
    (potential : PotentialEnergy n) (position : Position n) (velocity : Velocity n) : ℝ :=
  scratchKineticEnergy masses velocity + potential position

end MolecularDynamics
#print axioms MolecularDynamics.exists_glued_function_of_compatible
#print axioms MolecularDynamics.exists_mechanicalSolutionOn_iUnion
#print axioms MolecularDynamics.exists_globalMechanicalSolution_of_local_compact_confinement
#print axioms MolecularDynamics.exists_globalMechanicalIVP_of_energy_barrier
#print axioms MolecularDynamics.gradient_contDiffAt_of_potential_contDiffAt_two
#print axioms MolecularDynamics.strictPotentialMin_exists_future_bound
#print axioms MolecularDynamics.strictPotentialMin_futureStable
#print axioms MolecularDynamics.strictPotentialMin_futureStable_of_potential_contDiffAt_two
#print axioms MolecularDynamics.product_dist_le_phaseEuclideanDistance
#print axioms MolecularDynamics.phaseEuclideanDistance_le_two_mul_dist
#print axioms MolecularDynamics.IsFutureMechanicalStable.euclidean
#print axioms MolecularDynamics.strictPotentialMin_futureStableEuclidean_of_potential_contDiffAt_two
#print axioms MolecularDynamics.strictPotentialMin_futureStableEuclidean_of_smooth
#check MolecularDynamics.strictPotentialMin_futureStableEuclidean_of_smooth
#print axioms MolecularDynamics.nBodyKineticEnergy_eq_inner
#print axioms MolecularDynamics.hasGradientAt_nBodyKineticEnergy
#print axioms MolecularDynamics.hasGradientAt_massLagrangian_velocity
#print axioms MolecularDynamics.hasGradientAt_massLagrangian_position
#print axioms MolecularDynamics.mechanicalSolution_eulerLagrange
#print axioms MolecularDynamics.eulerLagrange_to_mechanicalSolution
#print axioms MolecularDynamics.massLagrangian_coordinateChange
#print axioms MolecularDynamics.hasDerivAt_coordinateChange
#print axioms MolecularDynamics.generalizedMassMatrix_posDef
#print axioms MolecularDynamics.generalizedMassMatrix_isUnit
#print axioms MolecularDynamics.massHamiltonian_legendre_gap
#print axioms MolecularDynamics.legendre_objective_le_massHamiltonian
#print axioms MolecularDynamics.legendre_objective_attains_massHamiltonian
#print axioms MolecularDynamics.nBodyKineticEnergy_eq_zero_iff
#print axioms MolecularDynamics.legendre_objective_eq_massHamiltonian_iff
#print axioms MolecularDynamics.massHamiltonian_eq_legendre_sup
#print axioms MolecularDynamics.mechanicalSolution_translate_on_Ioi
#print axioms MolecularDynamics.futureMechanicalFlow_add
#print axioms MolecularDynamics.futureMechanicalFlow_commute
#print axioms MolecularDynamics.futureMechanicalFlow_energy
#print axioms MolecularDynamics.futureMechanicalFlow_injOn
#print axioms MolecularDynamics.exists_futureMechanicalFlow_of_energy_barrier
#print axioms MolecularDynamics.massHamiltonian_momentumReflection
#print axioms MolecularDynamics.mechanicalSolution_time_reverse_on_Iio
#print axioms MolecularDynamics.exists_globalMechanicalIVP_of_energy_barrier_two_sided
#print axioms MolecularDynamics.mechanicalSolution_translate_on_univ
#print axioms MolecularDynamics.mechanicalSolution_energy_on_univ
#print axioms MolecularDynamics.globalMechanicalFlow_add
#print axioms MolecularDynamics.globalMechanicalFlow_inverse
#print axioms MolecularDynamics.globalMechanicalFlow_commute
#print axioms MolecularDynamics.globalMechanicalFlow_bijOn
#print axioms MolecularDynamics.globalMechanicalFlow_energy
#print axioms MolecularDynamics.exists_globalMechanicalFlow_of_energy_barrier
#print axioms MolecularDynamics.harmonicFlow_isMechanicalSolution
#print axioms MolecularDynamics.harmonicFlow_isGlobalFlow
#print axioms MolecularDynamics.harmonicFlow_continuous
#print axioms MolecularDynamics.harmonicFlow_add
#print axioms MolecularDynamics.harmonicFlow_inverse
#print axioms MolecularDynamics.harmonicContinuousFlow
#print axioms MolecularDynamics.hasGradientAt_harmonicPotential
#print axioms MolecularDynamics.harmonicFlow_energy
#print axioms MolecularDynamics.freeParticleFlow_isMechanicalSolution
#print axioms MolecularDynamics.freeParticleFlow_isGlobalFlow
#print axioms MolecularDynamics.freeParticleFlow_continuous
#print axioms MolecularDynamics.freeParticleFlow_add
#print axioms MolecularDynamics.freeParticleContinuousFlow
#print axioms MolecularDynamics.freeParticleFlow_energy
#print axioms MolecularDynamics.hasDerivAt_linearExponentialFlow
#print axioms MolecularDynamics.linearExponentialFlow_add
#print axioms MolecularDynamics.linearExponentialFlow_continuous
#print axioms MolecularDynamics.linearContinuousFlow
#print axioms MolecularDynamics.linearExponentialFlow_inverse
#print axioms MolecularDynamics.hasDerivAt_linearExponentialFlow_initial_time
#print axioms MolecularDynamics.linearExponentialFlow_unique
#print axioms MolecularDynamics.linearExponentialOperator_series
#print axioms MolecularDynamics.matrixExponentialFlow_eq
#print axioms MolecularDynamics.hasDerivAt_matrixExponentialFlow
#print axioms MolecularDynamics.hasDerivAt_matrixExponentialFlow_initial_time
#print axioms MolecularDynamics.matrixExponentialFlow_unique
#print axioms MolecularDynamics.matrixContinuousFlow
#print axioms MolecularDynamics.matrixExponential_series
#print axioms MolecularDynamics.hasDerivAt_realEigenmode
#print axioms MolecularDynamics.linearExponentialFlow_realEigenmode
#print axioms MolecularDynamics.linearExponentialFlow_realSpectral_sum
#print axioms MolecularDynamics.linearExponentialFlow_realEigenbasis
#print axioms MolecularDynamics.hasDerivAt_complexEigenmode
#print axioms MolecularDynamics.complexExponentialFlow_eigenmode
#print axioms MolecularDynamics.complexExponentialFlow_spectral_sum
#print axioms MolecularDynamics.complexExponentialFlow_eigenbasis
#print axioms MolecularDynamics.hasDerivAt_complexExponentialFlow
#print axioms MolecularDynamics.complexContinuousFlow
#print axioms MolecularDynamics.complexEigenbasis_coefficients_unique
#print axioms MolecularDynamics.linearExponentialFlow_intertwine
#print axioms MolecularDynamics.linearExponentialFlow_fixed_clm
#print axioms MolecularDynamics.realMatrix_conjugation_commute
#print axioms MolecularDynamics.realMatrix_complexFlow_isReal
#print axioms MolecularDynamics.realMatrix_complexSpectral_sum_isReal
#print axioms MolecularDynamics.basisColumnMatrix_mulVec
#print axioms MolecularDynamics.basisColumnMatrix_mulVec_repr
#print axioms MolecularDynamics.basisColumnMatrix_isUnit
#print axioms MolecularDynamics.basisColumnMatrix_inverse_coefficients
#print axioms MolecularDynamics.firstIntegral_hasDerivAt_zero
#print axioms MolecularDynamics.firstIntegral_const_on_Ioo
#print axioms MolecularDynamics.firstIntegral_differential_necessary
#print axioms MolecularDynamics.isFirstIntegralOn_iff_differential
#print axioms MolecularDynamics.firstIntegral_gradient_criterion
#print axioms MolecularDynamics.planarAngularMomentum_hasDerivAt_zero
#print axioms MolecularDynamics.planarAngularMomentum_const_on_Ioo
#print axioms MolecularDynamics.centralForce_planarAngularMomentum_const
#print axioms MolecularDynamics.polarKinetic_identity
#print axioms MolecularDynamics.polarAngularMomentum_identity
#print axioms MolecularDynamics.keplerPolarLagrangian_identity
#print axioms MolecularDynamics.polarCoordinates_hasDerivAt_components
#print axioms MolecularDynamics.polarJacobian_det
#print axioms MolecularDynamics.polarJacobian_isUnit_iff
#print axioms MolecularDynamics.hasGradientAt_keplerPotential
#print axioms MolecularDynamics.keplerForce_eq_neg_gradient
#print axioms MolecularDynamics.keplerForce_contDiffAt
#print axioms MolecularDynamics.exists_kepler_localIVP
#print axioms MolecularDynamics.kepler_energy_const_on_Ioo
#print axioms MolecularDynamics.kepler_planarAngularMomentum_const_on_Ioo
#print axioms MolecularDynamics.hasStrictFDerivAt_polarCoordinateMap
#print axioms MolecularDynamics.exists_polarDerivativeEquiv
#print axioms MolecularDynamics.fderiv_polarCoordinateMap
#print axioms MolecularDynamics.exists_polarLocalChart_strictInverse
#print axioms MolecularDynamics.exists_polarLocalChart
#print axioms MolecularDynamics.keplerPolar_partial_v
#print axioms MolecularDynamics.keplerPolar_partial_ω
#print axioms MolecularDynamics.keplerPolar_partial_r
#print axioms MolecularDynamics.keplerPolar_partial_θ
#print axioms MolecularDynamics.keplerPolar_eulerLagrange_iff
#print axioms MolecularDynamics.keplerPolar_angular_const
#print axioms MolecularDynamics.keplerPolar_radial_reduction
#print axioms MolecularDynamics.keplerRadialEnergy_formula
#print axioms MolecularDynamics.keplerRadialEnergy_hasDerivAt_zero
#print axioms MolecularDynamics.keplerPolar_radialEnergy_const
#print axioms MolecularDynamics.keplerPolar_angle_integral
#print axioms MolecularDynamics.keplerPolar_radialEnergy_const_initialAngular
#print axioms MolecularDynamics.keplerPolar_energy_radial_identity
#print axioms MolecularDynamics.norm_polarCartesianPosition
#print axioms MolecularDynamics.polarCartesianState_angular
#print axioms MolecularDynamics.polarCartesianState_energy
#print axioms MolecularDynamics.hasDerivAt_planarPair
#print axioms MolecularDynamics.keplerPolar_angularVelocity_hasDerivAt
#print axioms MolecularDynamics.polarCartesianState_momentum_hasDerivAt
#print axioms MolecularDynamics.keplerPolarEL_to_cartesianMechanical
#print axioms MolecularDynamics.polarCartesianState_force
#print axioms MolecularDynamics.polarCartesianState_radialVelocity
#print axioms MolecularDynamics.cartesianMechanical_to_keplerPolarEL
#print axioms MolecularDynamics.keplerPolarEL_iff_cartesianMechanical
#print axioms MolecularDynamics.keplerReconstructedAngle_initial
#print axioms MolecularDynamics.keplerReconstructedAngle_hasDerivAt
#print axioms MolecularDynamics.keplerRadial_reconstruction_isEulerLagrange
#print axioms MolecularDynamics.keplerRadial_reconstruction_isMechanical
#print axioms MolecularDynamics.keplerRadialForce_contDiffAt
#print axioms MolecularDynamics.exists_keplerRadial_localIVP
#print axioms MolecularDynamics.exists_keplerRadial_reconstructed_localIVP
#print axioms MolecularDynamics.exists_polarCartesian_initialRepresentation
#print axioms MolecularDynamics.exists_kepler_localIVP_radialReconstruction
#print axioms MolecularDynamics.separableTimePrimitive_initial
#print axioms MolecularDynamics.separableTimePrimitive_hasStrictDerivAt
#print axioms MolecularDynamics.separableTimePrimitive_localInverse
#print axioms MolecularDynamics.separableTimePrimitive_along_solution
#print axioms MolecularDynamics.separableTimePrimitive_inverse_along_solution
#print axioms MolecularDynamics.keplerRadial_energy_speedSquare
#print axioms MolecularDynamics.keplerRadialBranchSpeed_eq_velocity
#print axioms MolecularDynamics.keplerRadialSpeedSquare_continuousAt
#print axioms MolecularDynamics.keplerRadialEnergy_const_on_Ioo
#print axioms MolecularDynamics.keplerRadial_signedQuadrature_inverse_on_branch
#print axioms MolecularDynamics.exists_keplerRadial_nonturning_window
#print axioms MolecularDynamics.keplerRadial_nonturning_signedQuadrature
#print axioms MolecularDynamics.keplerRadial_nonturning_quadrature
#print axioms MolecularDynamics.harmonicAction_time_formula
#print axioms MolecularDynamics.harmonicAction_harmonicFlow
#print axioms MolecularDynamics.harmonicActionAmplitude_pos
#print axioms MolecularDynamics.harmonicActionVelocity_formula
#print axioms MolecularDynamics.harmonicAction_energy
#print axioms MolecularDynamics.harmonicActionAmplitude_hasDerivAt
#print axioms MolecularDynamics.harmonicAction_hasDerivAt_components
#print axioms MolecularDynamics.harmonicAction_derivative_coefficients_iff
#print axioms MolecularDynamics.harmonicAction_ode_iff
#print axioms MolecularDynamics.harmonicAction_explicit_solution
#print axioms MolecularDynamics.exists_harmonicAction_representation
#print axioms MolecularDynamics.harmonicActionAmplitude_hasStrictDerivAt
#print axioms MolecularDynamics.harmonicActionJacobian_det
#print axioms MolecularDynamics.hasStrictFDerivAt_harmonicActionMap
#print axioms MolecularDynamics.fderiv_harmonicActionMap
#print axioms MolecularDynamics.exists_harmonicActionLocalChart
#print axioms MolecularDynamics.harmonicTorusPhase_rotation_coordinates
#print axioms MolecularDynamics.harmonicTorusPhase_rotation_isMechanical
#print axioms MolecularDynamics.harmonicTorusRotation_continuous
#print axioms MolecularDynamics.harmonicTorusRotation_add
#print axioms MolecularDynamics.harmonicTorusRotation_periodic_iff
#print axioms MolecularDynamics.harmonicTorusRotation_periodic_iff_integer
#print axioms MolecularDynamics.harmonicTorusRotation_integerFrequencies_periodic
#print axioms MolecularDynamics.harmonicTorusPhase_continuous
#print axioms MolecularDynamics.harmonicTorusPhase_realAngles
#print axioms MolecularDynamics.harmonicTorusPhase_energy
#print axioms MolecularDynamics.harmonicTorusPhase_image_fixedEnergy
#print axioms MolecularDynamics.harmonicTorusPhase_injective
#print axioms MolecularDynamics.harmonicTorusPhase_isClosedEmbedding
#print axioms MolecularDynamics.exists_harmonicTorusPhase_homeomorph
#print axioms MolecularDynamics.harmonicTorusThreeResonance_rotation
#print axioms MolecularDynamics.harmonicTorusRotation_three_resonant_not_dense
#print axioms MolecularDynamics.harmonicTorusRotation_two_dense_zero
#print axioms MolecularDynamics.harmonicTorusRotation_two_dense
#print axioms MolecularDynamics.harmonicTorusPhase_two_dense_fixedEnergy
#print axioms MolecularDynamics.harmonicTorusRotation_two_positivePeriod_iff_rational
#print axioms MolecularDynamics.harmonicTorusRotation_two_irrational_no_positivePeriod
#print axioms MolecularDynamics.harmonicTorusPhase_periodic_of_rotation_periodic
#print axioms MolecularDynamics.harmonicTorusPhase_periodic_iff_rotation_periodic
#print axioms MolecularDynamics.harmonicTorusPhase_two_positivePeriod_iff_rational
#print axioms MolecularDynamics.harmonicTorusPhase_two_irrational_no_positivePeriod
#print axioms MolecularDynamics.planarScalarPartial_isInvertible
#print axioms MolecularDynamics.exists_planarFirstIntegral_localGraph
#print axioms MolecularDynamics.planarFirstIntegral_localGraph_reduction
#print axioms MolecularDynamics.exists_planarFirstIntegral_C1Graph
#print axioms MolecularDynamics.exists_planarFirstIntegral_quadratureWindow
#print axioms MolecularDynamics.planarFirstIntegral_nonturning_quadrature
#print axioms MolecularDynamics.scalarPotentialEnergy_contDiff
#print axioms MolecularDynamics.scalarPotentialVectorField_contDiff
#print axioms MolecularDynamics.scalarPotentialEnergy_hasDerivAt_zero
#print axioms MolecularDynamics.scalarPotentialEnergy_isFirstIntegral
#print axioms MolecularDynamics.scalarPotentialEnergy_velocityPartial
#print axioms MolecularDynamics.scalarPotential_nonturning_quadrature
#print axioms MolecularDynamics.scalarPotentialSwappedEnergy_contDiff
#print axioms MolecularDynamics.scalarPotentialSwappedField_contDiff
#print axioms MolecularDynamics.scalarPotentialSwappedEnergy_isFirstIntegral
#print axioms MolecularDynamics.scalarPotentialSwappedEnergy_positionPartial
#print axioms MolecularDynamics.scalarPotential_regularTurning_quadrature
#print axioms MolecularDynamics.scalarPotential_equilibrium_constant
#print axioms MolecularDynamics.scalarPotential_equilibrium_locally_unique
#print axioms MolecularDynamics.scalarPotential_equilibrium_on_Ioo
#print axioms MolecularDynamics.scalarPotential_localDescription
#print axioms MolecularDynamics.scalarPotential_exists_localIVP
#print axioms MolecularDynamics.scalarPotential_exists_localIVP_integrable
#print axioms MolecularDynamics.equilibrium_constant_ode_iff
#print axioms MolecularDynamics.equilibriumLinearizationRemainder_isLittleO
#print axioms MolecularDynamics.equilibriumLinearizationRemainder_of_C1
#print axioms MolecularDynamics.actual_perturbation_ode
#print axioms MolecularDynamics.equilibrium_linearized_IVP
#print axioms MolecularDynamics.mechanicalLinearization_apply
#print axioms MolecularDynamics.hasFDerivAt_mechanicalVectorField
#print axioms MolecularDynamics.conservative_mechanical_linearization
#print axioms MolecularDynamics.exists_C1_localContinuousSolutionFamily
#print axioms MolecularDynamics.exists_localContinuousMechanicalFamily
#print axioms MolecularDynamics.exists_localContinuousMechanicalFamily_open
#print axioms MolecularDynamics.potential_hessian_symmetric
#print axioms MolecularDynamics.potential_hessian_symmetric_apply
#print axioms MolecularDynamics.conservative_linearization_hessian_data
#print axioms MolecularDynamics.linearizedHamiltonianQuadratic
#print axioms MolecularDynamics.linearizedHamiltonianQuadratic_eq_textbook_form
#print axioms MolecularDynamics.linearizedHamiltonianQuadratic_nonneg
#print axioms MolecularDynamics.linearizedHamiltonianQuadratic_nonneg_of_hessian

-- Theorem 2.1: full C¹ open-domain Euler convergence, not just a scalar recurrence.
#check MolecularDynamics.eulerStep
#check MolecularDynamics.eulerIterate
#check MolecularDynamics.eulerIterate_zero
#check MolecularDynamics.eulerIterate_succ
#check MolecularDynamics.eulerIterate_zero_step
#check MolecularDynamics.eulerMaxError
#check MolecularDynamics.eulerMaxError_le
#check MolecularDynamics.eulerStep_norm_sub_le
#check MolecularDynamics.euler_localDefect_of_derivative_bound
#check MolecularDynamics.exists_euler_trajectory_bounds
#check MolecularDynamics.euler_convergence_on_open
#check MolecularDynamics.theorem_2_1_euler

-- Section 2.2.3: actual one-step error recurrence, bound (2.12), and convergence.
#check MolecularDynamics.oneStepIterate
#check MolecularDynamics.oneStepIterate_zero
#check MolecularDynamics.oneStepIterate_succ
#check MolecularDynamics.oneStepMaxError
#check MolecularDynamics.oneStepMaxError_nonneg
#check MolecularDynamics.oneStepMaxError_le
#check MolecularDynamics.oneStep_error_recursion
#check MolecularDynamics.oneStep_error_bound
#check MolecularDynamics.oneStepMaxError_order_bound
#check MolecularDynamics.oneStep_converges_of_consistency_stability

-- Section 2.3.3: actual wedge form, sign convention and matrix pullback.
#check MolecularDynamics.SymplecticCoordinates
#check MolecularDynamics.SymplecticCoordinateMatrix
#check MolecularDynamics.textbookJ
#check MolecularDynamics.textbookJ_eq_neg_mathlibJ
#check MolecularDynamics.textbookJ_transpose
#check MolecularDynamics.textbookJ_squared
#check MolecularDynamics.textbookDq
#check MolecularDynamics.textbookDp
#check MolecularDynamics.textbookDq_apply
#check MolecularDynamics.textbookDp_apply
#check MolecularDynamics.textbookWedgeOneForms
#check MolecularDynamics.textbookWedgeOneForms_apply
#check MolecularDynamics.textbookSymplecticForm
#check MolecularDynamics.textbookSymplecticForm_coordinates
#check MolecularDynamics.textbookSymplecticForm_eq_sum_wedges
#check MolecularDynamics.textbookSymplecticForm_self
#check MolecularDynamics.textbookSymplecticForm_skew
#check MolecularDynamics.textbookSymplecticPullback
#check MolecularDynamics.textbookSymplecticPullback_apply
#check MolecularDynamics.textbookSymplecticPullback_matrix
#check MolecularDynamics.IsTextbookSymplectic
#check MolecularDynamics.isTextbookSymplectic_iff_pullback
#check MolecularDynamics.isTextbookSymplectic_iff_preserves_form
#check MolecularDynamics.isTextbookSymplectic_iff_mathlib
#check MolecularDynamics.isTextbookSymplectic_one
#check MolecularDynamics.IsTextbookSymplectic.mul
#check MolecularDynamics.IsTextbookSymplectic.det_eq_one
#check MolecularDynamics.IsTextbookSymplectic.det_square
#check MolecularDynamics.IsTextbookSymplectic.abs_det
#check MolecularDynamics.IsTextbookSymplectic.inv
#check MolecularDynamics.IsTextbookSymplectic.inv_formula

-- Sections 2.3.3--2.3.5: actual Jacobians and the genuine diffeomorphism group.
#check MolecularDynamics.textbookJacobian
#check MolecularDynamics.textbookJacobian_entry
#check MolecularDynamics.textbookJacobian_mulVec
#check MolecularDynamics.textbookJacobian_id
#check MolecularDynamics.textbookJacobian_comp
#check MolecularDynamics.IsTextbookSymplecticMap
#check MolecularDynamics.isTextbookSymplecticMap_iff_preserves_form
#check MolecularDynamics.isTextbookSymplecticMap_id
#check MolecularDynamics.IsTextbookSymplecticMap.comp
#check MolecularDynamics.IsTextbookSymplecticMap.jacobian_det_eq_one
#check MolecularDynamics.textbookJacobian_equiv_symm
#check MolecularDynamics.IsTextbookSymplecticEquiv
#check MolecularDynamics.isTextbookSymplecticEquiv_refl
#check MolecularDynamics.IsTextbookSymplecticEquiv.mul
#check MolecularDynamics.IsTextbookSymplecticEquiv.symm
#check MolecularDynamics.textbookSymplecticDiffeomorphismGroup
#check MolecularDynamics.textbookSymplecticDiffeomorphismGroup_mem_iff
#check MolecularDynamics.TextbookSymplecticDiffeomorphism
#check MolecularDynamics.textbookSymplecticDiffeomorphism_mul_apply
#synth Group (MolecularDynamics.TextbookSymplecticDiffeomorphism 2)

-- Section 2.3.4: actual time-dependent variational derivatives and Hessian symmetry.
#check MolecularDynamics.textbookHamiltonianHessian
#check MolecularDynamics.textbookHamiltonianHessian_isSymm
#check MolecularDynamics.hamiltonian_variational_matrix_cancellation
#check MolecularDynamics.hasDerivWithinAt_hamiltonian_variational_form
#check MolecularDynamics.hamiltonian_variational_form_constant
#check MolecularDynamics.hamiltonian_variational_isSymplectic
#check MolecularDynamics.hamiltonian_hessian_variational_isSymplectic
#check MolecularDynamics.hamiltonian_flow_isSymplectic_of_variational_equation

-- Section 2.3.6: actual C2 potential, symplectic Euler and its genuine inverse.
#check MolecularDynamics.textbookPositionProjection
#check MolecularDynamics.textbookPotentialForce
#check MolecularDynamics.contDiff_textbookPotentialForce
#check MolecularDynamics.textbookPotentialForce_matrix_isSymm
#check MolecularDynamics.textbookMomentumKick
#check MolecularDynamics.textbookPositionDrift
#check MolecularDynamics.textbookJacobian_momentumKick
#check MolecularDynamics.contDiff_textbookMomentumKick
#check MolecularDynamics.textbookJacobian_positionDrift
#check MolecularDynamics.textbookPositionDrift_isSymplectic
#check MolecularDynamics.textbookPotentialKick_isSymplectic
#check MolecularDynamics.textbookSymplecticEuler
#check MolecularDynamics.textbookSymplecticEuler_position
#check MolecularDynamics.textbookSymplecticEuler_momentum
#check MolecularDynamics.textbookSymplecticEuler_isSymplectic
#check MolecularDynamics.textbookPositionProjection_momentumKick
#check MolecularDynamics.textbookMomentumKick_neg_cancel
#check MolecularDynamics.textbookPositionDrift_neg_cancel
#check MolecularDynamics.textbookMomentumKickEquiv
#check MolecularDynamics.textbookPositionDriftEquiv
#check MolecularDynamics.textbookSymplecticEulerEquiv
#check MolecularDynamics.textbookSymplecticEulerEquiv_apply
#check MolecularDynamics.textbookSymplecticEulerEquiv_symm_apply
#check MolecularDynamics.textbookSymplecticEulerEquiv_isSymplectic

-- Section 2.3.7: actual inverse maps and adjoint methods.
#check MolecularDynamics.textbookAdjointMethod
#check MolecularDynamics.textbookAdjointMethod_apply_eq_iff
#check MolecularDynamics.textbookAdjointMethod_involutive
#check MolecularDynamics.textbookAdjointMethod_isSymplectic
#check MolecularDynamics.textbookFlowMethod
#check MolecularDynamics.textbookFlowMethod_isSelfAdjoint
#check MolecularDynamics.euler_negative_step_iff_backward
#check MolecularDynamics.euler_adjoint_iff_backward
#check MolecularDynamics.textbookAdjointSymplecticEuler
#check MolecularDynamics.textbookAdjointSymplecticEuler_apply
#check MolecularDynamics.textbookAdjointSymplecticEuler_position
#check MolecularDynamics.textbookAdjointSymplecticEuler_momentum
#check MolecularDynamics.textbookAdjointSymplecticEuler_isSymplectic

-- Section 2.4.1: actual local flows and Hamiltonian splitting error.
#check MolecularDynamics.exists_splitting_localError_bound
#check MolecularDynamics.exists_flow_splitting_localError_bound
#check MolecularDynamics.textbookHamiltonianVectorField
#check MolecularDynamics.contDiffOn_textbookHamiltonianVectorField
#check MolecularDynamics.textbookHamiltonianVectorField_add
#check MolecularDynamics.exists_hamiltonian_splitting_localError_bound

-- Main-text composition: printed85/PDF107.
#check MolecularDynamics.textbookComposeMaps
#check MolecularDynamics.textbookComposeMaps_isSymplectic
#check MolecularDynamics.textbookComposeMethods
#check MolecularDynamics.textbookComposeMethods_toMap
#check MolecularDynamics.textbookAdjointMethod_comp
#check MolecularDynamics.textbookSymmetricComposition
#check MolecularDynamics.textbookSymmetricComposition_isSelfAdjoint
#check MolecularDynamics.textbookComposeMethods_isSymplectic
#check MolecularDynamics.textbookSymmetricComposition_isSymplectic

-- Main-text conjugacy and processing: printed88/PDF110.
#check MolecularDynamics.textbookConjugateMap
#check MolecularDynamics.textbookConjugateMap_iterate
#check MolecularDynamics.textbook_conjugate_iterates
#check MolecularDynamics.textbook_conjugate_iterates_tendsto_iff
#check MolecularDynamics.textbookProcessedMethod
#check MolecularDynamics.textbookProcessedIterate
#check MolecularDynamics.textbookProcessedIterate_eq
#check MolecularDynamics.textbookProcessedIterate_eq_of_conjugacy
#check MolecularDynamics.textbookProcessedMaxError
#check MolecularDynamics.textbookProcessedMaxError_eq_of_conjugacy

-- Main-text Lie/Poisson and actual commutator: printed100--105/PDF122--127.
#check MolecularDynamics.textbookLieDerivative
#check MolecularDynamics.hasDerivWithinAt_textbookLieDerivative
#check MolecularDynamics.hasDerivAt_textbookLieDerivative
#check MolecularDynamics.contDiff_textbookLieDerivative
#check MolecularDynamics.hasDerivAt_textbookLieDerivative_second
#check MolecularDynamics.textbookLieDerivative_field_add
#check MolecularDynamics.textbookPoissonBracket
#check MolecularDynamics.textbookPoissonBracket_coordinates
#check MolecularDynamics.textbookPoissonBracket_skew
#check MolecularDynamics.textbookPoissonBracket_self
#check MolecularDynamics.textbookPoissonBracket_linear_right
#check MolecularDynamics.textbookPoissonBracket_jacobi
#check MolecularDynamics.textbookLieDerivative_hamiltonian_eq_poisson
#check MolecularDynamics.hasDerivWithinAt_textbookPoissonBracket
#check MolecularDynamics.textbookHamiltonian_energy_const_on_Icc
#check MolecularDynamics.textbookPoissonBracket_linear_left
#check MolecularDynamics.textbookHamiltonianLieDerivative_add
#check MolecularDynamics.textbookHamiltonianLieDerivative_commutator

-- Genuine noncommuting formal-series coefficients: printed103--105/PDF125--127.
#check MolecularDynamics.textbookFormalOperatorExponential
#check MolecularDynamics.textbookFormalOperatorExponential_coeff
#check MolecularDynamics.textbookFormalOperatorProduct_coeff_zero
#check MolecularDynamics.textbookFormalOperatorProduct_coeff_one
#check MolecularDynamics.textbookFormalOperatorProduct_coeff_two
#check MolecularDynamics.textbookFormalOperatorProduct_coeff_three
#check MolecularDynamics.textbookFormalOperatorDifference_coeff_two
#check MolecularDynamics.textbookFormalOperatorDifference_coeff_three
#check MolecularDynamics.textbookFormalZeroConstant_power_coeff_zero
#check MolecularDynamics.textbookFormalZeroConstantExponential
#check MolecularDynamics.textbookFormalZeroConstantExponential_coeff_stabilizes
#check MolecularDynamics.textbookFormalModifiedExponential
#check MolecularDynamics.textbookFormalModifiedExponential_coeff_zero
#check MolecularDynamics.textbookFormalModifiedExponential_coeff_one
#check MolecularDynamics.textbookFormalModifiedExponential_coeff_two
#check MolecularDynamics.textbookFormalModifiedExponential_matches_product

-- Uniform finite modified-Hamiltonian bounds: printed114--115/PDF136--137.
#check MolecularDynamics.textbookTruncatedHamiltonian
#check MolecularDynamics.contDiffOn_textbookTruncatedHamiltonian
#check MolecularDynamics.exists_compact_C1_lipschitz_constant
#check MolecularDynamics.exists_uniform_textbookTruncatedHamiltonian_remainder
#check MolecularDynamics.textbookTruncatedHamiltonian_difference_isBigO
#check MolecularDynamics.exists_uniform_textbookTruncatedHamiltonian_lipschitz

-- Genuine ODE conservation and finite energy drift: printed115--116/PDF137--138.
#check MolecularDynamics.oneStep_energy_telescoping
#check MolecularDynamics.textbook_energy_drift_le_actual_defects
#check MolecularDynamics.energy_step_count_power_factor
#check MolecularDynamics.textbook_energy_drift_rate_of_flow_defect

-- Complete Lemma4.1 and the following finite constraint projection: printed159--160/PDF181--182.
#check MolecularDynamics.textbookConstraintGradient
#check MolecularDynamics.contDiff_textbookConstraintGradient
#check MolecularDynamics.textbookConstrainedMomentum
#check MolecularDynamics.textbookCotangentChart
#check MolecularDynamics.lemma_4_1_coordinates
#check MolecularDynamics.lemma_4_1
#check MolecularDynamics.textbookMultiConstrainedMomentum
#check MolecularDynamics.differentiableAt_textbookMultiConstrainedMomentum
#check MolecularDynamics.textbookMultiConstrainedMomentum_preserves_pullback

-- Actual constrained Euler stage pullbacks: printed159--160/PDF181--182.
#check MolecularDynamics.textbookProjectedEulerPreMomentum
#check MolecularDynamics.textbookProjectedEulerPosition
#check MolecularDynamics.textbookProjectedEulerChart
#check MolecularDynamics.differentiableAt_textbookProjectedEulerPreMomentum
#check MolecularDynamics.differentiableAt_textbookProjectedEulerPosition
#check MolecularDynamics.textbookProjectedEulerChart_preserves_pullback

-- Explicit actual Gram solve and hidden constraint: printed159/PDF181.
#check MolecularDynamics.textbookConstraintJacobian
#check MolecularDynamics.textbookConstraintJacobian_mulVec
#check MolecularDynamics.textbookConstraintJacobian_eq_actualDerivative
#check MolecularDynamics.textbookInverseMassMatrix
#check MolecularDynamics.textbookConstraintGram
#check MolecularDynamics.textbookCotangentMultiplier
#check MolecularDynamics.textbookCotangentProjection
#check MolecularDynamics.textbookCotangentProjection_eq_gradient_sum
#check MolecularDynamics.textbookCotangentProjection_hiddenConstraint
#check MolecularDynamics.textbookCotangentProjection_constraint_derivative_zero

-- Actual reaction and solution-interval cotangent invariance: printed152--153/PDF174--175.
#check MolecularDynamics.textbookConstraintCurvature
#check MolecularDynamics.textbookConstrainedReactionMultiplier
#check MolecularDynamics.textbookConstrainedReaction_balance
#check MolecularDynamics.textbookConstrainedODE_cotangent_invariant

-- Actual Gram projection regularity and constructed final integrator stage.
#check MolecularDynamics.contDiffAt_textbookConstraintJacobian
#check MolecularDynamics.contDiffAt_textbookConstraintGram
#check MolecularDynamics.contDiffAt_textbookCotangentMultiplier
#check MolecularDynamics.contDiffAt_textbookCotangentProjection
#check MolecularDynamics.textbookCotangentProjection_preserves_pullback
#check MolecularDynamics.contDiffAt_textbookProjectedEulerPreMomentum
#check MolecularDynamics.contDiffAt_textbookProjectedEulerPosition
#check MolecularDynamics.textbookGramProjectedEulerChart
#check MolecularDynamics.textbookGramProjectedEulerChart_hiddenConstraint_and_pullback

-- Physical positive masses and independent actual constraint gradients.
#check MolecularDynamics.textbookConstraintJacobian_vecMul_injective
#check MolecularDynamics.textbookInverseMassMatrix_posDef
#check MolecularDynamics.textbookConstraintGram_posDef
#check MolecularDynamics.textbookConstraintGram_det_pos
#check MolecularDynamics.textbookConstraintGram_det_ne_zero
#check MolecularDynamics.textbookCotangentProjection_hiddenConstraint_of_mass_and_independence
#check MolecularDynamics.contDiffAt_textbookCotangentMultiplier_of_mass_and_independence
#check MolecularDynamics.textbookConstrainedODE_cotangent_invariant_of_mass_and_independence

-- Genuine joint C2 solution variations, Hamiltonian Jacobian ODE and symplecticity.
#check MolecularDynamics.textbookSolutionVariation
#check MolecularDynamics.textbookSolutionVariation_hasDerivAt
#check MolecularDynamics.textbookHamiltonianVectorField_fderiv_mulVec
#check MolecularDynamics.textbookHamiltonianFlowJacobian_hasDerivAt
#check MolecularDynamics.textbookHamiltonianFlow_isSymplectic_of_jointC2
#check MolecularDynamics.textbookHamiltonianFlowJacobian_det_eq_one_of_jointC2

-- Genuine Hamiltonian divergence, ODE injectivity and Lebesgue image volume.
#check MolecularDynamics.textbookHamiltonianVectorField_jacobian
#check MolecularDynamics.textbookHamiltonianVectorField_divergence_zero
#check MolecularDynamics.textbookC1SolutionFamily_injective
#check MolecularDynamics.textbookHamiltonianFlow_injective_of_jointC2
#check MolecularDynamics.textbookHamiltonianFlow_measurable_image_of_jointC2
#check MolecularDynamics.textbookHamiltonianFlow_volume_image_of_jointC2

-- Real matrix determinant ODE and actual divergence-free Liouville volume.
#check MolecularDynamics.textbookCoordinateJacobian
#check MolecularDynamics.textbookCoordinateJacobian_entry
#check MolecularDynamics.textbookCoordinateJacobian_mulVec
#check MolecularDynamics.textbookMatrixDet_hasDerivAt_of_linearODE
#check MolecularDynamics.textbookSolutionFamilyJacobian_hasDerivAt
#check MolecularDynamics.textbookDivergenceFreeFlowJacobian_det_eq_one_of_jointC2
#check MolecularDynamics.textbookDivergenceFreeFlow_measurable_image_of_jointC2
#check MolecularDynamics.textbookDivergenceFreeFlow_volume_image_of_jointC2

-- Constructed real C1 Gram reaction for the constrained-flow proof.
#check MolecularDynamics.contDiffAt_textbookConstraintGram_inverse
#check MolecularDynamics.contDiffAt_textbookConstraintCurvature
#check MolecularDynamics.contDiffAt_textbookConstrainedReactionMultiplier
#check MolecularDynamics.contDiffAt_textbookConstrainedReactionMultiplier_of_mass_and_independence
#check MolecularDynamics.textbookConstrainedPhaseVectorField
#check MolecularDynamics.contDiffAt_textbookConstrainedPhaseVectorField
#check MolecularDynamics.contDiffAt_textbookConstrainedPhaseVectorField_of_mass_and_independence

-- Actual initial constraints and true constrained ODE give restricted flow symplecticity.
#check MolecularDynamics.textbookConstrainedAcceleration_pullback_zero
#check MolecularDynamics.textbookConstrainedFlow_pullback_constant_of_jointC2
#check MolecularDynamics.textbookConstrainedFlow_pullback_constant_of_mass_and_independence

-- Actual Brownian quadratic variation, textbook Proposition 6.2.
#check MolecularDynamics.textbookCenteredGaussian_secondMoment
#check MolecularDynamics.textbookCenteredGaussian_fourthMoment
#check MolecularDynamics.textbookCenteredGaussian_square_memLp
#check MolecularDynamics.textbookCenteredGaussian_square_variance
#check MolecularDynamics.textbookWienerTime
#check MolecularDynamics.textbookWienerIncrement
#check MolecularDynamics.textbookWienerQuadraticSum
#check MolecularDynamics.textbookWienerIncrement_hasLaw
#check MolecularDynamics.textbookWienerIncrement_independent
#check MolecularDynamics.textbookWienerQuadraticSum_integral
#check MolecularDynamics.textbookWienerQuadraticSum_variance
#check MolecularDynamics.textbookWienerQuadraticSum_meanSquareError
#check MolecularDynamics.textbookWienerQuadraticSum_meanSquare_tendsto

-- Genuine finite Wiener integrals and the self integral limit.
#check MolecularDynamics.textbookWienerWeightedSum
#check MolecularDynamics.textbookWienerWeightedVariance
#check MolecularDynamics.textbookWienerWeightedSum_hasGaussianLaw
#check MolecularDynamics.textbookWienerWeightedSum_integral
#check MolecularDynamics.textbookWienerWeightedSum_variance
#check MolecularDynamics.textbookWienerWeightedSum_hasLaw
#check MolecularDynamics.textbookWienerWeightedSum_difference_secondMoment
#check MolecularDynamics.textbookWienerSelfItoSum
#check MolecularDynamics.textbookWienerSelfItoSum_identity
#check MolecularDynamics.textbookWienerSelfItoLimit_memLp
#check MolecularDynamics.textbookWienerSelfItoSum_memLp
#check MolecularDynamics.textbookWienerSelfItoSum_meanSquareError
#check MolecularDynamics.textbookWienerSelfItoSum_meanSquare_tendsto
#check MolecularDynamics.textbookWienerSelfItoIntegral_exists

-- Real Markov composition and unique invariant distribution swap.
#check MolecularDynamics.textbookUniqueInvariantProbability
#check MolecularDynamics.textbookKernelInvariant_swap
#check MolecularDynamics.textbookKernelComposition_iterate
#check MolecularDynamics.textbookInvariantDistributionSwap_left
#check MolecularDynamics.textbookInvariantDistributionSwap

-- Actual linear thermostat fields and derivative bracket closure.
#check MolecularDynamics.textbookThermostatPhase
#check MolecularDynamics.textbookThermostatF
#check MolecularDynamics.textbookThermostatG
#check MolecularDynamics.textbookThermostatC
#check MolecularDynamics.textbookThermostatD
#check MolecularDynamics.textbookThermostatF_apply
#check MolecularDynamics.textbookThermostatG_apply
#check MolecularDynamics.textbookThermostatC_apply
#check MolecularDynamics.textbookThermostatD_apply
#check MolecularDynamics.textbookThermostatLinearField_lieBracket
#check MolecularDynamics.textbookThermostat_lie_F_G
#check MolecularDynamics.textbookThermostat_lie_F_C
#check MolecularDynamics.textbookThermostat_lie_D_F
#check MolecularDynamics.textbookThermostatLieSpan
#check MolecularDynamics.textbookThermostatLieSpan_vectorField_closed
#check MolecularDynamics.textbookThermostat_C_D_mem_lieSpan

-- Genuine spectral modes, actual vector independence and pointwise spanning.
#check MolecularDynamics.textbookThermostatEigenCoordinates
#check MolecularDynamics.textbookThermostatSpectralPhase
#check MolecularDynamics.textbookThermostatEigenCoordinates_eq_dotProduct
#check MolecularDynamics.textbookThermostatEigenCoordinates_intertwine
#check MolecularDynamics.textbookThermostatEigenCoordinates_power
#check MolecularDynamics.textbookThermostat_C_coordinates
#check MolecularDynamics.textbookThermostat_D_coordinates
#check MolecularDynamics.textbookThermostatModeDomain
#check MolecularDynamics.textbookThermostatModeDomain_isOpen
#check MolecularDynamics.textbookThermostatModal_coefficients_eq_zero
#check MolecularDynamics.textbookThermostatFamily
#check MolecularDynamics.textbookThermostatFamily_linearIndependent
#check MolecularDynamics.textbookThermostatFamily_span_eq_top
#check MolecularDynamics.textbookThermostatLieSpan_pointwise_span_eq_top

-- Actual iterated brackets, smooth coefficient closure, thermostat lift and NHL fields.
#check MolecularDynamics.textbookIteratedBracket
#check MolecularDynamics.textbookIteratedBracket_contDiff
#check MolecularDynamics.textbookBracketPointSpan
#check MolecularDynamics.textbookHormanderAt
#check MolecularDynamics.textbookSmoothBracketModule
#check MolecularDynamics.textbookSmoothBracketModule_generator_mem
#check MolecularDynamics.textbookSmoothBracketModule_contDiff
#check MolecularDynamics.textbookSmoothBracketModule_smooth_smul_mem
#check MolecularDynamics.textbookSmoothBracketModule_eval_mem
#check MolecularDynamics.textbookSmoothBracketModule_bracket_mem
#check MolecularDynamics.textbookThermostatLift
#check MolecularDynamics.textbookThermostatDrift
#check MolecularDynamics.textbookThermostatNoise
#check MolecularDynamics.textbookThermostatSeed
#check MolecularDynamics.textbookThermostatSeed_contDiff
#check MolecularDynamics.textbookThermostatLift_lieBracket
#check MolecularDynamics.textbookThermostatDrift_noise_bracket
#check MolecularDynamics.textbookThermostatLift_mem_module
#check MolecularDynamics.textbookThermostatLift_iterated_mem_module
#check MolecularDynamics.textbookThermostatHormanderLift
#check MolecularDynamics.textbookThermostatPhysical_hormander
#check MolecularDynamics.textbookNHLFeedback
#check MolecularDynamics.textbookNHLFeedback_contDiff
#check MolecularDynamics.textbookNHLDrift
#check MolecularDynamics.textbookNHL_domain_isOpen
#check MolecularDynamics.textbookNHLSeed_contDiff
#check MolecularDynamics.textbookNHLDrift_apply
#check MolecularDynamics.textbookNHL_hormander
#check MolecularDynamics.textbookNHL_hormander_physicalNoise
#check MolecularDynamics.textbookIteratedBracket.seed
#check MolecularDynamics.textbookIteratedBracket.bracket
#check MolecularDynamics.textbookIteratedBracket.rec

-- Actual zero eigenmode domain and pathwise invariance.
#check MolecularDynamics.textbookNHLZeroMode
#check MolecularDynamics.textbookThermostatModeDomain_eq_compl_zeroModes
#check MolecularDynamics.textbookNHL_zeroMode_invariant

#check MolecularDynamics.textbookWienerMidpointSum
#check MolecularDynamics.textbookWienerMidpointCorrection
#check MolecularDynamics.textbookWienerMidpointCorrection_memLp
#check MolecularDynamics.textbookWienerMidpointCorrection_integral
#check MolecularDynamics.textbookWienerMidpointCorrection_variance
#check MolecularDynamics.textbookWienerMidpointSum_identity
#check MolecularDynamics.textbookWienerMidpointLimit_memLp
#check MolecularDynamics.textbookWienerMidpointSum_memLp
#check MolecularDynamics.textbookWienerMidpointSum_meanSquareError
#check MolecularDynamics.textbookWienerMidpointSum_meanSquare_tendsto
#check MolecularDynamics.textbookWienerSelfStratonovichIntegral_exists

#check MolecularDynamics.textbookWienerWeightedSum_refine
#check MolecularDynamics.textbookWienerWeightedSum_twoGrid_secondMoment
#check MolecularDynamics.textbookWienerDeterministicSum
#check MolecularDynamics.textbookWienerDeterministicSum_memLp
#check MolecularDynamics.textbookWienerTime_mem_Icc
#check MolecularDynamics.textbookWienerDeterministicSum_twoGrid_meanSquare_le
#check MolecularDynamics.textbookWienerDeterministicLp
#check MolecularDynamics.textbookWienerDeterministicLp_dist_le
#check MolecularDynamics.textbookWienerDeterministicLp_cauchySeq
#check MolecularDynamics.textbookWienerDeterministicIntegral_exists_of_lipschitz
#check MolecularDynamics.textbookWienerDeterministicIntegral_exists

#check MolecularDynamics.textbookWienerDeterministicVariance
#check MolecularDynamics.textbookWienerDeterministicVariance_coe
#check MolecularDynamics.textbookWienerDeterministicFiniteVariance_tendsto
#check MolecularDynamics.textbookWienerDeterministicIntegral_hasLaw
#check MolecularDynamics.textbookWienerDeterministicIto_proposition63

#check MolecularDynamics.textbookDivergence
#check MolecularDynamics.textbookLiouvilleStationary
#check MolecularDynamics.textbookDivergence_density
#check MolecularDynamics.textbookDivergence_add
#check MolecularDynamics.textbookDivergence_sub
#check MolecularDynamics.textbookDivergence_const_smul
#check MolecularDynamics.textbookDivergence_prod
#check MolecularDynamics.textbookDivergence_conjugate
#check MolecularDynamics.textbookLiouvilleStationary_lift_idle
#check MolecularDynamics.textbookLiouvilleStationary_conjugate
#check MolecularDynamics.textbookLiouvilleStationary_add_sub
#check MolecularDynamics.textbookLiouvilleStationary_const_mul
#check MolecularDynamics.textbookHamiltonianGibbsWeight
#check MolecularDynamics.textbookHamiltonianGibbsWeight_pos
#check MolecularDynamics.textbookHamiltonianGibbsWeight_stationary
#check MolecularDynamics.textbookHamiltonianGibbsDensity
#check MolecularDynamics.textbookHamiltonianGibbsDensity_stationary
#check MolecularDynamics.textbookHamiltonianGibbsDensity_pos
#check MolecularDynamics.textbookSingleThermostatField
#check MolecularDynamics.textbookCombinedThermostatField
#check MolecularDynamics.textbookThermostatProductDensity
#check MolecularDynamics.textbookThermostatProductDensity_stationary
#check MolecularDynamics.textbookThermostatProductDensity_nonneg
#check MolecularDynamics.textbookThermostats_additive_proposition81

#check MolecularDynamics.textbookStationaryDensityFlow_weightedJacobian
#check MolecularDynamics.textbookStationaryDensityFlow_abs_weightedJacobian
#check MolecularDynamics.textbookDensityMeasure
#check MolecularDynamics.textbookStationaryDensityFlow_measure_image
#check MolecularDynamics.textbookStationaryDensityFlow_measure_map
#check MolecularDynamics.textbookThermostatProductDensity_measure_eq_prod
#check MolecularDynamics.textbookThermostatProductDensity_probability
#check MolecularDynamics.textbookThermostats_additive_invariant_probability

#check MolecularDynamics.textbookFormalOperatorLogarithm
#check MolecularDynamics.textbookFormalOperatorLogarithm_coeff_stabilizes
#check MolecularDynamics.textbookFormalOperatorLogarithm_coeff_one
#check MolecularDynamics.textbookFormalOperatorLogarithm_coeff_two
#check MolecularDynamics.textbookFormalOperatorLogarithm_coeff_three
#check MolecularDynamics.textbookFormalOperatorLogarithm_coeff_four
#check MolecularDynamics.textbookSymmetricOperatorComposition
#check MolecularDynamics.textbookOperatorCommutator
#check MolecularDynamics.textbookSymmetricOperatorCorrection
#check MolecularDynamics.textbookSymmetricOperatorComposition_coeff_zero
#check MolecularDynamics.textbookSymmetricOperatorComposition_coeff_one
#check MolecularDynamics.textbookSymmetricOperatorComposition_coeff_two
#check MolecularDynamics.textbookSymmetricOperatorComposition_coeff_three
#check MolecularDynamics.textbookSymmetricOperatorComposition_coeff_four
#check MolecularDynamics.textbookSymmetricModifiedGenerator
#check MolecularDynamics.textbookSymmetricModifiedGenerator_coeff_zero
#check MolecularDynamics.textbookSymmetricModifiedGenerator_coeff_one
#check MolecularDynamics.textbookSymmetricModifiedGenerator_coeff_two
#check MolecularDynamics.textbookSymmetricModifiedGenerator_coeff_three
#check MolecularDynamics.textbookSymmetricModifiedGenerator_formal_proposition71
#check MolecularDynamics.textbookFormalLogarithmExponential
#check MolecularDynamics.textbookFormalLogarithmExponential_coeff_matches
#check MolecularDynamics.textbookSymmetricModifiedGenerator_logarithm
#check MolecularDynamics.textbookSymmetricGeneratorExponential
#check MolecularDynamics.textbookSymmetricGeneratorExponential_coeff_matches

#check MolecularDynamics.textbookFormalOperatorCalculus
#check MolecularDynamics.textbookFormalOperatorCalculusHom
#check MolecularDynamics.textbookFormalOperatorCalculus_subst
#check MolecularDynamics.textbookFormalOperatorCalculus_exp
#check MolecularDynamics.textbookFormalOperatorCalculus_log
#check MolecularDynamics.textbookFormalLogarithmExponential_eq
#check MolecularDynamics.textbookFormalOperatorLogarithm_exp
#check MolecularDynamics.textbookSymmetricGeneratorExponential_eq
#check MolecularDynamics.textbookFormalOperatorTimeNeg
#check MolecularDynamics.textbookFormalZeroConstantExponential_mul_neg
#check MolecularDynamics.textbookFormalOperatorExponential_mul_neg
#check MolecularDynamics.textbookSymmetricOperatorComposition_inverse
#check MolecularDynamics.textbookSymmetricOperatorLogarithm_timeNeg
#check MolecularDynamics.textbookSymmetricModifiedGenerator_odd_coeff_zero

#check MolecularDynamics.textbookLangevinPhase
#check MolecularDynamics.textbookLangevinDrift
#check MolecularDynamics.textbookLangevinNoise
#check MolecularDynamics.textbookLangevinSeed
#check MolecularDynamics.textbookLangevinForce_contDiff
#check MolecularDynamics.textbookLangevinSeed_contDiff
#check MolecularDynamics.textbookLangevinDrift_noise_bracket
#check MolecularDynamics.textbookLangevinBracketFamily
#check MolecularDynamics.textbookLangevinBracketFamily_linearIndependent
#check MolecularDynamics.textbookLangevin_hormander
#check MolecularDynamics.textbookLangevin_hormander_physicalNoise

#check MolecularDynamics.textbookLangevinControlPosition
#check MolecularDynamics.textbookLangevinControlMomentum
#check MolecularDynamics.textbookLangevinControlRate
#check MolecularDynamics.textbookLangevinControlPath
#check MolecularDynamics.textbookLangevinControlPosition_hasDerivAt
#check MolecularDynamics.textbookLangevinControl_endpoints
#check MolecularDynamics.textbookLangevinControlPath_hasDerivAt
#check MolecularDynamics.textbookLangevinControlPath_contDiff
#check MolecularDynamics.textbookLangevinControlMomentum_hasDerivAt
#check MolecularDynamics.textbookLangevinControlledEndpoint

#check MolecularDynamics.textbookLangevinIntegralSolution
#check MolecularDynamics.textbookLangevinNoiseCompensated
#check MolecularDynamics.textbookLangevinDrivenField
#check MolecularDynamics.textbookLangevinNoiseCompensated_continuousOn
#check MolecularDynamics.textbookLangevinNoiseCompensated_hasDerivWithinAt
#check MolecularDynamics.textbookLangevinNoiseCompensated_initial
#check MolecularDynamics.textbookLangevinControl_integralSolution
#check MolecularDynamics.textbookLangevinNoiseCompensated_dist_le
#check MolecularDynamics.textbookLangevinNoise_phase_dist_le
#check MolecularDynamics.textbookLangevinControlledEndpoint_stable_globalLip

#check MolecularDynamics.textbookLangevinSmoothCutoff
#check MolecularDynamics.textbookLangevinSmoothCutoff_contDiff
#check MolecularDynamics.textbookLangevinSmoothCutoff_hasCompactSupport
#check MolecularDynamics.textbookLangevinSmoothCutoff_eq
#check MolecularDynamics.textbookLangevinSmoothCutoff_force_eq
#check MolecularDynamics.textbookPotentialForce_hasCompactSupport
#check MolecularDynamics.textbookLangevinSmoothCutoff_force_lipschitz
#check MolecularDynamics.textbookContinuous_firstExit
#check MolecularDynamics.textbookLangevinIntegralSolution_changePotential
#check MolecularDynamics.textbookLangevinControlledEndpoint_stable

#check MolecularDynamics.textbookBrownianBridge
#check MolecularDynamics.textbookBrownianBridge_terminal
#check MolecularDynamics.textbookBrownianBridge_jointGaussian
#check MolecularDynamics.textbookBrownianBridge_covariance_terminal
#check MolecularDynamics.textbookBrownianBridge_indep_terminal
#check MolecularDynamics.textbookBrownianBridge_continuous
#check MolecularDynamics.textbookBrownian_endpoint_ball_pos
#check MolecularDynamics.textbookBrownianBridgeSampleTube
#check MolecularDynamics.textbookBrownianBridgeSampleTube_nullMeasurable
#check MolecularDynamics.textbookBrownianBridgeSampleTube_short_pos
#check MolecularDynamics.textbookBrownianBridgeSampleTube_exists_pos
#check MolecularDynamics.textbookBrownianBridgeSampleTube_ae_full
#check MolecularDynamics.textbookBrownianBridgeSampleTube_inter_ball
#check MolecularDynamics.textbookBrownianBridgeSampleTube_short_joint_pos
#check MolecularDynamics.textbookWienerLinearTube
#check MolecularDynamics.textbookWienerLinearTube_nullMeasurable
#check MolecularDynamics.textbookWienerLinearTube_short_pos

#check MolecularDynamics.textbookWienerSamples_finiteLaw
#check MolecularDynamics.textbookWienerSamples_law_eq
#check MolecularDynamics.textbookWienerLinearTube_ae_samples
#check MolecularDynamics.textbookWienerLinearTube_measure_eq
#check MolecularDynamics.textbookWienerLinearTube_shift_short_pos
#check MolecularDynamics.textbookWienerSegment
#check MolecularDynamics.textbookWienerSegments_jointGaussian
#check MolecularDynamics.textbookWienerSegments_independent
#check MolecularDynamics.textbookBrownianBridgeJointTube_measure_eq
#check MolecularDynamics.textbookBrownianBridgeJointTube_shift_short_pos
#check MolecularDynamics.textbookWienerSegmentJointEvent
#check MolecularDynamics.textbookWienerSegmentJointEvent_nullMeasurable
#check MolecularDynamics.textbookWienerSegmentJointEvent_measure_prod
#check MolecularDynamics.textbookWienerSegmentJointEvent_short_pos

#check MolecularDynamics.textbookWienerUniformGrid_cell
#check MolecularDynamics.textbookWienerEndpointError_telescope
#check MolecularDynamics.textbookWienerUniformGrid_exists
#check MolecularDynamics.textbookWienerEndpointError_bound
#check MolecularDynamics.textbookWienerGridTube_bound
#check MolecularDynamics.textbookWienerControlTube
#check MolecularDynamics.textbookWienerControlTube_ae_samples
#check MolecularDynamics.textbookWienerControlTube_nullMeasurable
#check MolecularDynamics.textbookWienerControlTube_pos
#check MolecularDynamics.textbookIsWienerVector
#check MolecularDynamics.textbookWienerVector_coordinate
#check MolecularDynamics.textbookWienerVector_coordinates_independent
#check MolecularDynamics.textbookWienerVector_zero_ae
#check MolecularDynamics.textbookWienerVectorControlTube
#check MolecularDynamics.textbookWienerVectorControlTube_eq_iInter
#check MolecularDynamics.textbookWienerVectorControlTube_nullMeasurable
#check MolecularDynamics.textbookWienerVectorControlTube_measure_prod
#check MolecularDynamics.textbookWienerVectorControlTube_pos
#check MolecularDynamics.textbookWienerVectorRealControlTube
#check MolecularDynamics.textbookWienerVectorRealControlTube_eq
#check MolecularDynamics.textbookWienerVectorRealControlTube_nullMeasurable
#check MolecularDynamics.textbookWienerVectorRealControlTube_pos
#check MolecularDynamics.textbookLangevinEndpoint_ball_pos
#check MolecularDynamics.textbookLangevinEndpoint_open_pos
#check MolecularDynamics.textbookLangevinEndpoint_physicalNoise_open_pos

#check MolecularDynamics.textbookLangevinPeriodicPhase
#check MolecularDynamics.textbookLangevinPeriodicProjection
#check MolecularDynamics.textbookLangevinPeriodicProjection_continuous
#check MolecularDynamics.textbookLangevinPeriodicProjection_surjective
#check MolecularDynamics.textbookLangevinPeriodicProjection_open_preimage
#check MolecularDynamics.textbookLangevinProjectedEndpoint_open_pos
#check MolecularDynamics.textbookLangevinProjectedEndpoint_physicalNoise_open_pos
#check MolecularDynamics.textbookUnitPeriodicPotential
#check MolecularDynamics.textbookUnitPeriodicPotential_fderiv
#check MolecularDynamics.textbookUnitPeriodicPotential_force
#check MolecularDynamics.textbookUnitPeriodicPotential_force_fderiv
#check MolecularDynamics.textbookUnitPeriodicPotential_force_bound
#check MolecularDynamics.textbookUnitPeriodicPotential_force_derivative_bound
#check MolecularDynamics.textbookUnitPeriodicPotential_force_lipschitz
#check MolecularDynamics.textbookLangevinPeriodicRepresentative
#check MolecularDynamics.textbookLangevinPeriodicRepresentative_projects
#check MolecularDynamics.textbookLangevinPeriodicForce
#check MolecularDynamics.textbookLangevinPeriodicForce_lift
#check MolecularDynamics.textbookLangevinPeriodicIntegralSolution
#check MolecularDynamics.textbookLangevinPeriodicPositionLift
#check MolecularDynamics.textbookLangevinPeriodicPositionLift_projects
#check MolecularDynamics.textbookLangevinPeriodicIntegralSolution_lift
#check MolecularDynamics.textbookLangevinPeriodicEndpoint_open_pos
#check MolecularDynamics.textbookLangevinPeriodicEndpoint_physicalNoise_open_pos

#check MolecularDynamics.textbookLangevinDrivenField_lipschitz
#check MolecularDynamics.textbookLangevinDrivenField_exists
#check MolecularDynamics.textbookLangevinIntegralSolution_exists_globalLip
#check MolecularDynamics.textbookLangevinPeriodicIntegralSolution_exists

#check MolecularDynamics.textbookLangevinPathNoise
#check MolecularDynamics.textbookLangevinPathNoise_continuous
#check MolecularDynamics.textbookLangevinPathNoise_zero
#check MolecularDynamics.textbookLangevinPathSolution
#check MolecularDynamics.textbookLangevinPathSolution_integralSolution
#check MolecularDynamics.textbookLangevinPathEndpoint
#check MolecularDynamics.textbookLangevinPathEndpoint_lipschitz
#check MolecularDynamics.textbookLangevinPathEndpoint_continuous
#check MolecularDynamics.textbookLangevinIntegralSolution_unique_globalLip
#check MolecularDynamics.textbookWienerVectorContinuousPath
#check MolecularDynamics.textbookWienerVectorContinuousPath_eval
#check MolecularDynamics.textbookWienerVectorContinuousPath_aemeasurable
#check MolecularDynamics.textbookWienerVectorContinuousPath_noise_ae
#check MolecularDynamics.textbookLangevinRandomSolution
#check MolecularDynamics.textbookLangevinRandomSolution_integralSolution_ae
#check MolecularDynamics.textbookLangevinRandomSolution_endpoint_aemeasurable
#check MolecularDynamics.textbookLangevinRandomSolution_open_pos
#check MolecularDynamics.textbookLangevinPeriodicRandomSolution_exists
#check MolecularDynamics.textbookLangevinPeriodicRandomSolution_exists_open_pos
#check MolecularDynamics.textbookLangevinPeriodicRandomSolution_physicalNoise_exists_open_pos

#check MolecularDynamics.textbookLangevinIntegralSolution_periodicProjection
#check MolecularDynamics.textbookLangevinIntegralSolution_restrict
#check MolecularDynamics.textbookLangevinGlobalRandomPhase
#check MolecularDynamics.textbookLangevinGlobalRandomPhase_integralSolution_ae
#check MolecularDynamics.textbookLangevinGlobalRandomPhase_endpoint_aemeasurable
#check MolecularDynamics.textbookLangevinGlobalRandomPhase_continuousOn_ae
#check MolecularDynamics.textbookLangevinPeriodicGlobalRandomSolution_exists_open_pos
#check MolecularDynamics.textbookLangevinPeriodicGlobalRandomSolution_physicalNoise_exists_open_pos

#check MolecularDynamics.textbookUnitPeriodicPotential_bound
#check MolecularDynamics.textbookLangevinHamiltonian
#check MolecularDynamics.textbookLangevinHamiltonianPower
#check MolecularDynamics.textbookLangevinDifferentialOperator
#check MolecularDynamics.textbookLangevinLyapunov_printed_laplacian_bound_counterexample
#check MolecularDynamics.textbookLangevinHamiltonian_momentum_shift
#check MolecularDynamics.textbookLangevinHamiltonian_lower
#check MolecularDynamics.textbookLangevinHamiltonianPower_pos
#check MolecularDynamics.textbookLangevinHamiltonianPower_momentum_second
#check MolecularDynamics.textbookLangevinHamiltonianPower_momentum_laplacian
#check MolecularDynamics.textbookLangevinHamiltonianPower_momentum_laplacian_bound
#check MolecularDynamics.textbookLangevinHamiltonian_drift_hasDerivAt
#check MolecularDynamics.textbookLangevinHamiltonianPower_drift_hasDerivAt
#check MolecularDynamics.textbookLangevinHamiltonianPower_differentialOperator
#check MolecularDynamics.textbookLangevinHamiltonianPower_periodic_lyapunov
#check MolecularDynamics.textbookLangevinHamiltonianPower_contDiff
#check MolecularDynamics.textbookLangevinHamiltonianPower_momentum_coercive
#check MolecularDynamics.textbookLangevinPeriodicProjection_isOpenQuotientMap
#check MolecularDynamics.textbookLangevinPeriodicHamiltonianPower
#check MolecularDynamics.textbookLangevinPeriodicHamiltonianPower_lift
#check MolecularDynamics.textbookLangevinPeriodicHamiltonianPower_continuous
#check MolecularDynamics.textbookLangevinPeriodicHamiltonianPower_pos
#check MolecularDynamics.textbookLangevinPeriodicHamiltonianPower_momentum_coercive
#check MolecularDynamics.textbookLangevinPeriodicHamiltonianPower_isCompact_sublevel
#check MolecularDynamics.textbookLangevinPeriodicHamiltonianPower_tendsto_atTop
#check MolecularDynamics.textbookLangevinPeriodicDifferentialOperator
#check MolecularDynamics.textbookLangevinPeriodicHamiltonianPower_lyapunov
#check MolecularDynamics.textbookLangevinPeriodicHamiltonianPower_operator_lift
#check MolecularDynamics.textbookLangevinLyapunov_physical_diffusion_coefficient
#check MolecularDynamics.textbookLangevinPeriodicHamiltonianPower_physical_lyapunov

#check MolecularDynamics.textbookLangevinIntegralSolution_noise_congr
#check MolecularDynamics.textbookLangevinPathRestriction
#check MolecularDynamics.textbookLangevinPathRestriction_lipschitz
#check MolecularDynamics.textbookLangevinPathEndpoint_restrict
#check MolecularDynamics.textbookLangevinRandomSolution_integralSolution_of_cont
#check MolecularDynamics.textbookLangevinGlobalRandomPhase_history_endpoint_ae
#check MolecularDynamics.textbookLangevinIntegralSolution_shift
#check MolecularDynamics.textbookLangevinPathSegment
#check MolecularDynamics.textbookLangevinPathSegment_zero
#check MolecularDynamics.textbookLangevinPathEndpoint_restart
#check MolecularDynamics.textbookLangevinGlobalRandomPhase_history_path_ae
#check MolecularDynamics.textbookLangevinGlobalRandomPhase_restart_ae
#check MolecularDynamics.textbookLangevinIntegralSolution_project
#check MolecularDynamics.textbookLangevinPeriodicIntegralSolution_unique
#check MolecularDynamics.textbookLangevinPeriodicPathEndpoint
#check MolecularDynamics.textbookLangevinPeriodicPathEndpoint_lift
#check MolecularDynamics.textbookLangevinPeriodicPathEndpoint_restart
#check MolecularDynamics.textbookLangevinPeriodicGlobalRandomPhase
#check MolecularDynamics.textbookLangevinPeriodicGlobalRandomPhase_integralSolution_ae
#check MolecularDynamics.textbookLangevinPeriodicGlobalRandomPhase_endpoint_aemeasurable
#check MolecularDynamics.textbookLangevinPeriodicGlobalRandomPhase_history_endpoint_ae
#check MolecularDynamics.textbookLangevinPeriodicGlobalRandomPhase_restart_ae

#check MolecularDynamics.textbookWienerVectorFuture
#check MolecularDynamics.textbookWienerVectorFuture_gaussian
#check MolecularDynamics.textbookWienerVectorFuture_isWiener
#check MolecularDynamics.textbookWienerVectorFuture_hasLaw_eval
#check MolecularDynamics.textbookWienerVectorFuture_covariance_history
#check MolecularDynamics.textbookWienerVectorFuture_independent_history
#check MolecularDynamics.textbookWienerVectorSamples_law_eq
#check MolecularDynamics.textbookWienerVectorFuture_samples_law
#check MolecularDynamics.textbookWienerVectorContinuousPath_law_eq
#check MolecularDynamics.textbookWienerVectorFuture_continuousPath_law
#check MolecularDynamics.textbookWienerVectorFuture_continuousPath_independent_history
#check MolecularDynamics.textbookWienerVectorFuture_segment_ae
#check MolecularDynamics.textbookLangevinGlobalRandomPhase_future_restart_ae
#check MolecularDynamics.textbookLangevinGlobalRandomPhase_history_aemeasurable
#check MolecularDynamics.textbookLangevinGlobalRandomPhase_future_independent_history
#check MolecularDynamics.textbookLangevinPeriodicGlobalRandomPhase_future_independent_history
#check MolecularDynamics.textbookLangevinGlobalRandomPhase_future_history_product_law

#check MolecularDynamics.textbookLangevinNoiseCompensated_initial_dist_le
#check MolecularDynamics.textbookLangevinIntegralSolution_initial_dist_le
#check MolecularDynamics.textbookLangevinPathEndpoint_initial_lipschitz
#check MolecularDynamics.textbookLangevinPathEndpoint_joint_continuous
#check MolecularDynamics.textbookLangevinPathEndpoint_joint_measurable
#check MolecularDynamics.textbookLangevinRandomInitial_endpoint_aemeasurable
#check MolecularDynamics.textbookLangevinPeriodicPathEndpoint_joint_continuous
#check MolecularDynamics.textbookLangevinPeriodicPathEndpoint_joint_measurable
#check MolecularDynamics.textbookLangevinPeriodicRandomInitial_endpoint_aemeasurable
