import MolecularDynamics.Chapter06.BrownianGibbsComplexResolvent
open MeasureTheory
#check IsCompactOperator.hasEigenvalue_iff_mem_spectrum
#check Module.End.HasEigenvalue.exists_hasEigenvector
#check Module.End.hasEigenvalue_of_hasEigenvector
#check Module.End.mem_genEigenspace_one
#check Module.End.hasEigenvector_iff
#check Module.End.hasEigenvalue_iff
#check inv_injective
#check mul_right_cancel₀
#check Set.mem_image
#check MolecularDynamics.textbookBrownianGibbsGeneratorRealSpectrum_eq_eigenbasis_range
#check MolecularDynamics.textbookBrownianGibbsGeneratorRealSpectrum_countable
#check isUnit_iff_exists
#check spectrum.mem_resolventSet_iff
#check IsUnit.mul_left_iff
#check Complex.ofReal_inj
#check Complex.ofReal_inv
#check Complex.ofReal_sub