import MolecularDynamics.Chapter06.BrownianPotentialSelfAdjoint
import Mathlib.Analysis.Normed.Operator.Compact.Basic
#check lp.singleContinuousLinearMap
#check lp.evalCLM
#check lp.memℓp
#check lp.coeFn_sub
#check lp.single_apply
#check IsCompactOperator.comp_clm
#check IsCompactOperator.clm_comp
#check Submodule.sum_mem
#check isCompactOperator_of_locallyCompactSpace_dom
#check isCompactOperator_of_tendsto
#check Complex.abs_re_le_norm
#check ContinuousLinearMap.opNorm_le_bound
#check Metric.tendsto_atTop
#check ContinuousLinearMap.restrictScalars
#check compactOperator
#check isCompactOperator_of_locallyCompactSpace_rng