import Blueprint.Ch03

#print axioms MD.Ch03.modifiedConstruction
#print axioms MD.Ch03.oscillatorAdjointEuler
#print axioms MD.Ch03.oscillatorShadow
#print axioms MD.Ch03.oscillatorEnergyFailure
#print axioms MD.Ch03.oscillatorShadowInvariant
#print axioms MD.Ch03.shadowEllipses
#print axioms MD.Ch03.eulerOscillatorGrowth
#print axioms MD.Ch03.formalHamiltonian
#print axioms MD.Ch03.formalHamiltonianField
#print axioms MD.Ch03.textbookLieDerivative
#print axioms MD.Ch03.observableDerivative
#print axioms MD.Ch03.observableSecondDerivative
#print axioms MD.Ch03.formalOperatorExponential
#print axioms MD.Ch03.formalObservable
#print axioms MD.Ch03.lieTaylor
#print axioms MD.Ch03.flowCoordinates
#print axioms MD.Ch03.textbookPoissonBracket
#print axioms MD.Ch03.poissonCoordinates
#print axioms MD.Ch03.poissonBilinearity
#print axioms MD.Ch03.poissonSkew
#print axioms MD.Ch03.poissonSelf
#print axioms MD.Ch03.poissonJacobi
#print axioms MD.Ch03.hamiltonianObservableDerivative
#print axioms MD.Ch03.hamiltonianLie_eq_poisson
#print axioms MD.Ch03.hamiltonianCoordinateDerivative
#print axioms MD.Ch03.hamiltonianLieAdditivity
#print axioms MD.Ch03.formalSplitting
#print axioms MD.Ch03.exactExponentialCubic
#print axioms MD.Ch03.productExponentialCubic
#print axioms MD.Ch03.differenceCommutator
#print axioms MD.Ch03.differenceCubic
#print axioms MD.Ch03.hamiltonianCommutator
#print axioms MD.Ch03.leadingShadowPrinted
#print axioms MD.Ch03.leadingModifiedExponential
#print axioms MD.Ch03.leadingShadowHamiltonian
#print axioms MD.Ch03.bch4
#print axioms MD.Ch03.bchHamiltonian3
#print axioms MD.Ch03.bchHamiltonianMatching
#print axioms MD.Ch03.commutingFlows
#print axioms MD.Ch03.symplecticEulerShadow3
#print axioms MD.Ch03.symplecticEulerShadowMatching
#print axioms MD.Ch03.verletMaps
#print axioms MD.Ch03.verletHamiltonianParts
#print axioms MD.Ch03.verletStructure
#print axioms MD.Ch03.verletModifiedH
#print axioms MD.Ch03.verletModifiedMatching
#print axioms MD.Ch03.modifiedEven
#print axioms MD.Ch03.formalStrang
#print axioms MD.Ch03.differentLogsCommute
#print axioms MD.Ch03.strangInverse
#print axioms MD.Ch03.strangCubic
#print axioms MD.Ch03.yoshidaCompose
#print axioms MD.Ch03.yoshidaCoefficients
#print axioms MD.Ch03.yoshidaCancellation
#print axioms MD.Ch03.yoshidaUnique
#print axioms MD.Ch03.yoshidaRaiseOrder
#print axioms MD.Ch03.yoshida4
#print axioms MD.Ch03.yoshida4Structure
#print axioms MD.Ch03.generalSplitting
#print axioms MD.Ch03.takahashiImada
#print axioms MD.Ch03.potentialDoubleBracket
#print axioms MD.Ch03.takahashiShadow2
#print axioms MD.Ch03.takahashiProcessor
#print axioms MD.Ch03.processorEnergyPrinted
#print axioms MD.Ch03.takahashiEffectiveOrder
#print axioms MD.Ch03.formalField
#print axioms MD.Ch03.leadingModifiedField
#print axioms MD.Ch03.truncatedHamiltonian
#print axioms MD.Ch03.truncationSmooth
#print axioms MD.Ch03.theorem31
#print axioms MD.Ch03.compactLipschitz
#print axioms MD.Ch03.truncatedFlow
#print axioms MD.Ch03.finiteMatchingConstruction
#print axioms MD.Ch03.truncatedConservation
#print axioms MD.Ch03.energyTelescoping
#print axioms MD.Ch03.uniformTruncatedLipschitz
#print axioms MD.Ch03.truncationRemainder
#print axioms MD.Ch03.physicalEnergyDrift
#print axioms MD.Ch03.polynomialEnergyRate
#print axioms MD.Ch03.stepCountPower
#print axioms MD.Ch03.arbitraryFiniteTruncation
#print axioms MD.Ch03.analyticBEA
#print axioms MD.Ch03.optimalTruncation
#print axioms MD.Ch03.exponentialFlat
#print axioms MD.Ch03.scalarVerletShadow4
#print axioms MD.Ch03.commutingEnergy
#print axioms MD.Ch03.commutingEnergySymmetry
#print axioms MD.Ch03.energySymplecticNoGo
#print axioms MD.Ch03.equalComponentFirstIntegral
#print axioms MD.Ch03.equalEulerIntegral
#print axioms MD.Ch03.linearEulerIntegral
#print axioms MD.Ch03.linearRKIntegral
#print axioms MD.Ch03.verletOscillatorEnergy
#print axioms MD.Ch03.momentumProjection
#print axioms MD.Ch03.projectionConstraint
#print axioms MD.Ch03.projectionFactor
#print axioms MD.Ch03.projectionEnergy
#print axioms MD.Ch03.kineticZero
#print axioms MD.Ch03.energyProjectionRelation
#print axioms MD.Ch03.noHamiltonianAttractor
#print axioms MD.Ch03.linearContinuousIntegral
#print axioms MD.Ch03.hamiltonianFlowStructures
#print axioms MD.Ch03.volumeNotSymplectic
#print axioms MD.Ch03.linearInvolution
#print axioms MD.Ch03.reversedField
#print axioms MD.Ch03.momentumReversal
#print axioms MD.Ch03.mechanicalReversalPrinted
#print axioms MD.Ch03.reversedTrajectoryPrinted
#print axioms MD.Ch03.reversedTrajectory
#print axioms MD.Ch03.flowReversal
#print axioms MD.Ch03.flowReversalIdentity
#print axioms MD.Ch03.reversibleMethod
#print axioms MD.Ch03.symmetricMethod
#print axioms MD.Ch03.affineInvariant
#print axioms MD.Ch03.symmetricAffineReversible
#print axioms MD.Ch03.rkAffine
#print axioms MD.Ch03.partitionedAffinePrinted
#print axioms MD.Ch03.partitionedAffine
#print axioms MD.Ch03.symplecticNotReversible
#print axioms MD.Ch03.trapezoidalRelation
#print axioms MD.Ch03.trapezoidalProperties
#print axioms MD.Ch03.hamiltonianSpectrum
#print axioms MD.Ch03.symplecticSpectrum
#print axioms MD.Ch03.reversibleSpectrum
#print axioms MD.Ch03.conjugateIterates
#print axioms MD.Ch03.mechanicalReversalCorrect
#print axioms MD.Ch03.conjugateOrderPrinted
#print axioms MD.Ch03.reversibleVolumeFailure
