import Blueprint.Ch02

#print axioms MD.Ch02.hamiltonianODE
#print axioms MD.Ch02.mechanicalHamiltonian
#print axioms MD.Ch02.canonicalJ
#print axioms MD.Ch02.euler
#print axioms MD.Ch02.numericalTrajectory
#print axioms MD.Ch02.convergence
#print axioms MD.Ch02.order
#print axioms MD.Ch02.maximumError
#print axioms MD.Ch02.theorem_2_1
#print axioms MD.Ch02.odeSecondDerivative
#print axioms MD.Ch02.taylorSecond
#print axioms MD.Ch02.taylor2Order
#print axioms MD.Ch02.verletOrder
#print axioms MD.Ch02.bp_mechanicalL
#print axioms MD.Ch02.admissibleSmooth
#print axioms MD.Ch02.bp_action
#print axioms MD.Ch02.bp_variation
#print axioms MD.Ch02.firstVariation
#print axioms MD.Ch02.taylorPrinted
#print axioms MD.Ch02.stationarySmoothAction
#print axioms MD.Ch02.firstVariationParts
#print axioms MD.Ch02.hamiltonPrinciple
#print axioms MD.Ch02.printedVariationalDerivative
#print axioms MD.Ch02.stationaryNotMinimum
#print axioms MD.Ch02.finiteDiscretePath
#print axioms MD.Ch02.bp_discreteVelocity
#print axioms MD.Ch02.bp_discreteAction
#print axioms MD.Ch02.printedDiscreteStationary
#print axioms MD.Ch02.discreteActionDerivative
#print axioms MD.Ch02.discreteStationaryVerlet
#print axioms MD.Ch02.bp_stormerRelation
#print axioms MD.Ch02.bp_velocityVerlet
#print axioms MD.Ch02.velocityVerletStormer
#print axioms MD.Ch02.bp_verlet
#print axioms MD.Ch02.bp_leapfrog
#print axioms MD.Ch02.bp_leapfrogInitialize
#print axioms MD.Ch02.bp_leapfrogReconstruct
#print axioms MD.Ch02.errorDifference
#print axioms MD.Ch02.consistency
#print axioms MD.Ch02.stability
#print axioms MD.Ch02.errorRecursion
#print axioms MD.Ch02.errorBound
#print axioms MD.Ch02.consistencyConvergence
#print axioms MD.Ch02.bp_scalarVerlet
#print axioms MD.Ch02.verletExpansion
#print axioms MD.Ch02.exactExpansion
#print axioms MD.Ch02.defectPrinted
#print axioms MD.Ch02.verletConsistency
#print axioms MD.Ch02.verletStability
#print axioms MD.Ch02.bp_firstIntegral
#print axioms MD.Ch02.firstIntegralPreserved
#print axioms MD.Ch02.energyPreserved
#print axioms MD.Ch02.centralAngularMomentum
#print axioms MD.Ch02.integralMeanValue
#print axioms MD.Ch02.integralPointwiseBound
#print axioms MD.Ch02.integralErrorPrinted
