"""Eight §3.6.2 entries, original PDF151–152."""
from ch03_data import add,copied,proposition,D
add('FlowReversal','3.6.2',129,[109],r'''From this we see that if we start from a point $z_0$ and integrate forward in time (i.e apply $\mathcal F_t$) then apply the involution $R$, we get the exact same result as if we start from $\widetilde z(0)=Rz_0$ and integrate backward in time (i.e. apply $\mathcal F_{-t}$). In sum, since $z_0$ is an arbitrary point,
\[\mathcal F_{-t}(Rz)=R\mathcal F_t(z).\]''',proposition('flowReversal_statement'),extra=['正确R反转、C¹场和全实时间真实流；不把所需反转等式藏进流假设。'],missing='缺C¹场ODE唯一性到全时间反向轨道一致的完整桥接；不建设新ODE唯一性理论。')
add('FlowReversalIdentity','3.6.2',129,[110],r'''For the flow map, $\mathcal F_{-t}=\mathcal F_t^{-1}$ so we can recast the identity as
\[R\circ\mathcal F_t\circ R\circ\mathcal F_t=\mathrm{Id},\tag{3.14}\]''',proposition('flowReversalIdentity_statement'),label='(3.14)',extra=['正确R反转、C¹场、实际全时间流、群性质；不供应结论。'],missing='依赖尚未桥接的完整FlowReversal及实际流唯一性。')
add('ReversibleMethod','3.6.2',130,[111],r'''It does not automatically follow that a symmetric numerical method is time-reversible, i.e. satisfies a relation inspired by (3.14), namely
\[R\circ\mathcal G_h\circ R\circ\mathcal G_h=\mathrm{Id}.\tag{3.15}\]''',copied(D,'reversibleMethod'),kind='definition',label='(3.15)')
add('SymmetricMethod','3.6.2',130,[112],r'''Recall from the previous chapter that a numerical method $\mathcal G_h$ was said to be symmetric if it satisfied
\[\mathcal G_{-h}=\mathcal G_h^{-1}.\]''',copied(D,'symmetricMethod'),kind='definition',context=['equivalence给实际逆映射；与固定R的可逆性分开。'])
add('AffineInvariant','3.6.2',130,[113],r'''Definition 3.1 (Affine Invariance) Let
\[\frac{\mathrm d\boldsymbol z}{\mathrm dt}=f(\boldsymbol z)\tag{3.16}\]
be a given ordinary differential equation. The transformation $\widetilde{\boldsymbol z}=A\boldsymbol z$, where $A$ is a non-singular square matrix, results in the modified differential equation
\[\frac{\mathrm d\boldsymbol z}{\mathrm dt}=Af(A^{-1}\widetilde{\boldsymbol z}).\tag{3.17}\]
Let $z_0,z_1,\ldots$ be a sequence of points obtained by application of the numerical method $\mathcal G_h$ to (3.16). If the same method, when applied to (3.17) produces the set of points $Az_0,Az_1,\ldots$, then we say that the numerical method is invariant with respect to the transformation $\widetilde{\boldsymbol z}=Az$. An affine invariant method is one which is invariant under any such transformation.''',copied(D,'affineInvariant'),kind='definition',label='Definition 3.1',context=['A为连续线性等价；原定义未含平移，保留该范围；transportedField给真正A f A⁻¹。'],issues=[dict(code='ERRATUM?',detail='(3.17)左端印刷z而不是z̃；保留原文，语义按前后说明的变换坐标。')])
add('SymmetricAffineReversible','3.6.2',130,[114],r'''If a differential equation is time-reversible with respect to the involution $R$, and we apply a method which is affine invariant and symmetric, then the method will be time-reversible (3.15).''',proposition('symmetricAffineReversible_statement'),extra=['[EXTRA]G_{−f}(h)=G_f(−h)显式给步长符号相容性；原文没列这项，任意抽象方法仅线性等变与对称未必足够。'],verdict='NEEDS_HUMAN',explanation='额外符号相容性是独立必要资格，不能当作原书已明示假设。',issues=[dict(code='NEEDS_HUMAN',detail='一般方法需要G_{−f}(h)=G_f(−h)，否则原文蕴含式条件不全。')],missing='本地非PASS不进入证明；条件化有限代数推论可另审。')
add('RKAffine','3.6.2',130,[115],r'''All Runge-Kutta methods and Partitioned Runge-Kutta methods are affine invariant, thus, if they are also symmetric, then they preserve time-reversal symmetry.''',proposition('rkAffine_statement',proof='exact MolecularDynamics.Chapter03Review.rkAffine_proved'),context=['本条仅保留Runge–Kutta实际阶段关系在线性等价下的运输；PRK与对称可逆推论为相邻条目，合起来覆盖原句。'],prior=['MolecularDynamics.Chapter03Review.rkAffine_proved'])
add('PartitionedAffinePrinted','3.6.2',130,[116],r'''All Runge-Kutta methods and Partitioned Runge-Kutta methods are affine invariant, thus, if they are also symmetric, then they preserve time-reversal symmetry.''',proposition('partitionedAffinePrinted_statement','partitionedAffinePrinted'),verdict='NEEDS_HUMAN',explanation='任意混合q,p的线性等价通常不保持不同PRK表格的分区；字面全称保留待反例审查。',issues=[dict(code='ERRATUM?',detail='PRK一般只对保持分区的分块线性变换等变；任意混合变换的全称可疑。')],missing='字面非PASS不证明；正确分块运输另列。')
