import Lean
import MolecularDynamicsFormalization

-- Keep explicit dependency evidence for the current key textbook theorem.
-- Add corresponding commands when new key theorems enter the formal library.
#print axioms MolecularDynamics.nBodyKineticEnergy_nonneg
#print axioms MolecularDynamics.unflatten_flatten
#print axioms MolecularDynamics.flatten_unflatten
#print axioms MolecularDynamics.coordinateMassesOfParticles_pos_iff
#print axioms MolecularDynamics.nBodyKineticEnergy_particle_eq
#print axioms MolecularDynamics.diagonalMassMatrix_posDef_iff
#print axioms MolecularDynamics.diagonalMassMatrix_inv_eq
#print axioms MolecularDynamics.diagonalMassMatrix_inv_mulVec
#print axioms MolecularDynamics.massOperator_velocityOperator
#print axioms MolecularDynamics.velocityOperator_massOperator
#print axioms MolecularDynamics.isMechanicalSolutionOn_iff_components
#print axioms MolecularDynamics.momentum_eq_mass_deriv_position
#print axioms MolecularDynamics.hasDerivAt_deriv_position
#print axioms MolecularDynamics.solution_nBodyEquationAt
#print axioms MolecularDynamics.solution_nBodyEquationAt_of_differentiable
#print axioms MolecularDynamics.solution_hasGradientAt_potential
#print axioms MolecularDynamics.newtonTrajectory_to_mechanicalSolution
#print axioms MolecularDynamics.freeParticle_localIVP
#print axioms MolecularDynamics.IsLocalMechanicalIVP.initial_mem

#print axioms MolecularDynamics.momentumKineticEnergy_eq_inner
#print axioms MolecularDynamics.momentumKineticEnergy_massOperator
#print axioms MolecularDynamics.massHamiltonian_massOperator
#print axioms MolecularDynamics.massHamiltonian_particle
#print axioms MolecularDynamics.massHamiltonian_velocityOperator
#print axioms MolecularDynamics.hasGradientAt_momentumKineticEnergy
#print axioms MolecularDynamics.gradient_momentumKineticEnergy_eq_velocityOperator
#print axioms MolecularDynamics.gradient_position_slice
#print axioms MolecularDynamics.hasGradientAt_position_slice
#print axioms MolecularDynamics.hamiltonianVectorField_eq

#print axioms MolecularDynamics.mechanical_energy_hasDerivAt_zero
#print axioms MolecularDynamics.mechanical_energy_const_on_Ioo
#print axioms MolecularDynamics.mechanicalVectorField_contDiffAt
#print axioms MolecularDynamics.exists_localMechanicalIVP_open_of_force_contDiffAt
#print axioms MolecularDynamics.mechanicalSolution_unique_on_Ioo
#print axioms MolecularDynamics.mechanicalSolution_eventually_unique_of_contDiffAt
#print axioms MolecularDynamics.totalMomentumCoordinate_hasDerivAt_zero
#print axioms MolecularDynamics.totalMomentumCoordinate_const_on_Ioo
#print axioms MolecularDynamics.strictPotentialMin_mechanicalEquilibrium
#print axioms MolecularDynamics.momentumKineticEnergy_nonneg
#print axioms MolecularDynamics.momentum_norm_sq_le
#print axioms MolecularDynamics.momentum_norm_le_of_energy
#print axioms MolecularDynamics.momentum_norm_lt_of_kineticEnergy
#print axioms MolecularDynamics.isCompact_phaseEnergySublevel
#print axioms MolecularDynamics.mechanicalSolution_below_barrier_stays_in_ball
#print axioms MolecularDynamics.mechanicalSolution_phase_dist_lt
#print axioms MolecularDynamics.exists_rightEndpointLimit_of_lipschitzOnWith
#print axioms MolecularDynamics.exists_rightEndpointLimit_mem_of_lipschitzOnWith
#print axioms MolecularDynamics.mechanicalSolution_lipschitzOnWith_of_field_bound
#print axioms MolecularDynamics.mechanicalSolution_has_rightEndpointLimit_of_field_bound
#print axioms MolecularDynamics.mechanicalSolution_has_rightEndpointLimit_of_compact
#print axioms MolecularDynamics.mechanicalSolution_unique_on_preconnected_of_contDiffAt
#print axioms MolecularDynamics.mechanicalSolution_glue_on_Ioo
#print axioms MolecularDynamics.hasDerivWithinAt_rightEndpoint_of_continuousOn
#print axioms MolecularDynamics.exists_localODE_matching_rightEndpoint
#print axioms MolecularDynamics.mechanicalSolution_extend_of_rightEndpointLimit
#print axioms MolecularDynamics.mechanicalSolution_extend_of_force_contDiffAt
#print axioms MolecularDynamics.mechanicalSolution_extend_of_compact

#print axioms MolecularDynamics.strictOn_iff_punctured
#print axioms MolecularDynamics.strictUniv_iff
#print axioms MolecularDynamics.strictOn_isLocalMinOn
#print axioms MolecularDynamics.compact_positive_gap
#print axioms MolecularDynamics.fixed_sphere_barrier
#print axioms MolecularDynamics.open_domain_barrier
#print axioms MolecularDynamics.energy_excludes_sphere
#print axioms MolecularDynamics.energy_below_barrier_excludes_sphere
#print axioms MolecularDynamics.conserved_trajectory_stays_in_ball
#print axioms MolecularDynamics.conserved_trajectory_below_barrier_stays_in_ball
#print axioms MolecularDynamics.conserved_trajectory_center_below_barrier_stays_in_ball
#print axioms MolecularDynamics.open_domain_energy_confinement
#print axioms MolecularDynamics.zero_dimensional_sphere_empty
#print axioms MolecularDynamics.zero_dimensional_barrier
#print axioms MolecularDynamics.zero_dimensional_strict_min
#print axioms MolecularDynamics.singleton_relative_strict
#print axioms MolecularDynamics.singleton_sphere_not_subset
#print axioms MolecularDynamics.quartic_strict_min
#print axioms MolecularDynamics.quartic_sphere_barrier
#print axioms MolecularDynamics.constant_local_min
#print axioms MolecularDynamics.constant_not_strict
#print axioms MolecularDynamics.endpoint_strict_radius
#print axioms MolecularDynamics.endpoint_potential_continuous
#print axioms MolecularDynamics.endpoint_no_barrier
#print axioms MolecularDynamics.quartic_potential_continuous

-- Audit all declarations in the imported project namespace, including private
-- declarations after removing their generated private-name prefix.
open Lean Elab Command in
run_cmd do
  let allowed : Array Name := #[`propext, `Classical.choice, `Quot.sound]
  let env ← getEnv
  let names := env.constants.fold (init := #[]) fun names name _ =>
    if (`MolecularDynamics).isPrefixOf (privateToUserName name) then
      names.push name
    else
      names
  if names.isEmpty then
    throwError "No project declarations were found in the imported environment."
  for name in names do
    let dependencies ← collectAxioms name
    for dependency in dependencies do
      unless allowed.contains dependency do
        throwError "{name} depends on a disallowed logical dependency: {dependency}"
  logInfo m!"Dependency audit passed for {names.size} imported project declarations; allowed: {allowed}."
#print axioms MolecularDynamics.exists_glued_function_of_compatible
#print axioms MolecularDynamics.exists_mechanicalSolutionOn_iUnion
#print axioms MolecularDynamics.exists_globalMechanicalSolution_of_local_compact_confinement
#print axioms MolecularDynamics.exists_globalMechanicalIVP_of_energy_barrier
#print axioms MolecularDynamics.gradient_contDiffAt_of_potential_contDiffAt_two
#print axioms MolecularDynamics.strictPotentialMin_exists_future_bound
#print axioms MolecularDynamics.strictPotentialMin_futureStable
#print axioms MolecularDynamics.strictPotentialMin_futureStable_of_potential_contDiffAt_two
#print axioms MolecularDynamics.product_dist_le_phaseEuclideanDistance
#print axioms MolecularDynamics.phaseEuclideanDistance_le_two_mul_dist
#print axioms MolecularDynamics.IsFutureMechanicalStable.euclidean
#print axioms MolecularDynamics.strictPotentialMin_futureStableEuclidean_of_potential_contDiffAt_two
#print axioms MolecularDynamics.strictPotentialMin_futureStableEuclidean_of_smooth
#print axioms MolecularDynamics.nBodyKineticEnergy_eq_inner
#print axioms MolecularDynamics.hasGradientAt_nBodyKineticEnergy
#print axioms MolecularDynamics.hasGradientAt_massLagrangian_velocity
#print axioms MolecularDynamics.hasGradientAt_massLagrangian_position
#print axioms MolecularDynamics.mechanicalSolution_eulerLagrange
#print axioms MolecularDynamics.eulerLagrange_to_mechanicalSolution
#print axioms MolecularDynamics.massLagrangian_coordinateChange
#print axioms MolecularDynamics.hasDerivAt_coordinateChange
#print axioms MolecularDynamics.generalizedMassMatrix_posDef
#print axioms MolecularDynamics.generalizedMassMatrix_isUnit
#print axioms MolecularDynamics.massHamiltonian_legendre_gap
#print axioms MolecularDynamics.legendre_objective_le_massHamiltonian
#print axioms MolecularDynamics.legendre_objective_attains_massHamiltonian
#print axioms MolecularDynamics.nBodyKineticEnergy_eq_zero_iff
#print axioms MolecularDynamics.legendre_objective_eq_massHamiltonian_iff
#print axioms MolecularDynamics.massHamiltonian_eq_legendre_sup
#print axioms MolecularDynamics.mechanicalSolution_translate_on_Ioi
#print axioms MolecularDynamics.futureMechanicalFlow_add
#print axioms MolecularDynamics.futureMechanicalFlow_commute
#print axioms MolecularDynamics.futureMechanicalFlow_energy
#print axioms MolecularDynamics.futureMechanicalFlow_injOn
#print axioms MolecularDynamics.exists_futureMechanicalFlow_of_energy_barrier
#print axioms MolecularDynamics.massHamiltonian_momentumReflection
#print axioms MolecularDynamics.mechanicalSolution_time_reverse_on_Iio
#print axioms MolecularDynamics.exists_globalMechanicalIVP_of_energy_barrier_two_sided
#print axioms MolecularDynamics.mechanicalSolution_translate_on_univ
#print axioms MolecularDynamics.mechanicalSolution_energy_on_univ
#print axioms MolecularDynamics.globalMechanicalFlow_add
#print axioms MolecularDynamics.globalMechanicalFlow_inverse
#print axioms MolecularDynamics.globalMechanicalFlow_commute
#print axioms MolecularDynamics.globalMechanicalFlow_bijOn
#print axioms MolecularDynamics.globalMechanicalFlow_energy
#print axioms MolecularDynamics.exists_globalMechanicalFlow_of_energy_barrier
#print axioms MolecularDynamics.harmonicFlow_isMechanicalSolution
#print axioms MolecularDynamics.harmonicFlow_isGlobalFlow
#print axioms MolecularDynamics.harmonicFlow_continuous
#print axioms MolecularDynamics.harmonicFlow_add
#print axioms MolecularDynamics.harmonicFlow_inverse
#print axioms MolecularDynamics.harmonicContinuousFlow
#print axioms MolecularDynamics.hasGradientAt_harmonicPotential
#print axioms MolecularDynamics.harmonicFlow_energy
#print axioms MolecularDynamics.freeParticleFlow_isMechanicalSolution
#print axioms MolecularDynamics.freeParticleFlow_isGlobalFlow
#print axioms MolecularDynamics.freeParticleFlow_continuous
#print axioms MolecularDynamics.freeParticleFlow_add
#print axioms MolecularDynamics.freeParticleContinuousFlow
#print axioms MolecularDynamics.freeParticleFlow_energy
#print axioms MolecularDynamics.hasDerivAt_linearExponentialFlow
#print axioms MolecularDynamics.linearExponentialFlow_add
#print axioms MolecularDynamics.linearExponentialFlow_continuous
#print axioms MolecularDynamics.linearContinuousFlow
#print axioms MolecularDynamics.linearExponentialFlow_inverse
#print axioms MolecularDynamics.hasDerivAt_linearExponentialFlow_initial_time
#print axioms MolecularDynamics.linearExponentialFlow_unique
#print axioms MolecularDynamics.linearExponentialOperator_series
#print axioms MolecularDynamics.matrixExponentialFlow_eq
#print axioms MolecularDynamics.hasDerivAt_matrixExponentialFlow
#print axioms MolecularDynamics.hasDerivAt_matrixExponentialFlow_initial_time
#print axioms MolecularDynamics.matrixExponentialFlow_unique
#print axioms MolecularDynamics.matrixContinuousFlow
#print axioms MolecularDynamics.matrixExponential_series
#print axioms MolecularDynamics.hasDerivAt_realEigenmode
#print axioms MolecularDynamics.linearExponentialFlow_realEigenmode
#print axioms MolecularDynamics.linearExponentialFlow_realSpectral_sum
#print axioms MolecularDynamics.linearExponentialFlow_realEigenbasis
#print axioms MolecularDynamics.hasDerivAt_complexEigenmode
#print axioms MolecularDynamics.complexExponentialFlow_eigenmode
#print axioms MolecularDynamics.complexExponentialFlow_spectral_sum
#print axioms MolecularDynamics.complexExponentialFlow_eigenbasis
#print axioms MolecularDynamics.hasDerivAt_complexExponentialFlow
#print axioms MolecularDynamics.complexContinuousFlow
#print axioms MolecularDynamics.complexEigenbasis_coefficients_unique
#print axioms MolecularDynamics.linearExponentialFlow_intertwine
#print axioms MolecularDynamics.linearExponentialFlow_fixed_clm
#print axioms MolecularDynamics.realMatrix_conjugation_commute
#print axioms MolecularDynamics.realMatrix_complexFlow_isReal
#print axioms MolecularDynamics.realMatrix_complexSpectral_sum_isReal
#print axioms MolecularDynamics.basisColumnMatrix_mulVec
#print axioms MolecularDynamics.basisColumnMatrix_mulVec_repr
#print axioms MolecularDynamics.basisColumnMatrix_isUnit
#print axioms MolecularDynamics.basisColumnMatrix_inverse_coefficients
#print axioms MolecularDynamics.firstIntegral_hasDerivAt_zero
#print axioms MolecularDynamics.firstIntegral_const_on_Ioo
#print axioms MolecularDynamics.firstIntegral_differential_necessary
#print axioms MolecularDynamics.isFirstIntegralOn_iff_differential
#print axioms MolecularDynamics.firstIntegral_gradient_criterion
#print axioms MolecularDynamics.planarAngularMomentum_hasDerivAt_zero
#print axioms MolecularDynamics.planarAngularMomentum_const_on_Ioo
#print axioms MolecularDynamics.centralForce_planarAngularMomentum_const
#print axioms MolecularDynamics.polarKinetic_identity
#print axioms MolecularDynamics.polarAngularMomentum_identity
#print axioms MolecularDynamics.keplerPolarLagrangian_identity
#print axioms MolecularDynamics.polarCoordinates_hasDerivAt_components
#print axioms MolecularDynamics.polarJacobian_det
#print axioms MolecularDynamics.polarJacobian_isUnit_iff
#print axioms MolecularDynamics.hasGradientAt_keplerPotential
#print axioms MolecularDynamics.keplerForce_eq_neg_gradient
#print axioms MolecularDynamics.keplerForce_contDiffAt
#print axioms MolecularDynamics.exists_kepler_localIVP
#print axioms MolecularDynamics.kepler_energy_const_on_Ioo
#print axioms MolecularDynamics.kepler_planarAngularMomentum_const_on_Ioo
#print axioms MolecularDynamics.hasStrictFDerivAt_polarCoordinateMap
#print axioms MolecularDynamics.exists_polarDerivativeEquiv
#print axioms MolecularDynamics.fderiv_polarCoordinateMap
#print axioms MolecularDynamics.exists_polarLocalChart_strictInverse
#print axioms MolecularDynamics.exists_polarLocalChart
#print axioms MolecularDynamics.keplerPolar_partial_v
#print axioms MolecularDynamics.keplerPolar_partial_ω
#print axioms MolecularDynamics.keplerPolar_partial_r
#print axioms MolecularDynamics.keplerPolar_partial_θ
#print axioms MolecularDynamics.keplerPolar_eulerLagrange_iff
#print axioms MolecularDynamics.keplerPolar_angular_const
#print axioms MolecularDynamics.keplerPolar_radial_reduction
#print axioms MolecularDynamics.keplerRadialEnergy_formula
#print axioms MolecularDynamics.keplerRadialEnergy_hasDerivAt_zero
#print axioms MolecularDynamics.keplerPolar_radialEnergy_const
#print axioms MolecularDynamics.keplerPolar_angle_integral
#print axioms MolecularDynamics.keplerPolar_radialEnergy_const_initialAngular
#print axioms MolecularDynamics.keplerPolar_energy_radial_identity
#print axioms MolecularDynamics.norm_polarCartesianPosition
#print axioms MolecularDynamics.polarCartesianState_angular
#print axioms MolecularDynamics.polarCartesianState_energy
#print axioms MolecularDynamics.hasDerivAt_planarPair
#print axioms MolecularDynamics.keplerPolar_angularVelocity_hasDerivAt
#print axioms MolecularDynamics.polarCartesianState_momentum_hasDerivAt
#print axioms MolecularDynamics.keplerPolarEL_to_cartesianMechanical
#print axioms MolecularDynamics.polarCartesianState_force
#print axioms MolecularDynamics.polarCartesianState_radialVelocity
#print axioms MolecularDynamics.cartesianMechanical_to_keplerPolarEL
#print axioms MolecularDynamics.keplerPolarEL_iff_cartesianMechanical
#print axioms MolecularDynamics.keplerReconstructedAngle_initial
#print axioms MolecularDynamics.keplerReconstructedAngle_hasDerivAt
#print axioms MolecularDynamics.keplerRadial_reconstruction_isEulerLagrange
#print axioms MolecularDynamics.keplerRadial_reconstruction_isMechanical
#print axioms MolecularDynamics.keplerRadialForce_contDiffAt
#print axioms MolecularDynamics.exists_keplerRadial_localIVP
#print axioms MolecularDynamics.exists_keplerRadial_reconstructed_localIVP
#print axioms MolecularDynamics.exists_polarCartesian_initialRepresentation
#print axioms MolecularDynamics.exists_kepler_localIVP_radialReconstruction
#print axioms MolecularDynamics.separableTimePrimitive_initial
#print axioms MolecularDynamics.separableTimePrimitive_hasStrictDerivAt
#print axioms MolecularDynamics.separableTimePrimitive_localInverse
#print axioms MolecularDynamics.separableTimePrimitive_along_solution
#print axioms MolecularDynamics.separableTimePrimitive_inverse_along_solution
#print axioms MolecularDynamics.keplerRadial_energy_speedSquare
#print axioms MolecularDynamics.keplerRadialBranchSpeed_eq_velocity
#print axioms MolecularDynamics.keplerRadialSpeedSquare_continuousAt
#print axioms MolecularDynamics.keplerRadialEnergy_const_on_Ioo
#print axioms MolecularDynamics.keplerRadial_signedQuadrature_inverse_on_branch
#print axioms MolecularDynamics.exists_keplerRadial_nonturning_window
#print axioms MolecularDynamics.keplerRadial_nonturning_signedQuadrature
#print axioms MolecularDynamics.keplerRadial_nonturning_quadrature
#print axioms MolecularDynamics.harmonicAction_time_formula
#print axioms MolecularDynamics.harmonicAction_harmonicFlow
#print axioms MolecularDynamics.harmonicActionAmplitude_pos
#print axioms MolecularDynamics.harmonicActionVelocity_formula
#print axioms MolecularDynamics.harmonicAction_energy
#print axioms MolecularDynamics.harmonicActionAmplitude_hasDerivAt
#print axioms MolecularDynamics.harmonicAction_hasDerivAt_components
#print axioms MolecularDynamics.harmonicAction_derivative_coefficients_iff
#print axioms MolecularDynamics.harmonicAction_ode_iff
#print axioms MolecularDynamics.harmonicAction_explicit_solution
#print axioms MolecularDynamics.exists_harmonicAction_representation
#print axioms MolecularDynamics.harmonicActionAmplitude_hasStrictDerivAt
#print axioms MolecularDynamics.harmonicActionJacobian_det
#print axioms MolecularDynamics.hasStrictFDerivAt_harmonicActionMap
#print axioms MolecularDynamics.fderiv_harmonicActionMap
#print axioms MolecularDynamics.exists_harmonicActionLocalChart
#print axioms MolecularDynamics.harmonicTorusPhase_rotation_coordinates
#print axioms MolecularDynamics.harmonicTorusPhase_rotation_isMechanical
#print axioms MolecularDynamics.harmonicTorusRotation_continuous
#print axioms MolecularDynamics.harmonicTorusRotation_add
#print axioms MolecularDynamics.harmonicTorusRotation_periodic_iff
#print axioms MolecularDynamics.harmonicTorusRotation_periodic_iff_integer
#print axioms MolecularDynamics.harmonicTorusRotation_integerFrequencies_periodic
#print axioms MolecularDynamics.harmonicTorusPhase_continuous
#print axioms MolecularDynamics.harmonicTorusPhase_realAngles
#print axioms MolecularDynamics.harmonicTorusPhase_energy
#print axioms MolecularDynamics.harmonicTorusPhase_image_fixedEnergy
#print axioms MolecularDynamics.harmonicTorusPhase_injective
#print axioms MolecularDynamics.harmonicTorusPhase_isClosedEmbedding
#print axioms MolecularDynamics.exists_harmonicTorusPhase_homeomorph
#print axioms MolecularDynamics.harmonicTorusThreeResonance_rotation
#print axioms MolecularDynamics.harmonicTorusRotation_three_resonant_not_dense
#print axioms MolecularDynamics.harmonicTorusRotation_two_dense_zero
#print axioms MolecularDynamics.harmonicTorusRotation_two_dense
#print axioms MolecularDynamics.harmonicTorusPhase_two_dense_fixedEnergy
#print axioms MolecularDynamics.harmonicTorusRotation_two_positivePeriod_iff_rational
#print axioms MolecularDynamics.harmonicTorusRotation_two_irrational_no_positivePeriod
#print axioms MolecularDynamics.harmonicTorusPhase_periodic_of_rotation_periodic
#print axioms MolecularDynamics.harmonicTorusPhase_periodic_iff_rotation_periodic
#print axioms MolecularDynamics.harmonicTorusPhase_two_positivePeriod_iff_rational
#print axioms MolecularDynamics.harmonicTorusPhase_two_irrational_no_positivePeriod
#print axioms MolecularDynamics.planarScalarPartial_isInvertible
#print axioms MolecularDynamics.exists_planarFirstIntegral_localGraph
#print axioms MolecularDynamics.planarFirstIntegral_localGraph_reduction
#print axioms MolecularDynamics.exists_planarFirstIntegral_C1Graph
#print axioms MolecularDynamics.exists_planarFirstIntegral_quadratureWindow
#print axioms MolecularDynamics.planarFirstIntegral_nonturning_quadrature
#print axioms MolecularDynamics.scalarPotentialEnergy_contDiff
#print axioms MolecularDynamics.scalarPotentialVectorField_contDiff
#print axioms MolecularDynamics.scalarPotentialEnergy_hasDerivAt_zero
#print axioms MolecularDynamics.scalarPotentialEnergy_isFirstIntegral
#print axioms MolecularDynamics.scalarPotentialEnergy_velocityPartial
#print axioms MolecularDynamics.scalarPotential_nonturning_quadrature
#print axioms MolecularDynamics.scalarPotentialSwappedEnergy_contDiff
#print axioms MolecularDynamics.scalarPotentialSwappedField_contDiff
#print axioms MolecularDynamics.scalarPotentialSwappedEnergy_isFirstIntegral
#print axioms MolecularDynamics.scalarPotentialSwappedEnergy_positionPartial
#print axioms MolecularDynamics.scalarPotential_regularTurning_quadrature
#print axioms MolecularDynamics.scalarPotential_equilibrium_constant
#print axioms MolecularDynamics.scalarPotential_equilibrium_locally_unique
#print axioms MolecularDynamics.scalarPotential_equilibrium_on_Ioo
#print axioms MolecularDynamics.scalarPotential_localDescription
#print axioms MolecularDynamics.scalarPotential_exists_localIVP
#print axioms MolecularDynamics.scalarPotential_exists_localIVP_integrable
#print axioms MolecularDynamics.equilibrium_constant_ode_iff
#print axioms MolecularDynamics.equilibriumLinearizationRemainder_isLittleO
#print axioms MolecularDynamics.equilibriumLinearizationRemainder_of_C1
#print axioms MolecularDynamics.actual_perturbation_ode
#print axioms MolecularDynamics.equilibrium_linearized_IVP
#print axioms MolecularDynamics.mechanicalLinearization_apply
#print axioms MolecularDynamics.hasFDerivAt_mechanicalVectorField
#print axioms MolecularDynamics.conservative_mechanical_linearization
#print axioms MolecularDynamics.exists_C1_localContinuousSolutionFamily
#print axioms MolecularDynamics.exists_localContinuousMechanicalFamily
#print axioms MolecularDynamics.exists_localContinuousMechanicalFamily_open
#print axioms MolecularDynamics.potential_hessian_symmetric
#print axioms MolecularDynamics.potential_hessian_symmetric_apply
#print axioms MolecularDynamics.conservative_linearization_hessian_data
#print axioms MolecularDynamics.linearizedHamiltonianQuadratic
#print axioms MolecularDynamics.linearizedHamiltonianQuadratic_eq_textbook_form
#print axioms MolecularDynamics.linearizedHamiltonianQuadratic_nonneg
#print axioms MolecularDynamics.linearizedHamiltonianQuadratic_nonneg_of_hessian
#print axioms MolecularDynamics.uniformPairPotentialEnergy
#print axioms MolecularDynamics.uniformPairPotentialEnergy_translate
#print axioms MolecularDynamics.uniformPairPotentialEnergy_two
#print axioms MolecularDynamics.nearestNeighborPotentialEnergy
#print axioms MolecularDynamics.nearestNeighborPotentialEnergy_translate
#print axioms MolecularDynamics.nearestNeighborPotentialEnergy_two
#print axioms MolecularDynamics.periodicNearestNeighborPotentialEnergy
#print axioms MolecularDynamics.periodicNearestNeighborPotentialEnergy_translate
#print axioms MolecularDynamics.walledNearestNeighborPotentialEnergy
#print axioms MolecularDynamics.boxPeriodicNearestNeighborPotentialEnergy
#print axioms MolecularDynamics.boxPeriodicNearestNeighborPotentialEnergy_translate
#print axioms MolecularDynamics.gradientLinearizationRemainder
#print axioms MolecularDynamics.gradientLinearizationRemainder_isLittleO
#print axioms MolecularDynamics.gradientLinearization_expansion
#print axioms MolecularDynamics.potentialHessian_quadratic_nonneg_of_posDef
#print axioms MolecularDynamics.linearizedHamiltonianQuadratic_nonneg_of_positive_hessian
#print axioms MolecularDynamics.realNormalMode
#print axioms MolecularDynamics.hasDerivAt_realNormalMode
#print axioms MolecularDynamics.realNormalMode_eq_linearExponentialFlow
#print axioms MolecularDynamics.mechanicalNormalMode_pair
#print axioms MolecularDynamics.hasDerivAt_mechanicalNormalMode
#print axioms MolecularDynamics.IsConstantVariationalSolution
#print axioms MolecularDynamics.linearExponentialFlow_isConstantVariationalSolution
#print axioms MolecularDynamics.constantVariationalSolution_unique
#print axioms MolecularDynamics.matrixExponential_zero
#print axioms MolecularDynamics.matrixExponential_add_of_commute
#print axioms MolecularDynamics.matrixExponential_neg
#print axioms MolecularDynamics.matrixExponentialFlow_realEigenmode
#print axioms MolecularDynamics.matrixExponentialFlow_diagonal
#print axioms MolecularDynamics.matrixExponential_conjugate
#print axioms MolecularDynamics.upperTriangularMatrix
#print axioms MolecularDynamics.upperTriangularFlow
#print axioms MolecularDynamics.hasDerivAt_positionPair
#print axioms MolecularDynamics.hasDerivAt_upperTriangularFlow
#print axioms MolecularDynamics.matrixExponentialFlow_upperTriangular
#print axioms MolecularDynamics.twoBodyCenterOfMass
#print axioms MolecularDynamics.twoBodySeparation
#print axioms MolecularDynamics.twoBodyCenterVelocity
#print axioms MolecularDynamics.twoBodyRelativeVelocity
#print axioms MolecularDynamics.twoBody_reconstruct_first
#print axioms MolecularDynamics.twoBody_reconstruct_second
#print axioms MolecularDynamics.twoBody_center_roundtrip
#print axioms MolecularDynamics.twoBody_separation_roundtrip
#print axioms MolecularDynamics.twoBody_equalMass_kinetic_decomposition
#print axioms MolecularDynamics.twoBodyRadialLagrangian
#print axioms MolecularDynamics.twoBody_equalMass_lagrangian_center_relative

#print axioms MolecularDynamics.eulerStep
#print axioms MolecularDynamics.eulerIterate
#print axioms MolecularDynamics.eulerIterate_zero
#print axioms MolecularDynamics.eulerIterate_succ
#print axioms MolecularDynamics.eulerIterate_zero_step
#print axioms MolecularDynamics.eulerMaxError
#print axioms MolecularDynamics.eulerMaxError_le
#print axioms MolecularDynamics.eulerStep_norm_sub_le
#print axioms MolecularDynamics.euler_localDefect_of_derivative_bound
#print axioms MolecularDynamics.exists_euler_trajectory_bounds
#print axioms MolecularDynamics.euler_convergence_on_open
#print axioms MolecularDynamics.theorem_2_1_euler

#print axioms MolecularDynamics.oneStepIterate
#print axioms MolecularDynamics.oneStepIterate_zero
#print axioms MolecularDynamics.oneStepIterate_succ
#print axioms MolecularDynamics.oneStepMaxError
#print axioms MolecularDynamics.oneStepMaxError_nonneg
#print axioms MolecularDynamics.oneStepMaxError_le
#print axioms MolecularDynamics.oneStep_error_recursion
#print axioms MolecularDynamics.oneStep_error_bound
#print axioms MolecularDynamics.oneStepMaxError_order_bound
#print axioms MolecularDynamics.oneStep_converges_of_consistency_stability

-- Section 2.3.3: actual wedge form, sign convention and matrix pullback.
#print axioms MolecularDynamics.SymplecticCoordinates
#print axioms MolecularDynamics.SymplecticCoordinateMatrix
#print axioms MolecularDynamics.textbookJ
#print axioms MolecularDynamics.textbookJ_eq_neg_mathlibJ
#print axioms MolecularDynamics.textbookJ_transpose
#print axioms MolecularDynamics.textbookJ_squared
#print axioms MolecularDynamics.textbookDq
#print axioms MolecularDynamics.textbookDp
#print axioms MolecularDynamics.textbookDq_apply
#print axioms MolecularDynamics.textbookDp_apply
#print axioms MolecularDynamics.textbookWedgeOneForms
#print axioms MolecularDynamics.textbookWedgeOneForms_apply
#print axioms MolecularDynamics.textbookSymplecticForm
#print axioms MolecularDynamics.textbookSymplecticForm_coordinates
#print axioms MolecularDynamics.textbookSymplecticForm_eq_sum_wedges
#print axioms MolecularDynamics.textbookSymplecticForm_self
#print axioms MolecularDynamics.textbookSymplecticForm_skew
#print axioms MolecularDynamics.textbookSymplecticPullback
#print axioms MolecularDynamics.textbookSymplecticPullback_apply
#print axioms MolecularDynamics.textbookSymplecticPullback_matrix
#print axioms MolecularDynamics.IsTextbookSymplectic
#print axioms MolecularDynamics.isTextbookSymplectic_iff_pullback
#print axioms MolecularDynamics.isTextbookSymplectic_iff_preserves_form
#print axioms MolecularDynamics.isTextbookSymplectic_iff_mathlib
#print axioms MolecularDynamics.isTextbookSymplectic_one
#print axioms MolecularDynamics.IsTextbookSymplectic.mul
#print axioms MolecularDynamics.IsTextbookSymplectic.det_eq_one
#print axioms MolecularDynamics.IsTextbookSymplectic.det_square
#print axioms MolecularDynamics.IsTextbookSymplectic.abs_det
#print axioms MolecularDynamics.IsTextbookSymplectic.inv
#print axioms MolecularDynamics.IsTextbookSymplectic.inv_formula

-- Sections 2.3.3--2.3.5: actual Jacobians and the genuine diffeomorphism group.
#print axioms MolecularDynamics.textbookJacobian
#print axioms MolecularDynamics.textbookJacobian_entry
#print axioms MolecularDynamics.textbookJacobian_mulVec
#print axioms MolecularDynamics.textbookJacobian_id
#print axioms MolecularDynamics.textbookJacobian_comp
#print axioms MolecularDynamics.IsTextbookSymplecticMap
#print axioms MolecularDynamics.isTextbookSymplecticMap_iff_preserves_form
#print axioms MolecularDynamics.isTextbookSymplecticMap_id
#print axioms MolecularDynamics.IsTextbookSymplecticMap.comp
#print axioms MolecularDynamics.IsTextbookSymplecticMap.jacobian_det_eq_one
#print axioms MolecularDynamics.textbookJacobian_equiv_symm
#print axioms MolecularDynamics.IsTextbookSymplecticEquiv
#print axioms MolecularDynamics.isTextbookSymplecticEquiv_refl
#print axioms MolecularDynamics.IsTextbookSymplecticEquiv.mul
#print axioms MolecularDynamics.IsTextbookSymplecticEquiv.symm
#print axioms MolecularDynamics.textbookSymplecticDiffeomorphismGroup
#print axioms MolecularDynamics.textbookSymplecticDiffeomorphismGroup_mem_iff
#print axioms MolecularDynamics.TextbookSymplecticDiffeomorphism
#print axioms MolecularDynamics.textbookSymplecticDiffeomorphism_mul_apply

-- Section 2.3.4: actual time-dependent variational derivatives and Hessian symmetry.
#print axioms MolecularDynamics.textbookHamiltonianHessian
#print axioms MolecularDynamics.textbookHamiltonianHessian_isSymm
#print axioms MolecularDynamics.hamiltonian_variational_matrix_cancellation
#print axioms MolecularDynamics.hasDerivWithinAt_hamiltonian_variational_form
#print axioms MolecularDynamics.hamiltonian_variational_form_constant
#print axioms MolecularDynamics.hamiltonian_variational_isSymplectic
#print axioms MolecularDynamics.hamiltonian_hessian_variational_isSymplectic
#print axioms MolecularDynamics.hamiltonian_flow_isSymplectic_of_variational_equation

-- Section 2.3.6: actual C2 potential, symplectic Euler and its genuine inverse.
#print axioms MolecularDynamics.textbookPositionProjection
#print axioms MolecularDynamics.textbookPotentialForce
#print axioms MolecularDynamics.contDiff_textbookPotentialForce
#print axioms MolecularDynamics.textbookPotentialForce_matrix_isSymm
#print axioms MolecularDynamics.textbookMomentumKick
#print axioms MolecularDynamics.textbookPositionDrift
#print axioms MolecularDynamics.textbookJacobian_momentumKick
#print axioms MolecularDynamics.contDiff_textbookMomentumKick
#print axioms MolecularDynamics.textbookJacobian_positionDrift
#print axioms MolecularDynamics.textbookPositionDrift_isSymplectic
#print axioms MolecularDynamics.textbookPotentialKick_isSymplectic
#print axioms MolecularDynamics.textbookSymplecticEuler
#print axioms MolecularDynamics.textbookSymplecticEuler_position
#print axioms MolecularDynamics.textbookSymplecticEuler_momentum
#print axioms MolecularDynamics.textbookSymplecticEuler_isSymplectic
#print axioms MolecularDynamics.textbookPositionProjection_momentumKick
#print axioms MolecularDynamics.textbookMomentumKick_neg_cancel
#print axioms MolecularDynamics.textbookPositionDrift_neg_cancel
#print axioms MolecularDynamics.textbookMomentumKickEquiv
#print axioms MolecularDynamics.textbookPositionDriftEquiv
#print axioms MolecularDynamics.textbookSymplecticEulerEquiv
#print axioms MolecularDynamics.textbookSymplecticEulerEquiv_apply
#print axioms MolecularDynamics.textbookSymplecticEulerEquiv_symm_apply
#print axioms MolecularDynamics.textbookSymplecticEulerEquiv_isSymplectic

-- Section 2.3.7: actual inverse maps and adjoint methods.
#print axioms MolecularDynamics.textbookAdjointMethod
#print axioms MolecularDynamics.textbookAdjointMethod_apply_eq_iff
#print axioms MolecularDynamics.textbookAdjointMethod_involutive
#print axioms MolecularDynamics.textbookAdjointMethod_isSymplectic
#print axioms MolecularDynamics.textbookFlowMethod
#print axioms MolecularDynamics.textbookFlowMethod_isSelfAdjoint
#print axioms MolecularDynamics.euler_negative_step_iff_backward
#print axioms MolecularDynamics.euler_adjoint_iff_backward
#print axioms MolecularDynamics.textbookAdjointSymplecticEuler
#print axioms MolecularDynamics.textbookAdjointSymplecticEuler_apply
#print axioms MolecularDynamics.textbookAdjointSymplecticEuler_position
#print axioms MolecularDynamics.textbookAdjointSymplecticEuler_momentum
#print axioms MolecularDynamics.textbookAdjointSymplecticEuler_isSymplectic

-- Section 2.4.1: actual local flows and Hamiltonian splitting error.
#print axioms MolecularDynamics.exists_splitting_localError_bound
#print axioms MolecularDynamics.exists_flow_splitting_localError_bound
#print axioms MolecularDynamics.textbookHamiltonianVectorField
#print axioms MolecularDynamics.contDiffOn_textbookHamiltonianVectorField
#print axioms MolecularDynamics.textbookHamiltonianVectorField_add
#print axioms MolecularDynamics.exists_hamiltonian_splitting_localError_bound

-- Main-text composition: printed85/PDF107.
#print axioms MolecularDynamics.textbookComposeMaps
#print axioms MolecularDynamics.textbookComposeMaps_isSymplectic
#print axioms MolecularDynamics.textbookComposeMethods
#print axioms MolecularDynamics.textbookComposeMethods_toMap
#print axioms MolecularDynamics.textbookAdjointMethod_comp
#print axioms MolecularDynamics.textbookSymmetricComposition
#print axioms MolecularDynamics.textbookSymmetricComposition_isSelfAdjoint
#print axioms MolecularDynamics.textbookComposeMethods_isSymplectic
#print axioms MolecularDynamics.textbookSymmetricComposition_isSymplectic

-- Main-text conjugacy and processing: printed88/PDF110.
#print axioms MolecularDynamics.textbookConjugateMap
#print axioms MolecularDynamics.textbookConjugateMap_iterate
#print axioms MolecularDynamics.textbook_conjugate_iterates
#print axioms MolecularDynamics.textbook_conjugate_iterates_tendsto_iff
#print axioms MolecularDynamics.textbookProcessedMethod
#print axioms MolecularDynamics.textbookProcessedIterate
#print axioms MolecularDynamics.textbookProcessedIterate_eq
#print axioms MolecularDynamics.textbookProcessedIterate_eq_of_conjugacy
#print axioms MolecularDynamics.textbookProcessedMaxError
#print axioms MolecularDynamics.textbookProcessedMaxError_eq_of_conjugacy

-- Main-text Lie/Poisson and actual commutator: printed100--105/PDF122--127.
#print axioms MolecularDynamics.textbookLieDerivative
#print axioms MolecularDynamics.hasDerivWithinAt_textbookLieDerivative
#print axioms MolecularDynamics.hasDerivAt_textbookLieDerivative
#print axioms MolecularDynamics.contDiff_textbookLieDerivative
#print axioms MolecularDynamics.hasDerivAt_textbookLieDerivative_second
#print axioms MolecularDynamics.textbookLieDerivative_field_add
#print axioms MolecularDynamics.textbookPoissonBracket
#print axioms MolecularDynamics.textbookPoissonBracket_coordinates
#print axioms MolecularDynamics.textbookPoissonBracket_skew
#print axioms MolecularDynamics.textbookPoissonBracket_self
#print axioms MolecularDynamics.textbookPoissonBracket_linear_right
#print axioms MolecularDynamics.textbookPoissonBracket_jacobi
#print axioms MolecularDynamics.textbookLieDerivative_hamiltonian_eq_poisson
#print axioms MolecularDynamics.hasDerivWithinAt_textbookPoissonBracket
#print axioms MolecularDynamics.textbookHamiltonian_energy_const_on_Icc
#print axioms MolecularDynamics.textbookPoissonBracket_linear_left
#print axioms MolecularDynamics.textbookHamiltonianLieDerivative_add
#print axioms MolecularDynamics.textbookHamiltonianLieDerivative_commutator

-- Genuine noncommuting formal-series coefficients: printed103--105/PDF125--127.
#print axioms MolecularDynamics.textbookFormalOperatorExponential
#print axioms MolecularDynamics.textbookFormalOperatorExponential_coeff
#print axioms MolecularDynamics.textbookFormalOperatorProduct_coeff_zero
#print axioms MolecularDynamics.textbookFormalOperatorProduct_coeff_one
#print axioms MolecularDynamics.textbookFormalOperatorProduct_coeff_two
#print axioms MolecularDynamics.textbookFormalOperatorProduct_coeff_three
#print axioms MolecularDynamics.textbookFormalOperatorDifference_coeff_two
#print axioms MolecularDynamics.textbookFormalOperatorDifference_coeff_three
#print axioms MolecularDynamics.textbookFormalZeroConstant_power_coeff_zero
#print axioms MolecularDynamics.textbookFormalZeroConstantExponential
#print axioms MolecularDynamics.textbookFormalZeroConstantExponential_coeff_stabilizes
#print axioms MolecularDynamics.textbookFormalModifiedExponential
#print axioms MolecularDynamics.textbookFormalModifiedExponential_coeff_zero
#print axioms MolecularDynamics.textbookFormalModifiedExponential_coeff_one
#print axioms MolecularDynamics.textbookFormalModifiedExponential_coeff_two
#print axioms MolecularDynamics.textbookFormalModifiedExponential_matches_product

-- Uniform finite modified-Hamiltonian bounds: printed114--115/PDF136--137.
#print axioms MolecularDynamics.textbookTruncatedHamiltonian
#print axioms MolecularDynamics.contDiffOn_textbookTruncatedHamiltonian
#print axioms MolecularDynamics.exists_compact_C1_lipschitz_constant
#print axioms MolecularDynamics.exists_uniform_textbookTruncatedHamiltonian_remainder
#print axioms MolecularDynamics.textbookTruncatedHamiltonian_difference_isBigO
#print axioms MolecularDynamics.exists_uniform_textbookTruncatedHamiltonian_lipschitz

-- Genuine ODE conservation and finite energy drift: printed115--116/PDF137--138.
#print axioms MolecularDynamics.oneStep_energy_telescoping
#print axioms MolecularDynamics.textbook_energy_drift_le_actual_defects
#print axioms MolecularDynamics.energy_step_count_power_factor
#print axioms MolecularDynamics.textbook_energy_drift_rate_of_flow_defect

-- Complete Lemma4.1 and the following finite constraint projection: printed159--160/PDF181--182.
#print axioms MolecularDynamics.textbookConstraintGradient
#print axioms MolecularDynamics.contDiff_textbookConstraintGradient
#print axioms MolecularDynamics.textbookConstrainedMomentum
#print axioms MolecularDynamics.textbookCotangentChart
#print axioms MolecularDynamics.lemma_4_1_coordinates
#print axioms MolecularDynamics.lemma_4_1
#print axioms MolecularDynamics.textbookMultiConstrainedMomentum
#print axioms MolecularDynamics.differentiableAt_textbookMultiConstrainedMomentum
#print axioms MolecularDynamics.textbookMultiConstrainedMomentum_preserves_pullback

-- Actual constrained Euler stage pullbacks: printed159--160/PDF181--182.
#print axioms MolecularDynamics.textbookProjectedEulerPreMomentum
#print axioms MolecularDynamics.textbookProjectedEulerPosition
#print axioms MolecularDynamics.textbookProjectedEulerChart
#print axioms MolecularDynamics.differentiableAt_textbookProjectedEulerPreMomentum
#print axioms MolecularDynamics.differentiableAt_textbookProjectedEulerPosition
#print axioms MolecularDynamics.textbookProjectedEulerChart_preserves_pullback

-- Explicit actual Gram solve and hidden constraint: printed159/PDF181.
#print axioms MolecularDynamics.textbookConstraintJacobian
#print axioms MolecularDynamics.textbookConstraintJacobian_mulVec
#print axioms MolecularDynamics.textbookConstraintJacobian_eq_actualDerivative
#print axioms MolecularDynamics.textbookInverseMassMatrix
#print axioms MolecularDynamics.textbookConstraintGram
#print axioms MolecularDynamics.textbookCotangentMultiplier
#print axioms MolecularDynamics.textbookCotangentProjection
#print axioms MolecularDynamics.textbookCotangentProjection_eq_gradient_sum
#print axioms MolecularDynamics.textbookCotangentProjection_hiddenConstraint
#print axioms MolecularDynamics.textbookCotangentProjection_constraint_derivative_zero

-- Actual reaction and solution-interval cotangent invariance: printed152--153/PDF174--175.
#print axioms MolecularDynamics.textbookConstraintCurvature
#print axioms MolecularDynamics.textbookConstrainedReactionMultiplier
#print axioms MolecularDynamics.textbookConstrainedReaction_balance
#print axioms MolecularDynamics.textbookConstrainedODE_cotangent_invariant

-- Actual Gram projection regularity and constructed final integrator stage.
#print axioms MolecularDynamics.contDiffAt_textbookConstraintJacobian
#print axioms MolecularDynamics.contDiffAt_textbookConstraintGram
#print axioms MolecularDynamics.contDiffAt_textbookCotangentMultiplier
#print axioms MolecularDynamics.contDiffAt_textbookCotangentProjection
#print axioms MolecularDynamics.textbookCotangentProjection_preserves_pullback
#print axioms MolecularDynamics.contDiffAt_textbookProjectedEulerPreMomentum
#print axioms MolecularDynamics.contDiffAt_textbookProjectedEulerPosition
#print axioms MolecularDynamics.textbookGramProjectedEulerChart
#print axioms MolecularDynamics.textbookGramProjectedEulerChart_hiddenConstraint_and_pullback

-- Physical positive masses and independent actual constraint gradients.
#print axioms MolecularDynamics.textbookConstraintJacobian_vecMul_injective
#print axioms MolecularDynamics.textbookInverseMassMatrix_posDef
#print axioms MolecularDynamics.textbookConstraintGram_posDef
#print axioms MolecularDynamics.textbookConstraintGram_det_pos
#print axioms MolecularDynamics.textbookConstraintGram_det_ne_zero
#print axioms MolecularDynamics.textbookCotangentProjection_hiddenConstraint_of_mass_and_independence
#print axioms MolecularDynamics.contDiffAt_textbookCotangentMultiplier_of_mass_and_independence
#print axioms MolecularDynamics.textbookConstrainedODE_cotangent_invariant_of_mass_and_independence

-- Genuine joint C2 solution variations, Hamiltonian Jacobian ODE and symplecticity.
#print axioms MolecularDynamics.textbookSolutionVariation
#print axioms MolecularDynamics.textbookSolutionVariation_hasDerivAt
#print axioms MolecularDynamics.textbookHamiltonianVectorField_fderiv_mulVec
#print axioms MolecularDynamics.textbookHamiltonianFlowJacobian_hasDerivAt
#print axioms MolecularDynamics.textbookHamiltonianFlow_isSymplectic_of_jointC2
#print axioms MolecularDynamics.textbookHamiltonianFlowJacobian_det_eq_one_of_jointC2

-- Genuine Hamiltonian divergence, ODE injectivity and Lebesgue image volume.
#print axioms MolecularDynamics.textbookHamiltonianVectorField_jacobian
#print axioms MolecularDynamics.textbookHamiltonianVectorField_divergence_zero
#print axioms MolecularDynamics.textbookC1SolutionFamily_injective
#print axioms MolecularDynamics.textbookHamiltonianFlow_injective_of_jointC2
#print axioms MolecularDynamics.textbookHamiltonianFlow_measurable_image_of_jointC2
#print axioms MolecularDynamics.textbookHamiltonianFlow_volume_image_of_jointC2

-- Real matrix determinant ODE and actual divergence-free Liouville volume.
#print axioms MolecularDynamics.textbookCoordinateJacobian
#print axioms MolecularDynamics.textbookCoordinateJacobian_entry
#print axioms MolecularDynamics.textbookCoordinateJacobian_mulVec
#print axioms MolecularDynamics.textbookMatrixDet_hasDerivAt_of_linearODE
#print axioms MolecularDynamics.textbookSolutionFamilyJacobian_hasDerivAt
#print axioms MolecularDynamics.textbookDivergenceFreeFlowJacobian_det_eq_one_of_jointC2
#print axioms MolecularDynamics.textbookDivergenceFreeFlow_measurable_image_of_jointC2
#print axioms MolecularDynamics.textbookDivergenceFreeFlow_volume_image_of_jointC2

-- Constructed real C1 Gram reaction for the constrained-flow proof.
#print axioms MolecularDynamics.contDiffAt_textbookConstraintGram_inverse
#print axioms MolecularDynamics.contDiffAt_textbookConstraintCurvature
#print axioms MolecularDynamics.contDiffAt_textbookConstrainedReactionMultiplier
#print axioms MolecularDynamics.contDiffAt_textbookConstrainedReactionMultiplier_of_mass_and_independence
#print axioms MolecularDynamics.textbookConstrainedPhaseVectorField
#print axioms MolecularDynamics.contDiffAt_textbookConstrainedPhaseVectorField
#print axioms MolecularDynamics.contDiffAt_textbookConstrainedPhaseVectorField_of_mass_and_independence

-- Actual initial constraints and true constrained ODE give restricted flow symplecticity.
#print axioms MolecularDynamics.textbookConstrainedAcceleration_pullback_zero
#print axioms MolecularDynamics.textbookConstrainedFlow_pullback_constant_of_jointC2
#print axioms MolecularDynamics.textbookConstrainedFlow_pullback_constant_of_mass_and_independence

-- Actual Brownian quadratic variation, textbook Proposition 6.2.
#print axioms MolecularDynamics.textbookCenteredGaussian_secondMoment
#print axioms MolecularDynamics.textbookCenteredGaussian_fourthMoment
#print axioms MolecularDynamics.textbookCenteredGaussian_square_memLp
#print axioms MolecularDynamics.textbookCenteredGaussian_square_variance
#print axioms MolecularDynamics.textbookWienerTime
#print axioms MolecularDynamics.textbookWienerIncrement
#print axioms MolecularDynamics.textbookWienerQuadraticSum
#print axioms MolecularDynamics.textbookWienerIncrement_hasLaw
#print axioms MolecularDynamics.textbookWienerIncrement_independent
#print axioms MolecularDynamics.textbookWienerQuadraticSum_integral
#print axioms MolecularDynamics.textbookWienerQuadraticSum_variance
#print axioms MolecularDynamics.textbookWienerQuadraticSum_meanSquareError
#print axioms MolecularDynamics.textbookWienerQuadraticSum_meanSquare_tendsto

-- Genuine finite Wiener integrals and the self integral limit.
#print axioms MolecularDynamics.textbookWienerWeightedSum
#print axioms MolecularDynamics.textbookWienerWeightedVariance
#print axioms MolecularDynamics.textbookWienerWeightedSum_hasGaussianLaw
#print axioms MolecularDynamics.textbookWienerWeightedSum_integral
#print axioms MolecularDynamics.textbookWienerWeightedSum_variance
#print axioms MolecularDynamics.textbookWienerWeightedSum_hasLaw
#print axioms MolecularDynamics.textbookWienerWeightedSum_difference_secondMoment
#print axioms MolecularDynamics.textbookWienerSelfItoSum
#print axioms MolecularDynamics.textbookWienerSelfItoSum_identity
#print axioms MolecularDynamics.textbookWienerSelfItoLimit_memLp
#print axioms MolecularDynamics.textbookWienerSelfItoSum_memLp
#print axioms MolecularDynamics.textbookWienerSelfItoSum_meanSquareError
#print axioms MolecularDynamics.textbookWienerSelfItoSum_meanSquare_tendsto
#print axioms MolecularDynamics.textbookWienerSelfItoIntegral_exists

-- Real Markov composition and unique invariant distribution swap.
#print axioms MolecularDynamics.textbookUniqueInvariantProbability
#print axioms MolecularDynamics.textbookKernelInvariant_swap
#print axioms MolecularDynamics.textbookKernelComposition_iterate
#print axioms MolecularDynamics.textbookInvariantDistributionSwap_left
#print axioms MolecularDynamics.textbookInvariantDistributionSwap

-- Actual linear thermostat fields and derivative bracket closure.
#print axioms MolecularDynamics.textbookThermostatPhase
#print axioms MolecularDynamics.textbookThermostatF
#print axioms MolecularDynamics.textbookThermostatG
#print axioms MolecularDynamics.textbookThermostatC
#print axioms MolecularDynamics.textbookThermostatD
#print axioms MolecularDynamics.textbookThermostatF_apply
#print axioms MolecularDynamics.textbookThermostatG_apply
#print axioms MolecularDynamics.textbookThermostatC_apply
#print axioms MolecularDynamics.textbookThermostatD_apply
#print axioms MolecularDynamics.textbookThermostatLinearField_lieBracket
#print axioms MolecularDynamics.textbookThermostat_lie_F_G
#print axioms MolecularDynamics.textbookThermostat_lie_F_C
#print axioms MolecularDynamics.textbookThermostat_lie_D_F
#print axioms MolecularDynamics.textbookThermostatLieSpan
#print axioms MolecularDynamics.textbookThermostatLieSpan_vectorField_closed
#print axioms MolecularDynamics.textbookThermostat_C_D_mem_lieSpan

-- Genuine spectral modes, actual vector independence and pointwise spanning.
#print axioms MolecularDynamics.textbookThermostatEigenCoordinates
#print axioms MolecularDynamics.textbookThermostatSpectralPhase
#print axioms MolecularDynamics.textbookThermostatEigenCoordinates_eq_dotProduct
#print axioms MolecularDynamics.textbookThermostatEigenCoordinates_intertwine
#print axioms MolecularDynamics.textbookThermostatEigenCoordinates_power
#print axioms MolecularDynamics.textbookThermostat_C_coordinates
#print axioms MolecularDynamics.textbookThermostat_D_coordinates
#print axioms MolecularDynamics.textbookThermostatModeDomain
#print axioms MolecularDynamics.textbookThermostatModeDomain_isOpen
#print axioms MolecularDynamics.textbookThermostatModal_coefficients_eq_zero
#print axioms MolecularDynamics.textbookThermostatFamily
#print axioms MolecularDynamics.textbookThermostatFamily_linearIndependent
#print axioms MolecularDynamics.textbookThermostatFamily_span_eq_top
#print axioms MolecularDynamics.textbookThermostatLieSpan_pointwise_span_eq_top

-- Actual iterated brackets, smooth coefficient closure, thermostat lift and NHL fields.
#print axioms MolecularDynamics.textbookIteratedBracket
#print axioms MolecularDynamics.textbookIteratedBracket_contDiff
#print axioms MolecularDynamics.textbookBracketPointSpan
#print axioms MolecularDynamics.textbookHormanderAt
#print axioms MolecularDynamics.textbookSmoothBracketModule
#print axioms MolecularDynamics.textbookSmoothBracketModule_generator_mem
#print axioms MolecularDynamics.textbookSmoothBracketModule_contDiff
#print axioms MolecularDynamics.textbookSmoothBracketModule_smooth_smul_mem
#print axioms MolecularDynamics.textbookSmoothBracketModule_eval_mem
#print axioms MolecularDynamics.textbookSmoothBracketModule_bracket_mem
#print axioms MolecularDynamics.textbookThermostatLift
#print axioms MolecularDynamics.textbookThermostatDrift
#print axioms MolecularDynamics.textbookThermostatNoise
#print axioms MolecularDynamics.textbookThermostatSeed
#print axioms MolecularDynamics.textbookThermostatSeed_contDiff
#print axioms MolecularDynamics.textbookThermostatLift_lieBracket
#print axioms MolecularDynamics.textbookThermostatDrift_noise_bracket
#print axioms MolecularDynamics.textbookThermostatLift_mem_module
#print axioms MolecularDynamics.textbookThermostatLift_iterated_mem_module
#print axioms MolecularDynamics.textbookThermostatHormanderLift
#print axioms MolecularDynamics.textbookThermostatPhysical_hormander
#print axioms MolecularDynamics.textbookNHLFeedback
#print axioms MolecularDynamics.textbookNHLFeedback_contDiff
#print axioms MolecularDynamics.textbookNHLDrift
#print axioms MolecularDynamics.textbookNHL_domain_isOpen
#print axioms MolecularDynamics.textbookNHLSeed_contDiff
#print axioms MolecularDynamics.textbookNHLDrift_apply
#print axioms MolecularDynamics.textbookNHL_hormander
#print axioms MolecularDynamics.textbookNHL_hormander_physicalNoise
#print axioms MolecularDynamics.textbookIteratedBracket.seed
#print axioms MolecularDynamics.textbookIteratedBracket.bracket
#print axioms MolecularDynamics.textbookIteratedBracket.rec

-- Actual zero eigenmode domain and pathwise invariance.
#print axioms MolecularDynamics.textbookNHLZeroMode
#print axioms MolecularDynamics.textbookThermostatModeDomain_eq_compl_zeroModes
#print axioms MolecularDynamics.textbookNHL_zeroMode_invariant

#print axioms MolecularDynamics.textbookWienerMidpointSum
#print axioms MolecularDynamics.textbookWienerMidpointCorrection
#print axioms MolecularDynamics.textbookWienerMidpointCorrection_memLp
#print axioms MolecularDynamics.textbookWienerMidpointCorrection_integral
#print axioms MolecularDynamics.textbookWienerMidpointCorrection_variance
#print axioms MolecularDynamics.textbookWienerMidpointSum_identity
#print axioms MolecularDynamics.textbookWienerMidpointLimit_memLp
#print axioms MolecularDynamics.textbookWienerMidpointSum_memLp
#print axioms MolecularDynamics.textbookWienerMidpointSum_meanSquareError
#print axioms MolecularDynamics.textbookWienerMidpointSum_meanSquare_tendsto
#print axioms MolecularDynamics.textbookWienerSelfStratonovichIntegral_exists

#print axioms MolecularDynamics.textbookWienerWeightedSum_refine
#print axioms MolecularDynamics.textbookWienerWeightedSum_twoGrid_secondMoment
#print axioms MolecularDynamics.textbookWienerDeterministicSum
#print axioms MolecularDynamics.textbookWienerDeterministicSum_memLp
#print axioms MolecularDynamics.textbookWienerTime_mem_Icc
#print axioms MolecularDynamics.textbookWienerDeterministicSum_twoGrid_meanSquare_le
#print axioms MolecularDynamics.textbookWienerDeterministicLp
#print axioms MolecularDynamics.textbookWienerDeterministicLp_dist_le
#print axioms MolecularDynamics.textbookWienerDeterministicLp_cauchySeq
#print axioms MolecularDynamics.textbookWienerDeterministicIntegral_exists_of_lipschitz
#print axioms MolecularDynamics.textbookWienerDeterministicIntegral_exists

#print axioms MolecularDynamics.textbookWienerDeterministicVariance
#print axioms MolecularDynamics.textbookWienerDeterministicVariance_coe
#print axioms MolecularDynamics.textbookWienerDeterministicFiniteVariance_tendsto
#print axioms MolecularDynamics.textbookWienerDeterministicIntegral_hasLaw
#print axioms MolecularDynamics.textbookWienerDeterministicIto_proposition63

#print axioms MolecularDynamics.textbookDivergence
#print axioms MolecularDynamics.textbookLiouvilleStationary
#print axioms MolecularDynamics.textbookDivergence_density
#print axioms MolecularDynamics.textbookDivergence_add
#print axioms MolecularDynamics.textbookDivergence_sub
#print axioms MolecularDynamics.textbookDivergence_const_smul
#print axioms MolecularDynamics.textbookDivergence_prod
#print axioms MolecularDynamics.textbookDivergence_conjugate
#print axioms MolecularDynamics.textbookLiouvilleStationary_lift_idle
#print axioms MolecularDynamics.textbookLiouvilleStationary_conjugate
#print axioms MolecularDynamics.textbookLiouvilleStationary_add_sub
#print axioms MolecularDynamics.textbookLiouvilleStationary_const_mul
#print axioms MolecularDynamics.textbookHamiltonianGibbsWeight
#print axioms MolecularDynamics.textbookHamiltonianGibbsWeight_pos
#print axioms MolecularDynamics.textbookHamiltonianGibbsWeight_stationary
#print axioms MolecularDynamics.textbookHamiltonianGibbsDensity
#print axioms MolecularDynamics.textbookHamiltonianGibbsDensity_stationary
#print axioms MolecularDynamics.textbookHamiltonianGibbsDensity_pos
#print axioms MolecularDynamics.textbookSingleThermostatField
#print axioms MolecularDynamics.textbookCombinedThermostatField
#print axioms MolecularDynamics.textbookThermostatProductDensity
#print axioms MolecularDynamics.textbookThermostatProductDensity_stationary
#print axioms MolecularDynamics.textbookThermostatProductDensity_nonneg
#print axioms MolecularDynamics.textbookThermostats_additive_proposition81

#print axioms MolecularDynamics.textbookStationaryDensityFlow_weightedJacobian
#print axioms MolecularDynamics.textbookStationaryDensityFlow_abs_weightedJacobian
#print axioms MolecularDynamics.textbookDensityMeasure
#print axioms MolecularDynamics.textbookStationaryDensityFlow_measure_image
#print axioms MolecularDynamics.textbookStationaryDensityFlow_measure_map
#print axioms MolecularDynamics.textbookThermostatProductDensity_measure_eq_prod
#print axioms MolecularDynamics.textbookThermostatProductDensity_probability
#print axioms MolecularDynamics.textbookThermostats_additive_invariant_probability

#print axioms MolecularDynamics.textbookFormalOperatorLogarithm
#print axioms MolecularDynamics.textbookFormalOperatorLogarithm_coeff_stabilizes
#print axioms MolecularDynamics.textbookFormalOperatorLogarithm_coeff_one
#print axioms MolecularDynamics.textbookFormalOperatorLogarithm_coeff_two
#print axioms MolecularDynamics.textbookFormalOperatorLogarithm_coeff_three
#print axioms MolecularDynamics.textbookFormalOperatorLogarithm_coeff_four
#print axioms MolecularDynamics.textbookSymmetricOperatorComposition
#print axioms MolecularDynamics.textbookOperatorCommutator
#print axioms MolecularDynamics.textbookSymmetricOperatorCorrection
#print axioms MolecularDynamics.textbookSymmetricOperatorComposition_coeff_zero
#print axioms MolecularDynamics.textbookSymmetricOperatorComposition_coeff_one
#print axioms MolecularDynamics.textbookSymmetricOperatorComposition_coeff_two
#print axioms MolecularDynamics.textbookSymmetricOperatorComposition_coeff_three
#print axioms MolecularDynamics.textbookSymmetricOperatorComposition_coeff_four
#print axioms MolecularDynamics.textbookSymmetricModifiedGenerator
#print axioms MolecularDynamics.textbookSymmetricModifiedGenerator_coeff_zero
#print axioms MolecularDynamics.textbookSymmetricModifiedGenerator_coeff_one
#print axioms MolecularDynamics.textbookSymmetricModifiedGenerator_coeff_two
#print axioms MolecularDynamics.textbookSymmetricModifiedGenerator_coeff_three
#print axioms MolecularDynamics.textbookSymmetricModifiedGenerator_formal_proposition71
#print axioms MolecularDynamics.textbookFormalLogarithmExponential
#print axioms MolecularDynamics.textbookFormalLogarithmExponential_coeff_matches
#print axioms MolecularDynamics.textbookSymmetricModifiedGenerator_logarithm
#print axioms MolecularDynamics.textbookSymmetricGeneratorExponential
#print axioms MolecularDynamics.textbookSymmetricGeneratorExponential_coeff_matches
