import Lean
import MolecularDynamicsFormalization

-- Keep explicit dependency evidence for the current key textbook theorem.
-- Add corresponding commands when new key theorems enter the formal library.
#print axioms MolecularDynamics.nBodyKineticEnergy_nonneg
#print axioms MolecularDynamics.unflatten_flatten
#print axioms MolecularDynamics.flatten_unflatten
#print axioms MolecularDynamics.coordinateMassesOfParticles_pos_iff
#print axioms MolecularDynamics.nBodyKineticEnergy_particle_eq
#print axioms MolecularDynamics.diagonalMassMatrix_posDef_iff
#print axioms MolecularDynamics.diagonalMassMatrix_inv_eq
#print axioms MolecularDynamics.diagonalMassMatrix_inv_mulVec
#print axioms MolecularDynamics.massOperator_velocityOperator
#print axioms MolecularDynamics.velocityOperator_massOperator
#print axioms MolecularDynamics.isMechanicalSolutionOn_iff_components
#print axioms MolecularDynamics.momentum_eq_mass_deriv_position
#print axioms MolecularDynamics.hasDerivAt_deriv_position
#print axioms MolecularDynamics.solution_nBodyEquationAt
#print axioms MolecularDynamics.solution_nBodyEquationAt_of_differentiable
#print axioms MolecularDynamics.solution_hasGradientAt_potential
#print axioms MolecularDynamics.newtonTrajectory_to_mechanicalSolution
#print axioms MolecularDynamics.freeParticle_localIVP
#print axioms MolecularDynamics.IsLocalMechanicalIVP.initial_mem

#print axioms MolecularDynamics.momentumKineticEnergy_eq_inner
#print axioms MolecularDynamics.momentumKineticEnergy_massOperator
#print axioms MolecularDynamics.massHamiltonian_massOperator
#print axioms MolecularDynamics.massHamiltonian_particle
#print axioms MolecularDynamics.massHamiltonian_velocityOperator
#print axioms MolecularDynamics.hasGradientAt_momentumKineticEnergy
#print axioms MolecularDynamics.gradient_momentumKineticEnergy_eq_velocityOperator
#print axioms MolecularDynamics.gradient_position_slice
#print axioms MolecularDynamics.hasGradientAt_position_slice
#print axioms MolecularDynamics.hamiltonianVectorField_eq

#print axioms MolecularDynamics.mechanical_energy_hasDerivAt_zero
#print axioms MolecularDynamics.mechanical_energy_const_on_Ioo
#print axioms MolecularDynamics.mechanicalVectorField_contDiffAt
#print axioms MolecularDynamics.exists_localMechanicalIVP_open_of_force_contDiffAt
#print axioms MolecularDynamics.mechanicalSolution_unique_on_Ioo
#print axioms MolecularDynamics.mechanicalSolution_eventually_unique_of_contDiffAt
#print axioms MolecularDynamics.totalMomentumCoordinate_hasDerivAt_zero
#print axioms MolecularDynamics.totalMomentumCoordinate_const_on_Ioo
#print axioms MolecularDynamics.strictPotentialMin_mechanicalEquilibrium
#print axioms MolecularDynamics.momentumKineticEnergy_nonneg
#print axioms MolecularDynamics.momentum_norm_sq_le
#print axioms MolecularDynamics.momentum_norm_le_of_energy
#print axioms MolecularDynamics.momentum_norm_lt_of_kineticEnergy
#print axioms MolecularDynamics.isCompact_phaseEnergySublevel
#print axioms MolecularDynamics.mechanicalSolution_below_barrier_stays_in_ball
#print axioms MolecularDynamics.mechanicalSolution_phase_dist_lt
#print axioms MolecularDynamics.exists_rightEndpointLimit_of_lipschitzOnWith
#print axioms MolecularDynamics.exists_rightEndpointLimit_mem_of_lipschitzOnWith
#print axioms MolecularDynamics.mechanicalSolution_lipschitzOnWith_of_field_bound
#print axioms MolecularDynamics.mechanicalSolution_has_rightEndpointLimit_of_field_bound
#print axioms MolecularDynamics.mechanicalSolution_has_rightEndpointLimit_of_compact
#print axioms MolecularDynamics.mechanicalSolution_unique_on_preconnected_of_contDiffAt
#print axioms MolecularDynamics.mechanicalSolution_glue_on_Ioo
#print axioms MolecularDynamics.hasDerivWithinAt_rightEndpoint_of_continuousOn
#print axioms MolecularDynamics.exists_localODE_matching_rightEndpoint
#print axioms MolecularDynamics.mechanicalSolution_extend_of_rightEndpointLimit
#print axioms MolecularDynamics.mechanicalSolution_extend_of_force_contDiffAt
#print axioms MolecularDynamics.mechanicalSolution_extend_of_compact

#print axioms MolecularDynamics.strictOn_iff_punctured
#print axioms MolecularDynamics.strictUniv_iff
#print axioms MolecularDynamics.strictOn_isLocalMinOn
#print axioms MolecularDynamics.compact_positive_gap
#print axioms MolecularDynamics.fixed_sphere_barrier
#print axioms MolecularDynamics.open_domain_barrier
#print axioms MolecularDynamics.energy_excludes_sphere
#print axioms MolecularDynamics.energy_below_barrier_excludes_sphere
#print axioms MolecularDynamics.conserved_trajectory_stays_in_ball
#print axioms MolecularDynamics.conserved_trajectory_below_barrier_stays_in_ball
#print axioms MolecularDynamics.conserved_trajectory_center_below_barrier_stays_in_ball
#print axioms MolecularDynamics.open_domain_energy_confinement
#print axioms MolecularDynamics.zero_dimensional_sphere_empty
#print axioms MolecularDynamics.zero_dimensional_barrier
#print axioms MolecularDynamics.zero_dimensional_strict_min
#print axioms MolecularDynamics.singleton_relative_strict
#print axioms MolecularDynamics.singleton_sphere_not_subset
#print axioms MolecularDynamics.quartic_strict_min
#print axioms MolecularDynamics.quartic_sphere_barrier
#print axioms MolecularDynamics.constant_local_min
#print axioms MolecularDynamics.constant_not_strict
#print axioms MolecularDynamics.endpoint_strict_radius
#print axioms MolecularDynamics.endpoint_potential_continuous
#print axioms MolecularDynamics.endpoint_no_barrier
#print axioms MolecularDynamics.quartic_potential_continuous

-- Audit all declarations in the imported project namespace, including private
-- declarations after removing their generated private-name prefix.
open Lean Elab Command in
run_cmd do
  let allowed : Array Name := #[`propext, `Classical.choice, `Quot.sound]
  let env ← getEnv
  let names := env.constants.fold (init := #[]) fun names name _ =>
    if (`MolecularDynamics).isPrefixOf (privateToUserName name) then
      names.push name
    else
      names
  if names.isEmpty then
    throwError "No project declarations were found in the imported environment."
  for name in names do
    let dependencies ← collectAxioms name
    for dependency in dependencies do
      unless allowed.contains dependency do
        throwError "{name} depends on a disallowed logical dependency: {dependency}"
  logInfo m!"Dependency audit passed for {names.size} imported project declarations; allowed: {allowed}."
#print axioms MolecularDynamics.exists_glued_function_of_compatible
#print axioms MolecularDynamics.exists_mechanicalSolutionOn_iUnion
#print axioms MolecularDynamics.exists_globalMechanicalSolution_of_local_compact_confinement
#print axioms MolecularDynamics.exists_globalMechanicalIVP_of_energy_barrier
#print axioms MolecularDynamics.gradient_contDiffAt_of_potential_contDiffAt_two
#print axioms MolecularDynamics.strictPotentialMin_exists_future_bound
#print axioms MolecularDynamics.strictPotentialMin_futureStable
#print axioms MolecularDynamics.strictPotentialMin_futureStable_of_potential_contDiffAt_two
#print axioms MolecularDynamics.product_dist_le_phaseEuclideanDistance
#print axioms MolecularDynamics.phaseEuclideanDistance_le_two_mul_dist
#print axioms MolecularDynamics.IsFutureMechanicalStable.euclidean
#print axioms MolecularDynamics.strictPotentialMin_futureStableEuclidean_of_potential_contDiffAt_two
#print axioms MolecularDynamics.strictPotentialMin_futureStableEuclidean_of_smooth
#print axioms MolecularDynamics.nBodyKineticEnergy_eq_inner
#print axioms MolecularDynamics.hasGradientAt_nBodyKineticEnergy
#print axioms MolecularDynamics.hasGradientAt_massLagrangian_velocity
#print axioms MolecularDynamics.hasGradientAt_massLagrangian_position
#print axioms MolecularDynamics.mechanicalSolution_eulerLagrange
#print axioms MolecularDynamics.eulerLagrange_to_mechanicalSolution
#print axioms MolecularDynamics.massLagrangian_coordinateChange
#print axioms MolecularDynamics.hasDerivAt_coordinateChange
#print axioms MolecularDynamics.generalizedMassMatrix_posDef
#print axioms MolecularDynamics.generalizedMassMatrix_isUnit
#print axioms MolecularDynamics.massHamiltonian_legendre_gap
#print axioms MolecularDynamics.legendre_objective_le_massHamiltonian
#print axioms MolecularDynamics.legendre_objective_attains_massHamiltonian
#print axioms MolecularDynamics.nBodyKineticEnergy_eq_zero_iff
#print axioms MolecularDynamics.legendre_objective_eq_massHamiltonian_iff
#print axioms MolecularDynamics.massHamiltonian_eq_legendre_sup
#print axioms MolecularDynamics.mechanicalSolution_translate_on_Ioi
#print axioms MolecularDynamics.futureMechanicalFlow_add
#print axioms MolecularDynamics.futureMechanicalFlow_commute
#print axioms MolecularDynamics.futureMechanicalFlow_energy
#print axioms MolecularDynamics.futureMechanicalFlow_injOn
#print axioms MolecularDynamics.exists_futureMechanicalFlow_of_energy_barrier
#print axioms MolecularDynamics.massHamiltonian_momentumReflection
#print axioms MolecularDynamics.mechanicalSolution_time_reverse_on_Iio
#print axioms MolecularDynamics.exists_globalMechanicalIVP_of_energy_barrier_two_sided
#print axioms MolecularDynamics.mechanicalSolution_translate_on_univ
#print axioms MolecularDynamics.mechanicalSolution_energy_on_univ
#print axioms MolecularDynamics.globalMechanicalFlow_add
#print axioms MolecularDynamics.globalMechanicalFlow_inverse
#print axioms MolecularDynamics.globalMechanicalFlow_commute
#print axioms MolecularDynamics.globalMechanicalFlow_bijOn
#print axioms MolecularDynamics.globalMechanicalFlow_energy
#print axioms MolecularDynamics.exists_globalMechanicalFlow_of_energy_barrier
#print axioms MolecularDynamics.harmonicFlow_isMechanicalSolution
#print axioms MolecularDynamics.harmonicFlow_isGlobalFlow
#print axioms MolecularDynamics.harmonicFlow_continuous
#print axioms MolecularDynamics.harmonicFlow_add
#print axioms MolecularDynamics.harmonicFlow_inverse
#print axioms MolecularDynamics.harmonicContinuousFlow
#print axioms MolecularDynamics.hasGradientAt_harmonicPotential
#print axioms MolecularDynamics.harmonicFlow_energy
#print axioms MolecularDynamics.freeParticleFlow_isMechanicalSolution
#print axioms MolecularDynamics.freeParticleFlow_isGlobalFlow
#print axioms MolecularDynamics.freeParticleFlow_continuous
#print axioms MolecularDynamics.freeParticleFlow_add
#print axioms MolecularDynamics.freeParticleContinuousFlow
#print axioms MolecularDynamics.freeParticleFlow_energy
#print axioms MolecularDynamics.hasDerivAt_linearExponentialFlow
#print axioms MolecularDynamics.linearExponentialFlow_add
#print axioms MolecularDynamics.linearExponentialFlow_continuous
#print axioms MolecularDynamics.linearContinuousFlow
#print axioms MolecularDynamics.linearExponentialFlow_inverse
#print axioms MolecularDynamics.hasDerivAt_linearExponentialFlow_initial_time
#print axioms MolecularDynamics.linearExponentialFlow_unique
#print axioms MolecularDynamics.linearExponentialOperator_series
#print axioms MolecularDynamics.matrixExponentialFlow_eq
#print axioms MolecularDynamics.hasDerivAt_matrixExponentialFlow
#print axioms MolecularDynamics.hasDerivAt_matrixExponentialFlow_initial_time
#print axioms MolecularDynamics.matrixExponentialFlow_unique
#print axioms MolecularDynamics.matrixContinuousFlow
#print axioms MolecularDynamics.matrixExponential_series
#print axioms MolecularDynamics.hasDerivAt_realEigenmode
#print axioms MolecularDynamics.linearExponentialFlow_realEigenmode
#print axioms MolecularDynamics.linearExponentialFlow_realSpectral_sum
#print axioms MolecularDynamics.linearExponentialFlow_realEigenbasis
#print axioms MolecularDynamics.hasDerivAt_complexEigenmode
#print axioms MolecularDynamics.complexExponentialFlow_eigenmode
#print axioms MolecularDynamics.complexExponentialFlow_spectral_sum
#print axioms MolecularDynamics.complexExponentialFlow_eigenbasis
#print axioms MolecularDynamics.hasDerivAt_complexExponentialFlow
#print axioms MolecularDynamics.complexContinuousFlow
#print axioms MolecularDynamics.complexEigenbasis_coefficients_unique
#print axioms MolecularDynamics.linearExponentialFlow_intertwine
#print axioms MolecularDynamics.linearExponentialFlow_fixed_clm
#print axioms MolecularDynamics.realMatrix_conjugation_commute
#print axioms MolecularDynamics.realMatrix_complexFlow_isReal
#print axioms MolecularDynamics.realMatrix_complexSpectral_sum_isReal
#print axioms MolecularDynamics.basisColumnMatrix_mulVec
#print axioms MolecularDynamics.basisColumnMatrix_mulVec_repr
#print axioms MolecularDynamics.basisColumnMatrix_isUnit
#print axioms MolecularDynamics.basisColumnMatrix_inverse_coefficients
