import MolecularDynamicsFormalization
#check MolecularDynamics.Chapter02Review.coordinateVerlet
#print axioms MolecularDynamics.Chapter02Review.coordinateVerlet
#check MolecularDynamics.Chapter02Review.localHamiltonianStructures_statement
#print axioms MolecularDynamics.Chapter02Review.localHamiltonianStructures_statement
#check MolecularDynamics.Chapter02Review.takahashiOrder_statement
#print axioms MolecularDynamics.Chapter02Review.takahashiOrder_statement
#check MolecularDynamics.Chapter02Review.takahashiPotential
#print axioms MolecularDynamics.Chapter02Review.takahashiPotential
#check MolecularDynamics.Chapter03Review.actualFlowNearCompact
#print axioms MolecularDynamics.Chapter03Review.actualFlowNearCompact
#check MolecularDynamics.Chapter03Review.affineInvariant
#print axioms MolecularDynamics.Chapter03Review.affineInvariant
#check MolecularDynamics.Chapter03Review.analyticBEA_statement
#print axioms MolecularDynamics.Chapter03Review.analyticBEA_statement
#check MolecularDynamics.Chapter03Review.bch4_statement
#print axioms MolecularDynamics.Chapter03Review.bch4_statement
#check MolecularDynamics.Chapter03Review.bchHamiltonian3
#print axioms MolecularDynamics.Chapter03Review.bchHamiltonian3
#check MolecularDynamics.Chapter03Review.bchHamiltonianMatching_statement
#print axioms MolecularDynamics.Chapter03Review.bchHamiltonianMatching_statement
#check MolecularDynamics.Chapter03Review.collisionComposition
#print axioms MolecularDynamics.Chapter03Review.collisionComposition
#check MolecularDynamics.Chapter03Review.collisionDefectZero_proved
#print axioms MolecularDynamics.Chapter03Review.collisionDefectZero_proved
#check MolecularDynamics.Chapter03Review.collisionDefectZero_statement
#print axioms MolecularDynamics.Chapter03Review.collisionDefectZero_statement
#check MolecularDynamics.Chapter03Review.collisionQuadraticPath
#print axioms MolecularDynamics.Chapter03Review.collisionQuadraticPath
#check MolecularDynamics.Chapter03Review.collisionQuartic_proved
#print axioms MolecularDynamics.Chapter03Review.collisionQuartic_proved
#check MolecularDynamics.Chapter03Review.collisionQuartic_statement
#print axioms MolecularDynamics.Chapter03Review.collisionQuartic_statement
#check MolecularDynamics.Chapter03Review.collisionRegularity_statement
#print axioms MolecularDynamics.Chapter03Review.collisionRegularity_statement
#check MolecularDynamics.Chapter03Review.collisionTimeRelation
#print axioms MolecularDynamics.Chapter03Review.collisionTimeRelation
#check MolecularDynamics.Chapter03Review.collisionalVerletOrder_statement
#print axioms MolecularDynamics.Chapter03Review.collisionalVerletOrder_statement
#check MolecularDynamics.Chapter03Review.collisionalVerletRelation
#print axioms MolecularDynamics.Chapter03Review.collisionalVerletRelation
#check MolecularDynamics.Chapter03Review.commutator
#print axioms MolecularDynamics.Chapter03Review.commutator
#check MolecularDynamics.Chapter03Review.commutingEnergySymmetry_statement
#print axioms MolecularDynamics.Chapter03Review.commutingEnergySymmetry_statement
#check MolecularDynamics.Chapter03Review.commutingEnergy_statement
#print axioms MolecularDynamics.Chapter03Review.commutingEnergy_statement
#check MolecularDynamics.Chapter03Review.commutingFlows_statement
#print axioms MolecularDynamics.Chapter03Review.commutingFlows_statement
#check MolecularDynamics.Chapter03Review.correctedReversedField
#print axioms MolecularDynamics.Chapter03Review.correctedReversedField
#check MolecularDynamics.Chapter03Review.decoupledOrder_statement
#print axioms MolecularDynamics.Chapter03Review.decoupledOrder_statement
#check MolecularDynamics.Chapter03Review.differentLogsCommute_statement
#print axioms MolecularDynamics.Chapter03Review.differentLogsCommute_statement
#check MolecularDynamics.Chapter03Review.elasticEnergy_statement
#print axioms MolecularDynamics.Chapter03Review.elasticEnergy_statement
#check MolecularDynamics.Chapter03Review.elasticReflection
#print axioms MolecularDynamics.Chapter03Review.elasticReflection
#check MolecularDynamics.Chapter03Review.energyProjectionRelation
#print axioms MolecularDynamics.Chapter03Review.energyProjectionRelation
#check MolecularDynamics.Chapter03Review.energySymplecticNoGo_statement
#print axioms MolecularDynamics.Chapter03Review.energySymplecticNoGo_statement
#check MolecularDynamics.Chapter03Review.equalComponentIntegral
#print axioms MolecularDynamics.Chapter03Review.equalComponentIntegral
#check MolecularDynamics.Chapter03Review.equalEulerIntegral_proved
#print axioms MolecularDynamics.Chapter03Review.equalEulerIntegral_proved
#check MolecularDynamics.Chapter03Review.equalEulerIntegral_statement
#print axioms MolecularDynamics.Chapter03Review.equalEulerIntegral_statement
#check MolecularDynamics.Chapter03Review.eulerOscillatorGrowth_statement
#print axioms MolecularDynamics.Chapter03Review.eulerOscillatorGrowth_statement
#check MolecularDynamics.Chapter03Review.exponentialFlat_statement
#print axioms MolecularDynamics.Chapter03Review.exponentialFlat_statement
#check MolecularDynamics.Chapter03Review.finiteMatching
#print axioms MolecularDynamics.Chapter03Review.finiteMatching
#check MolecularDynamics.Chapter03Review.flowObservable_statement
#print axioms MolecularDynamics.Chapter03Review.flowObservable_statement
#check MolecularDynamics.Chapter03Review.flowReversalIdentity_statement
#print axioms MolecularDynamics.Chapter03Review.flowReversalIdentity_statement
#check MolecularDynamics.Chapter03Review.flowReversal_statement
#print axioms MolecularDynamics.Chapter03Review.flowReversal_statement
#check MolecularDynamics.Chapter03Review.formalField
#print axioms MolecularDynamics.Chapter03Review.formalField
#check MolecularDynamics.Chapter03Review.formalHamiltonian
#print axioms MolecularDynamics.Chapter03Review.formalHamiltonian
#check MolecularDynamics.Chapter03Review.formalHamiltonianField
#print axioms MolecularDynamics.Chapter03Review.formalHamiltonianField
#check MolecularDynamics.Chapter03Review.formalObservable
#print axioms MolecularDynamics.Chapter03Review.formalObservable
#check MolecularDynamics.Chapter03Review.formalSplitting
#print axioms MolecularDynamics.Chapter03Review.formalSplitting
#check MolecularDynamics.Chapter03Review.formalStrang
#print axioms MolecularDynamics.Chapter03Review.formalStrang
#check MolecularDynamics.Chapter03Review.generalSplitting
#print axioms MolecularDynamics.Chapter03Review.generalSplitting
#check MolecularDynamics.Chapter03Review.hamiltonianLie
#print axioms MolecularDynamics.Chapter03Review.hamiltonianLie
#check MolecularDynamics.Chapter03Review.hamiltonianSpectrum_statement
#print axioms MolecularDynamics.Chapter03Review.hamiltonianSpectrum_statement
#check MolecularDynamics.Chapter03Review.hardCoreDomain
#print axioms MolecularDynamics.Chapter03Review.hardCoreDomain
#check MolecularDynamics.Chapter03Review.hardCorePotential
#print axioms MolecularDynamics.Chapter03Review.hardCorePotential
#check MolecularDynamics.Chapter03Review.kineticZero_proved
#print axioms MolecularDynamics.Chapter03Review.kineticZero_proved
#check MolecularDynamics.Chapter03Review.kineticZero_statement
#print axioms MolecularDynamics.Chapter03Review.kineticZero_statement
#check MolecularDynamics.Chapter03Review.leadingModifiedField_statement
#print axioms MolecularDynamics.Chapter03Review.leadingModifiedField_statement
#check MolecularDynamics.Chapter03Review.leadingShadowHamiltonian_statement
#print axioms MolecularDynamics.Chapter03Review.leadingShadowHamiltonian_statement
#check MolecularDynamics.Chapter03Review.leadingShadowPrinted_statement
#print axioms MolecularDynamics.Chapter03Review.leadingShadowPrinted_statement
#check MolecularDynamics.Chapter03Review.lieTaylor_statement
#print axioms MolecularDynamics.Chapter03Review.lieTaylor_statement
#check MolecularDynamics.Chapter03Review.linearEulerIntegral_proved
#print axioms MolecularDynamics.Chapter03Review.linearEulerIntegral_proved
#check MolecularDynamics.Chapter03Review.linearEulerIntegral_statement
#print axioms MolecularDynamics.Chapter03Review.linearEulerIntegral_statement
#check MolecularDynamics.Chapter03Review.linearInvolution
#print axioms MolecularDynamics.Chapter03Review.linearInvolution
#check MolecularDynamics.Chapter03Review.linearRKIntegral_proved
#print axioms MolecularDynamics.Chapter03Review.linearRKIntegral_proved
#check MolecularDynamics.Chapter03Review.linearRKIntegral_statement
#print axioms MolecularDynamics.Chapter03Review.linearRKIntegral_statement
#check MolecularDynamics.Chapter03Review.localOrder
#print axioms MolecularDynamics.Chapter03Review.localOrder
#check MolecularDynamics.Chapter03Review.mechanicalReversal_proved
#print axioms MolecularDynamics.Chapter03Review.mechanicalReversal_proved
#check MolecularDynamics.Chapter03Review.mechanicalReversal_statement
#print axioms MolecularDynamics.Chapter03Review.mechanicalReversal_statement
#check MolecularDynamics.Chapter03Review.modifiedCollisionProjection
#print axioms MolecularDynamics.Chapter03Review.modifiedCollisionProjection
#check MolecularDynamics.Chapter03Review.modifiedConstruction_statement
#print axioms MolecularDynamics.Chapter03Review.modifiedConstruction_statement
#check MolecularDynamics.Chapter03Review.modifiedEven_statement
#print axioms MolecularDynamics.Chapter03Review.modifiedEven_statement
#check MolecularDynamics.Chapter03Review.momentumProjection
#print axioms MolecularDynamics.Chapter03Review.momentumProjection
#check MolecularDynamics.Chapter03Review.momentumReversal
#print axioms MolecularDynamics.Chapter03Review.momentumReversal
#check MolecularDynamics.Chapter03Review.noHamiltonianAttractor_statement
#print axioms MolecularDynamics.Chapter03Review.noHamiltonianAttractor_statement
#check MolecularDynamics.Chapter03Review.obstacleReflection
#print axioms MolecularDynamics.Chapter03Review.obstacleReflection
#check MolecularDynamics.Chapter03Review.optimalTruncation_statement
#print axioms MolecularDynamics.Chapter03Review.optimalTruncation_statement
#check MolecularDynamics.Chapter03Review.oscillatorAdjointEuler
#print axioms MolecularDynamics.Chapter03Review.oscillatorAdjointEuler
#check MolecularDynamics.Chapter03Review.oscillatorEnergyFailure_proved
#print axioms MolecularDynamics.Chapter03Review.oscillatorEnergyFailure_proved
#check MolecularDynamics.Chapter03Review.oscillatorEnergyFailure_statement
#print axioms MolecularDynamics.Chapter03Review.oscillatorEnergyFailure_statement
#check MolecularDynamics.Chapter03Review.oscillatorShadow
#print axioms MolecularDynamics.Chapter03Review.oscillatorShadow
#check MolecularDynamics.Chapter03Review.oscillatorShadowInvariant_proved
#print axioms MolecularDynamics.Chapter03Review.oscillatorShadowInvariant_proved
#check MolecularDynamics.Chapter03Review.oscillatorShadowInvariant_statement
#print axioms MolecularDynamics.Chapter03Review.oscillatorShadowInvariant_statement
#check MolecularDynamics.Chapter03Review.pairForceDecoupling
#print axioms MolecularDynamics.Chapter03Review.pairForceDecoupling
#check MolecularDynamics.Chapter03Review.partitionedAffinePrinted_statement
#print axioms MolecularDynamics.Chapter03Review.partitionedAffinePrinted_statement
#check MolecularDynamics.Chapter03Review.partitionedAffine_statement
#print axioms MolecularDynamics.Chapter03Review.partitionedAffine_statement
#check MolecularDynamics.Chapter03Review.positionVerlet
#print axioms MolecularDynamics.Chapter03Review.positionVerlet
#check MolecularDynamics.Chapter03Review.potentialDoubleBracket_statement
#print axioms MolecularDynamics.Chapter03Review.potentialDoubleBracket_statement
#check MolecularDynamics.Chapter03Review.primitiveDefect_statement
#print axioms MolecularDynamics.Chapter03Review.primitiveDefect_statement
#check MolecularDynamics.Chapter03Review.primitiveOrder_statement
#print axioms MolecularDynamics.Chapter03Review.primitiveOrder_statement
#check MolecularDynamics.Chapter03Review.primitiveSplitting
#print axioms MolecularDynamics.Chapter03Review.primitiveSplitting
#check MolecularDynamics.Chapter03Review.processorEnergy_statement
#print axioms MolecularDynamics.Chapter03Review.processorEnergy_statement
#check MolecularDynamics.Chapter03Review.projectionConstraint
#print axioms MolecularDynamics.Chapter03Review.projectionConstraint
#check MolecularDynamics.Chapter03Review.projectionEnergy_proved
#print axioms MolecularDynamics.Chapter03Review.projectionEnergy_proved
#check MolecularDynamics.Chapter03Review.projectionEnergy_statement
#print axioms MolecularDynamics.Chapter03Review.projectionEnergy_statement
#check MolecularDynamics.Chapter03Review.projectionFactor
#print axioms MolecularDynamics.Chapter03Review.projectionFactor
#check MolecularDynamics.Chapter03Review.reversedField
#print axioms MolecularDynamics.Chapter03Review.reversedField
#check MolecularDynamics.Chapter03Review.reversedFieldPrinted_statement
#print axioms MolecularDynamics.Chapter03Review.reversedFieldPrinted_statement
#check MolecularDynamics.Chapter03Review.reversedTrajectory_statement
#print axioms MolecularDynamics.Chapter03Review.reversedTrajectory_statement
#check MolecularDynamics.Chapter03Review.reversibleMethod
#print axioms MolecularDynamics.Chapter03Review.reversibleMethod
#check MolecularDynamics.Chapter03Review.reversibleSpectrum_statement
#print axioms MolecularDynamics.Chapter03Review.reversibleSpectrum_statement
#check MolecularDynamics.Chapter03Review.reversibleVolumeFailure_statement
#print axioms MolecularDynamics.Chapter03Review.reversibleVolumeFailure_statement
#check MolecularDynamics.Chapter03Review.rkAffine_proved
#print axioms MolecularDynamics.Chapter03Review.rkAffine_proved
#check MolecularDynamics.Chapter03Review.rkAffine_statement
#print axioms MolecularDynamics.Chapter03Review.rkAffine_statement
#check MolecularDynamics.Chapter03Review.scalarVerletShadow4
#print axioms MolecularDynamics.Chapter03Review.scalarVerletShadow4
#check MolecularDynamics.Chapter03Review.shadowPositive_statement
#print axioms MolecularDynamics.Chapter03Review.shadowPositive_statement
#check MolecularDynamics.Chapter03Review.smoothSymplecticData
#print axioms MolecularDynamics.Chapter03Review.smoothSymplecticData
#check MolecularDynamics.Chapter03Review.strangCubic_statement
#print axioms MolecularDynamics.Chapter03Review.strangCubic_statement
#check MolecularDynamics.Chapter03Review.strangInverse_statement
#print axioms MolecularDynamics.Chapter03Review.strangInverse_statement
#check MolecularDynamics.Chapter03Review.symmetricAffineReversible_statement
#print axioms MolecularDynamics.Chapter03Review.symmetricAffineReversible_statement
#check MolecularDynamics.Chapter03Review.symmetricMethod
#print axioms MolecularDynamics.Chapter03Review.symmetricMethod
#check MolecularDynamics.Chapter03Review.symplecticEulerShadow3
#print axioms MolecularDynamics.Chapter03Review.symplecticEulerShadow3
#check MolecularDynamics.Chapter03Review.symplecticEulerShadowMatching_statement
#print axioms MolecularDynamics.Chapter03Review.symplecticEulerShadowMatching_statement
#check MolecularDynamics.Chapter03Review.symplecticNotReversible_statement
#print axioms MolecularDynamics.Chapter03Review.symplecticNotReversible_statement
#check MolecularDynamics.Chapter03Review.symplecticSpectrum_statement
#print axioms MolecularDynamics.Chapter03Review.symplecticSpectrum_statement
#check MolecularDynamics.Chapter03Review.takahashiProcessor
#print axioms MolecularDynamics.Chapter03Review.takahashiProcessor
#check MolecularDynamics.Chapter03Review.takahashiShadow2
#print axioms MolecularDynamics.Chapter03Review.takahashiShadow2
#check MolecularDynamics.Chapter03Review.theorem31_statement
#print axioms MolecularDynamics.Chapter03Review.theorem31_statement
#check MolecularDynamics.Chapter03Review.trapezoidalProperties_statement
#print axioms MolecularDynamics.Chapter03Review.trapezoidalProperties_statement
#check MolecularDynamics.Chapter03Review.trapezoidalRelation
#print axioms MolecularDynamics.Chapter03Review.trapezoidalRelation
#check MolecularDynamics.Chapter03Review.truncatedFlow
#print axioms MolecularDynamics.Chapter03Review.truncatedFlow
#check MolecularDynamics.Chapter03Review.verletHamiltonianParts
#print axioms MolecularDynamics.Chapter03Review.verletHamiltonianParts
#check MolecularDynamics.Chapter03Review.verletModifiedH
#print axioms MolecularDynamics.Chapter03Review.verletModifiedH
#check MolecularDynamics.Chapter03Review.verletModifiedHPrinted_statement
#print axioms MolecularDynamics.Chapter03Review.verletModifiedHPrinted_statement
#check MolecularDynamics.Chapter03Review.verletModifiedH_statement
#print axioms MolecularDynamics.Chapter03Review.verletModifiedH_statement
#check MolecularDynamics.Chapter03Review.verletOscillatorEnergy_statement
#print axioms MolecularDynamics.Chapter03Review.verletOscillatorEnergy_statement
#check MolecularDynamics.Chapter03Review.verletVariants_proved
#print axioms MolecularDynamics.Chapter03Review.verletVariants_proved
#check MolecularDynamics.Chapter03Review.verletVariants_statement
#print axioms MolecularDynamics.Chapter03Review.verletVariants_statement
#check MolecularDynamics.Chapter03Review.volumeNotSymplectic_statement
#print axioms MolecularDynamics.Chapter03Review.volumeNotSymplectic_statement
#check MolecularDynamics.Chapter03Review.yoshida4
#print axioms MolecularDynamics.Chapter03Review.yoshida4
#check MolecularDynamics.Chapter03Review.yoshida4Structure_proved
#print axioms MolecularDynamics.Chapter03Review.yoshida4Structure_proved
#check MolecularDynamics.Chapter03Review.yoshida4Structure_statement
#print axioms MolecularDynamics.Chapter03Review.yoshida4Structure_statement
#check MolecularDynamics.Chapter03Review.yoshidaCancellation_statement
#print axioms MolecularDynamics.Chapter03Review.yoshidaCancellation_statement
#check MolecularDynamics.Chapter03Review.yoshidaCoefficients
#print axioms MolecularDynamics.Chapter03Review.yoshidaCoefficients
#check MolecularDynamics.Chapter03Review.yoshidaCompose
#print axioms MolecularDynamics.Chapter03Review.yoshidaCompose
#check MolecularDynamics.Chapter03Review.yoshidaRaiseOrder_statement
#print axioms MolecularDynamics.Chapter03Review.yoshidaRaiseOrder_statement
#check MolecularDynamics.Chapter03Review.yoshidaUnique_statement
#print axioms MolecularDynamics.Chapter03Review.yoshidaUnique_statement
#check MolecularDynamics.contDiffOn_textbookTruncatedHamiltonian
#print axioms MolecularDynamics.contDiffOn_textbookTruncatedHamiltonian
#check MolecularDynamics.energy_step_count_power_factor
#print axioms MolecularDynamics.energy_step_count_power_factor
#check MolecularDynamics.exists_compact_C1_lipschitz_constant
#print axioms MolecularDynamics.exists_compact_C1_lipschitz_constant
#check MolecularDynamics.exists_uniform_textbookTruncatedHamiltonian_lipschitz
#print axioms MolecularDynamics.exists_uniform_textbookTruncatedHamiltonian_lipschitz
#check MolecularDynamics.exists_uniform_textbookTruncatedHamiltonian_remainder
#print axioms MolecularDynamics.exists_uniform_textbookTruncatedHamiltonian_remainder
#check MolecularDynamics.hasDerivAt_textbookLieDerivative
#print axioms MolecularDynamics.hasDerivAt_textbookLieDerivative
#check MolecularDynamics.hasDerivAt_textbookLieDerivative_second
#print axioms MolecularDynamics.hasDerivAt_textbookLieDerivative_second
#check MolecularDynamics.hasDerivWithinAt_textbookPoissonBracket
#print axioms MolecularDynamics.hasDerivWithinAt_textbookPoissonBracket
#check MolecularDynamics.oneStep_energy_telescoping
#print axioms MolecularDynamics.oneStep_energy_telescoping
#check MolecularDynamics.textbookFormalModifiedExponential_matches_product
#print axioms MolecularDynamics.textbookFormalModifiedExponential_matches_product
#check MolecularDynamics.textbookFormalOperatorDifference_coeff_three
#print axioms MolecularDynamics.textbookFormalOperatorDifference_coeff_three
#check MolecularDynamics.textbookFormalOperatorDifference_coeff_two
#print axioms MolecularDynamics.textbookFormalOperatorDifference_coeff_two
#check MolecularDynamics.textbookFormalOperatorExponential
#print axioms MolecularDynamics.textbookFormalOperatorExponential
#check MolecularDynamics.textbookFormalOperatorExponential_coeff
#print axioms MolecularDynamics.textbookFormalOperatorExponential_coeff
#check MolecularDynamics.textbookFormalOperatorProduct_coeff_one
#print axioms MolecularDynamics.textbookFormalOperatorProduct_coeff_one
#check MolecularDynamics.textbookFormalOperatorProduct_coeff_three
#print axioms MolecularDynamics.textbookFormalOperatorProduct_coeff_three
#check MolecularDynamics.textbookFormalOperatorProduct_coeff_two
#print axioms MolecularDynamics.textbookFormalOperatorProduct_coeff_two
#check MolecularDynamics.textbookFormalOperatorProduct_coeff_zero
#print axioms MolecularDynamics.textbookFormalOperatorProduct_coeff_zero
#check MolecularDynamics.textbookHamiltonianFlow_isSymplectic_of_jointC2
#print axioms MolecularDynamics.textbookHamiltonianFlow_isSymplectic_of_jointC2
#check MolecularDynamics.textbookHamiltonianFlow_volume_image_of_jointC2
#print axioms MolecularDynamics.textbookHamiltonianFlow_volume_image_of_jointC2
#check MolecularDynamics.textbookHamiltonianLieDerivative_add
#print axioms MolecularDynamics.textbookHamiltonianLieDerivative_add
#check MolecularDynamics.textbookHamiltonianLieDerivative_commutator
#print axioms MolecularDynamics.textbookHamiltonianLieDerivative_commutator
#check MolecularDynamics.textbookHamiltonian_energy_const_on_Icc
#print axioms MolecularDynamics.textbookHamiltonian_energy_const_on_Icc
#check MolecularDynamics.textbookLieDerivative
#print axioms MolecularDynamics.textbookLieDerivative
#check MolecularDynamics.textbookLieDerivative_hamiltonian_eq_poisson
#print axioms MolecularDynamics.textbookLieDerivative_hamiltonian_eq_poisson
#check MolecularDynamics.textbookPoissonBracket
#print axioms MolecularDynamics.textbookPoissonBracket
#check MolecularDynamics.textbookPoissonBracket_coordinates
#print axioms MolecularDynamics.textbookPoissonBracket_coordinates
#check MolecularDynamics.textbookPoissonBracket_jacobi
#print axioms MolecularDynamics.textbookPoissonBracket_jacobi
#check MolecularDynamics.textbookPoissonBracket_linear_left
#print axioms MolecularDynamics.textbookPoissonBracket_linear_left
#check MolecularDynamics.textbookPoissonBracket_linear_right
#print axioms MolecularDynamics.textbookPoissonBracket_linear_right
#check MolecularDynamics.textbookPoissonBracket_self
#print axioms MolecularDynamics.textbookPoissonBracket_self
#check MolecularDynamics.textbookPoissonBracket_skew
#print axioms MolecularDynamics.textbookPoissonBracket_skew
#check MolecularDynamics.textbookSymplecticEuler_isSymplectic
#print axioms MolecularDynamics.textbookSymplecticEuler_isSymplectic
#check MolecularDynamics.textbookTruncatedHamiltonian
#print axioms MolecularDynamics.textbookTruncatedHamiltonian
#check MolecularDynamics.textbookTruncatedHamiltonian_difference_isBigO
#print axioms MolecularDynamics.textbookTruncatedHamiltonian_difference_isBigO
#check MolecularDynamics.textbook_conjugate_iterates
#print axioms MolecularDynamics.textbook_conjugate_iterates
#check MolecularDynamics.textbook_conjugate_iterates_tendsto_iff
#print axioms MolecularDynamics.textbook_conjugate_iterates_tendsto_iff
#check MolecularDynamics.textbook_energy_drift_le_actual_defects
#print axioms MolecularDynamics.textbook_energy_drift_le_actual_defects
#check MolecularDynamics.textbook_energy_drift_rate_of_flow_defect
#print axioms MolecularDynamics.textbook_energy_drift_rate_of_flow_defect
