import Mathlib.Algebra.Lie.OfAssociative
import Mathlib.Algebra.Lie.Subalgebra
import Mathlib.Analysis.Calculus.VectorField
import Mathlib.Analysis.Normed.Module.FiniteDimension
import Mathlib.LinearAlgebra.Matrix.ToLin

/-! Lemma8.1, printed347/PDF368: the actual linear thermostat fields and their Lie closure.
The real derivative bracket is explicitly related to the opposite endomorphism commutator.
-/

open Matrix

namespace MolecularDynamics

attribute [local instance] LieRing.ofAssociativeRing

abbrev textbookThermostatPhase (Nc : ℕ) := (Fin Nc → ℝ) × (Fin Nc → ℝ)

/-- The actual Hamiltonian linear field (p,-Aq). -/
noncomputable def textbookThermostatF {Nc : ℕ} (A : Matrix (Fin Nc) (Fin Nc) ℝ) :
    Module.End ℝ (textbookThermostatPhase Nc) :=
  (LinearMap.snd ℝ (Fin Nc → ℝ) (Fin Nc → ℝ)).prod
    (-A.toLin'.comp (LinearMap.fst ℝ (Fin Nc → ℝ) (Fin Nc → ℝ)))

/-- The actual momentum scaling field (0,p). -/
noncomputable def textbookThermostatG (Nc : ℕ) : Module.End ℝ (textbookThermostatPhase Nc) :=
  (0 : textbookThermostatPhase Nc →ₗ[ℝ] (Fin Nc → ℝ)).prod
    (LinearMap.snd ℝ (Fin Nc → ℝ) (Fin Nc → ℝ))

/-- Internal index k corresponds to the textbook C_(k+1). -/
noncomputable def textbookThermostatC {Nc : ℕ} (A : Matrix (Fin Nc) (Fin Nc) ℝ) (k : ℕ) :
    Module.End ℝ (textbookThermostatPhase Nc) :=
  ((A ^ k).toLin'.comp (LinearMap.snd ℝ (Fin Nc → ℝ) (Fin Nc → ℝ))).prod
    ((A ^ (k + 1)).toLin'.comp (LinearMap.fst ℝ (Fin Nc → ℝ) (Fin Nc → ℝ)))

/-- Internal index k corresponds to the textbook D_(k+1). -/
noncomputable def textbookThermostatD {Nc : ℕ} (A : Matrix (Fin Nc) (Fin Nc) ℝ) (k : ℕ) :
    Module.End ℝ (textbookThermostatPhase Nc) :=
  ((A ^ (k + 1)).toLin'.comp (LinearMap.fst ℝ (Fin Nc → ℝ) (Fin Nc → ℝ))).prod
    (-((A ^ (k + 1)).toLin'.comp (LinearMap.snd ℝ (Fin Nc → ℝ) (Fin Nc → ℝ))))

theorem textbookThermostatF_apply {Nc : ℕ} (A : Matrix (Fin Nc) (Fin Nc) ℝ)
    (z : textbookThermostatPhase Nc) : textbookThermostatF A z = (z.2, -(A *ᵥ z.1)) := rfl

theorem textbookThermostatG_apply (Nc : ℕ) (z : textbookThermostatPhase Nc) :
    textbookThermostatG Nc z = (0, z.2) := rfl

theorem textbookThermostatC_apply {Nc : ℕ} (A : Matrix (Fin Nc) (Fin Nc) ℝ)
    (k : ℕ) (z : textbookThermostatPhase Nc) :
    textbookThermostatC A k z = ((A ^ k) *ᵥ z.2, (A ^ (k + 1)) *ᵥ z.1) := rfl

theorem textbookThermostatD_apply {Nc : ℕ} (A : Matrix (Fin Nc) (Fin Nc) ℝ)
    (k : ℕ) (z : textbookThermostatPhase Nc) :
    textbookThermostatD A k z = ((A ^ (k + 1)) *ᵥ z.1, -((A ^ (k + 1)) *ᵥ z.2)) := rfl

/-- The genuine fderiv bracket of linear fields is the opposite End commutator. -/
theorem textbookThermostatLinearField_lieBracket {Nc : ℕ}
    (X Y : Module.End ℝ (textbookThermostatPhase Nc)) (z : textbookThermostatPhase Nc) :
    VectorField.lieBracket ℝ (fun x ↦ X x) (fun x ↦ Y x) z = -(⁅X, Y⁆ z) := by
  have hx : fderiv ℝ (fun x ↦ X x) z = LinearMap.toContinuousLinearMap X :=
    (LinearMap.toContinuousLinearMap X).hasFDerivAt.fderiv
  have hy : fderiv ℝ (fun x ↦ Y x) z = LinearMap.toContinuousLinearMap Y :=
    (LinearMap.toContinuousLinearMap Y).hasFDerivAt.fderiv
  rw [VectorField.lieBracket, hx, hy]
  change Y (X z) - X (Y z) = -(X (Y z) - Y (X z))
  abel

theorem textbookThermostat_lie_F_G {Nc : ℕ} (A : Matrix (Fin Nc) (Fin Nc) ℝ) :
    ⁅textbookThermostatF A, textbookThermostatG Nc⁆ = textbookThermostatC A 0 := by
  apply LinearMap.ext
  intro z
  simp [Ring.lie_def, Module.End.mul_apply, textbookThermostatF_apply,
    textbookThermostatG_apply, textbookThermostatC_apply]

theorem textbookThermostat_lie_F_C {Nc : ℕ} (A : Matrix (Fin Nc) (Fin Nc) ℝ) (k : ℕ) :
    (1 / 2 : ℝ) • ⁅textbookThermostatF A, textbookThermostatC A k⁆ =
      textbookThermostatD A k := by
  apply LinearMap.ext
  intro z
  apply Prod.ext
  · change (1 / 2 : ℝ) • ((A ^ (k + 1)) *ᵥ z.1 - (A ^ k) *ᵥ (-(A *ᵥ z.1))) =
      (A ^ (k + 1)) *ᵥ z.1
    simp only [Matrix.mulVec_neg, Matrix.mulVec_mulVec, ← pow_succ]
    module
  · change (1 / 2 : ℝ) • (-(A *ᵥ ((A ^ k) *ᵥ z.2)) - (A ^ (k + 1)) *ᵥ z.2) =
      -((A ^ (k + 1)) *ᵥ z.2)
    simp only [Matrix.mulVec_mulVec, ← pow_succ']
    module

theorem textbookThermostat_lie_D_F {Nc : ℕ} (A : Matrix (Fin Nc) (Fin Nc) ℝ) (k : ℕ) :
    (1 / 2 : ℝ) • ⁅textbookThermostatD A k, textbookThermostatF A⁆ =
      textbookThermostatC A (k + 1) := by
  apply LinearMap.ext
  intro z
  apply Prod.ext
  · change (1 / 2 : ℝ) • ((A ^ (k + 1)) *ᵥ z.2 - (-((A ^ (k + 1)) *ᵥ z.2))) =
      (A ^ (k + 1)) *ᵥ z.2
    module
  · change (1 / 2 : ℝ) • (-((A ^ (k + 1)) *ᵥ (-(A *ᵥ z.1))) -
      (-(A *ᵥ ((A ^ (k + 1)) *ᵥ z.1)))) = (A ^ (k + 1 + 1)) *ᵥ z.1
    simp only [Matrix.mulVec_neg, neg_neg, Matrix.mulVec_mulVec, ← pow_succ,
      ← pow_succ']
    module

/-- The genuine finite-dimensional Lie subalgebra generated by the actual F and G. -/
noncomputable def textbookThermostatLieSpan {Nc : ℕ} (A : Matrix (Fin Nc) (Fin Nc) ℝ) :
    LieSubalgebra ℝ (Module.End ℝ (textbookThermostatPhase Nc)) :=
  LieSubalgebra.lieSpan ℝ _ {textbookThermostatF A, textbookThermostatG Nc}

/-- The represented subspace is closed under the actual derivative bracket of vector fields. -/
theorem textbookThermostatLieSpan_vectorField_closed {Nc : ℕ}
    (A : Matrix (Fin Nc) (Fin Nc) ℝ)
    (X Y : Module.End ℝ (textbookThermostatPhase Nc))
    (hx : X ∈ textbookThermostatLieSpan A) (hy : Y ∈ textbookThermostatLieSpan A) :
    ∃ Z : Module.End ℝ (textbookThermostatPhase Nc), Z ∈ textbookThermostatLieSpan A ∧
      ∀ z, VectorField.lieBracket ℝ (fun x ↦ X x) (fun x ↦ Y x) z = Z z := by
  refine ⟨-⁅X, Y⁆, (textbookThermostatLieSpan A).neg_mem
    ((textbookThermostatLieSpan A).lie_mem hx hy), ?_⟩
  intro z
  exact textbookThermostatLinearField_lieBracket X Y z

/-- Lemma8.1: both actual fields belong to the true generated Lie subalgebra for every order. -/
theorem textbookThermostat_C_D_mem_lieSpan {Nc : ℕ} (A : Matrix (Fin Nc) (Fin Nc) ℝ) (k : ℕ) :
    textbookThermostatC A k ∈ textbookThermostatLieSpan A ∧
      textbookThermostatD A k ∈ textbookThermostatLieSpan A := by
  have hF : textbookThermostatF A ∈ textbookThermostatLieSpan A :=
    LieSubalgebra.subset_lieSpan (by simp)
  have hG : textbookThermostatG Nc ∈ textbookThermostatLieSpan A :=
    LieSubalgebra.subset_lieSpan (by simp)
  have hd (j : ℕ) (hc : textbookThermostatC A j ∈ textbookThermostatLieSpan A) :
      textbookThermostatD A j ∈ textbookThermostatLieSpan A := by
    rw [← textbookThermostat_lie_F_C A j]
    exact (textbookThermostatLieSpan A).smul_mem (1 / 2 : ℝ)
      ((textbookThermostatLieSpan A).lie_mem hF hc)
  induction k with
  | zero =>
    have hc : textbookThermostatC A 0 ∈ textbookThermostatLieSpan A := by
      rw [← textbookThermostat_lie_F_G A]
      exact (textbookThermostatLieSpan A).lie_mem hF hG
    exact ⟨hc, hd 0 hc⟩
  | succ k ih =>
    have hc : textbookThermostatC A (k + 1) ∈ textbookThermostatLieSpan A := by
      rw [← textbookThermostat_lie_D_F A k]
      exact (textbookThermostatLieSpan A).smul_mem (1 / 2 : ℝ)
        ((textbookThermostatLieSpan A).lie_mem ih.2 hF)
    exact ⟨hc, hd (k + 1) hc⟩

end MolecularDynamics
